discourse/discourse-chat

lib/chat_message_creator.rb

I refactored chat URLs to include the chat channel ID, and this was missed.

FIX: Correct chat notification URLs

---

assets/javascripts/discourse/components/chat-composer.js
assets/javascripts/discourse/templates/components/chat-composer.hbs
assets/stylesheets/desktop/desktop.scss
assets/stylesheets/mobile/mobile.scss

Dependent on this PR being merged first - https://github.com/discourse/discourse/pull/14976
Also I could not get `autocomplete` popup to go up on mobile - currently its cut off going down. Setting bottom value seems to work well! I didn't see any cases where it _doesn't_ work.

FIX: Implement emoji picker

---

app/controllers/chat_base_controller.rb
app/controllers/chat_controller.rb
app/models/chat_channel.rb
app/serializers/chat_base_message_serializer.rb
app/serializers/chat_view_serializer.rb
assets/javascripts/discourse/components/channel-list.js
assets/javascripts/discourse/templates/components/channel-list.hbs
assets/javascripts/discourse/templates/components/chat-channel-settings-row.hbs
assets/javascripts/discourse/templates/components/chat-channel-title.hbs
assets/stylesheets/common/common.scss
config/locales/client.en.yml
config/locales/server.en.yml
config/settings.yml
db/fixtures/001_chat_channels.rb
lib/chat_channel_fetcher.rb
lib/chat_seeder.rb
lib/guardian_extensions.rb
plugin.rb
spec/components/chat_message_creator_spec.rb
spec/components/chat_message_updater_spec.rb
spec/components/chat_seeder_spec.rb
spec/fabricators/chat_fabricator.rb
spec/models/chat_channel_spec.rb
spec/requests/admin/admin_incoming_chat_webhooks_controller_spec.rb
spec/requests/chat_channel_controller_spec.rb
spec/requests/chat_controller_spec.rb
spec/requests/incoming_chat_webhooks_controller_spec.rb

This removes the one-off `staff-only` chat channel in favor of an auto-seeded staff category chat channel.
Also adds nice text and prompt for the channel list has no channels:
In sidebar
In float

DEV: Remove staff-only chat and seed staff category channel

---

assets/javascripts/discourse/templates/components/chat-channel-title.hbs
assets/stylesheets/common/common.scss

UX: Align title elements

---

assets/javascripts/discourse/components/chat-live-pane.js

Safari/Webkit appears to have a bug with `flex-direction: column-reverse`, on first load, it doesn't update the location of the scrollbar. The scrollbar is stuck at the top of the element, even though the element contents is scrolled to the bottom. 
This workaround triggers a 1-pixel scroll, to force recalculating the position of the scrollbar.

Workaround for Safari scrollbar position

---

assets/javascripts/discourse/services/chat-notification-manager.js

Following core change in https://github.com/discourse/discourse/commit/af4b8d0e21f823463a1f8a613aedf9bc845a62e1

FIX: Ensure the user remains 'present' in notification-routing channels

---

assets/javascripts/discourse/components/chat-channel-title.js
assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/components/topic-chat-float.js
assets/javascripts/discourse/templates/components/chat-channel-settings-row.hbs
assets/javascripts/discourse/templates/components/chat-live-pane.hbs
assets/javascripts/discourse/templates/components/topic-chat-float.hbs
assets/stylesheets/common/common.scss

This does a few things:
* Sets max-height on chat channel settings modal
* Removes links around chat-channel-title in favor of passed in action
*  Huge benefit of this is that we can make the title expand the widget when it is hidden on click.
* Expands widget when it was collapsed and sidebar link is clicked on
* Cleans up a ton of css

FIX: Remove links around chat channel title

---

plugin.rb

Otherwise, a `nil` value for `allowed_group_ids` and `allowed_user_ids` will mean nobody is allowed access

FIX: Make PresenceChannel 'public' for unsecured categories/topics

---

assets/javascripts/discourse/templates/components/tc-message.hbs

Previously all the space below it would also trigger the card.

FIX: Display user card only on actual avatar click

---

app/serializers/chat_base_message_serializer.rb
test/javascripts/acceptance/chat-test.js
test/javascripts/chat-fixtures.js

Branch name is whack, sorry.
`in_reply_to` was being thrown out by the ember store because `in_reply_to_id` was serialized (unnecessarily). Removed and the reply-to line is rendered again.

FIX: Reply-to line rendering

---

assets/javascripts/discourse/components/chat-composer.js
assets/javascripts/discourse/templates/components/chat-composer.hbs
assets/javascripts/discourse/templates/components/chat-replying-indicator.hbs
assets/stylesheets/common/common.scss

Otherwise, the UI will jump around when people start/stop replying
Partial revert of ab5117dcd645ebe2144512e224da8d6c32160a34.
To reduce the unused space, this PR hides the uploads-container div when it's empty.

Ensure space is reserved for the 'replying...' indicator

---

assets/javascripts/discourse/components/chat-upload.js
assets/javascripts/discourse/templates/components/chat-upload.hbs

This restricts image height/width to the proper site settings. For posts this is done in `PostCookedProcessor` because the images are in the `cooked` content. Since uploads are rendered differently here, we can super easily fix the dimensions on the client.

UX: Restrict image height/width

---

assets/javascripts/discourse/components/full-page-chat.js
assets/stylesheets/common/common.scss
assets/stylesheets/desktop/desktop.scss

No more listening to "resize" event or manual height var calculation. The issue in the Desktop app was that the content was taller than the app window (when you had a lot of channels/personal messages)

FIX: Drop --full-page-chat-height to fix app height issue

---

assets/javascripts/discourse/components/chat-live-pane.js

Currently it takes 2 seconds to have messages marked as read. It feels awkwardly wrong to me; bumping down to 1 second.

DEV: Speed up marking messages as read

---

assets/stylesheets/common/common.scss
assets/stylesheets/desktop/desktop.scss

* Change typing indicator color to match core
* Remove a macOS-Firefox-specific property
* Fix border radius issues on desktop full-page-chat

UX: Small CSS tweaks

---

assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/components/tc-message.js
assets/javascripts/discourse/templates/components/chat-live-pane.hbs
assets/javascripts/discourse/templates/components/tc-message.hbs
assets/stylesheets/common/common.scss
test/javascripts/acceptance/chat-test.js

First I was tackling sticking to the bottom when new reactions come in that could force chat up. Then I started to think more about the last read message scrolling as it's a bit janky.
I realized a much better way is to add a boolean to the newest message with the indicator at the top, so that it's always scrolled perfectly, with the "New messages" line right at the top. It works much better this way.

FIX: All sorts of scroll improvements

---

assets/javascripts/discourse/services/chat.js

The PresenceChannel default is 'browser in the background for 10s', which is a little aggressive for this use case. Users appear to constantly go online/offline, which is quite annoying. This commit updates the timeout to 60 seconds.
Requires https://github.com/discourse/discourse/pull/15217 to make it work, but won't blow up if installed on an earlier Discourse version

UX: Increase the time before a user is marked 'offline'

---

spec/components/chat_message_creator_spec.rb
spec/components/chat_message_updater_spec.rb
spec/jobs/process_chat_message_spec.rb
spec/models/chat_channel_spec.rb
spec/requests/admin/admin_incoming_chat_webhooks_controller_spec.rb
spec/requests/chat_channel_controller_spec.rb
spec/requests/chat_controller_spec.rb
spec/requests/direct_messages_controller_spec.rb
spec/requests/incoming_chat_webhooks_controller_spec.rb
spec/requests/move_to_topic_controller_spec.rb

This is no longer needed as at https://github.com/discourse/discourse/commit/0edacbd8f7f2bf153f11fc8f7579b30ba7f368c6

DEV: Remove requires for fabricators

---

app/controllers/incoming_chat_webhooks_controller.rb
lib/slack_compatibility.rb
plugin.rb
spec/lib/slack_compatibility_spec.rb
spec/requests/incoming_chat_webhooks_controller_spec.rb

This commit adds support for slack-compatible webhooks, which
many other integrations already support (including Mattermost,
OpsGenie, etc.)
To use the slack compatible version of the webhook, post to
the webhook URL and append `/slack` at the end, e.g.
https://meta.discourse.org/chat/hooks/ID/slack.json
See https://api.slack.com/reference/messaging/payload for the
slack message payload format. For now we only support the
text param, which we preprocess lightly to remove the slack-isms
in the formatting.
Later on down the track we may want to process blocks, attachments,
and user mentions in the text.

FEATURE: Slack-compatible webhooks

---

app/controllers/incoming_chat_webhooks_controller.rb
config/settings.yml
lib/slack_compatibility.rb
spec/requests/incoming_chat_webhooks_controller_spec.rb

Very minimal handling of the attachments part of the
slack webhook payload, to handle our OpsGenie integration,
which does not use the top-level `text` field.
This is quite barebones and needs to be expanded upon in
future. We are just using the `fallback` field for now because
it contains all the text we need from the other attachment
fields. See https://api.slack.com/reference/messaging/attachments
for more details.
Also added a SiteSetting.chat_debug_webhook_payloads setting
to drop the webhook payloads into the Rails logger when
enabled, so we can look at them in a nicer way.

FEATURE: Handle attachments for Slack webhooks

---

assets/javascripts/discourse/components/tc-message.js

Appending to body was triggering infinite scroll on topic list.

FIX: append to current element instead of body

---

assets/stylesheets/common/common.scss

I know important is bad, but it's IMPORTANT! We have the background color set to various things (in widget or in full-screen), and then we have hover background color, but we waant to always ignore all of that and show the highlight when it should be there.

FIX: Properly highlight chat messages

---

assets/javascripts/discourse/components/chat-composer.js
assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/services/chat.js
assets/javascripts/discourse/templates/components/chat-composer.hbs
assets/javascripts/discourse/templates/components/chat-live-pane.hbs
test/javascripts/acceptance/chat-test.js

Very simple implementation: store text/uploads in a `drafts` object in the chat service, with the channel ID as the key. When a new chat channel is opened, load the draft into the composer, and keep it updated while the user inputs text/uploads/sends messages.
Coolest thing about this is if you are typing in the widget and expand into full page, your uploads/text will still be there :)
Oh also, this make the composer textarea **not-** disabled when uploads are processing. That was old logic when the uploads went into markdown

FEATURE: Client-side per-channel drafts

---

assets/javascripts/discourse/components/chat-composer.js
test/javascripts/acceptance/chat-test.js

I changed the behavior of reset and forgot to switch this usage of `reset` to the new function `cancelEditing`

FIX: Escape while editing message calls correct func

---

assets/javascripts/discourse/components/chat-composer.js

There was also a double check for if the `messageIsValid` for both `internalEditMessage` and `internalSendMessage` (they're both called after the verifications)

UX: Don't do the ugly text bounce on edit

---

assets/javascripts/discourse/templates/components/category-chat-settings.hbs

https://dev.discourse.org/t/incorrect-capitalization-in-chat-category-extension/57436

Capitalize chat title.

---

assets/javascripts/discourse/components/chat-composer.js

In chat since "ENTER" submits a message we need to be a bit more protective
of autocomplete dialog.
Hold off for at least 2 chars and avoid autocomplete unless there are 2 non
symbol letters, this catches most commonly typed word emojis

FEATURE: hold back on emoji autocomplete

---

assets/javascripts/discourse/components/chat-composer.js

`throttle` doesn't work with anonymous functions. If you do this, throttle is being handed a brand new function instance each time, and it has no way to know they are identical.

Fix textarea input throttling

---

assets/javascripts/discourse/templates/components/chat-composer-message-details.hbs
assets/javascripts/discourse/templates/components/tc-message.hbs

Currently chat bot emojis are not rendered in the reply-to line, and the system icon is rendered. This fixes that, as well as rendering emojis in reply-to line, as well as composer edit/reply line.

UX: Render emojis in reply-to and bot emoji

---

assets/javascripts/discourse/widgets/chat-mention-notification-item.js

This is a bit of an optimistic fix, as I can't reproduce the issue locally, but on dev if you click a mention notification, the parent widget isn't re-rendering properly and I believe this will fix it

FIX: Don't preventDefault on notification click

---

assets/stylesheets/common/common.scss

The `highlight` color for the background and `primary-high` for the text color don't fill too well on dark themes. `tertiary` with `primary-very-high` look a lot better:

FIX: Use `tertiary` color as background for highlighted mentions

---

assets/stylesheets/common/common.scss

Extra (invisible) padding makes it easier to move the mouse cursor over to .tc-msgactions without making it disappear.

UX: Make msgactions easier to use

---

assets/stylesheets/common/common.scss

Screenshot:
This styling matches core's styling for alerts/banners like these:

FIX: Make highlighted mentions standout in dark themes

---

assets/javascripts/discourse/controllers/preferences-chat.js
assets/javascripts/discourse/routes/preferences-chat.js
assets/javascripts/discourse/templates/preferences/chat.hbs
config/locales/client.en.yml
test/javascripts/acceptance/chat-test.js

This is to merge the functionality of `minimal_chat_view` into `isolate_chat`. The sidebar plugin is what actually uses the preference - https://github.com/discourse-org/discourse-teams-sidebar/pull/254

DEV: Remove minimal chat view user preference

---

app/jobs/regular/send_chat_notifications.rb
lib/chat_message_creator.rb
lib/chat_message_updater.rb
lib/chat_notifier.rb
lib/guardian_extensions.rb
plugin.rb
spec/components/chat_message_creator_spec.rb
spec/components/chat_message_updater_spec.rb
spec/jobs/send_chat_notifications_spec.rb
spec/requests/chat_channel_controller_spec.rb

This moves the chat notification logic from the chat message creator/updater and into a job that is enqueued 5 seconds after message creation/edit.
This job also simply returns in a `ChatMessageRevision` record is created in-between the job being enqueued and it being run. This means the message was edited and a new job will handle it.

FEATURE: Wait 5 seconds to send notifications, to make sure user hasn't read

---

app/controllers/chat_controller.rb
lib/chat_message_creator.rb
lib/chat_message_updater.rb
spec/requests/chat_controller_spec.rb

I'm sorry @eviltrout I have to do multiple queries here for the AR callbacks to run and send message_bus data to the client to the count actually clears.
Also lower time to enqueue notify job to 3 seconds. 5 is so long.

FEATURE: Mark unread chat mentions as read when messages are read

---

assets/javascripts/discourse/components/chat-live-pane.js

When a GitHub onebox renders off-screen, calling `scrollIntoView` would scroll the entire chat window up to the onebox. This is not what we want.
All we want to do is scroll the `.onebox .onebox-body` div so that the selected line is in view
Unfortunately calculating the y-position of that line relative to the `.onebox-body` is quite complicated, but I think this should be pretty robust.

FIX: Don't scroll the entire chat pane to GitHub oneboxes

---

assets/javascripts/discourse/components/tc-message.js
assets/javascripts/discourse/templates/components/tc-message.hbs

We can't use popper here because we want the position to be `fixed` not `absolute`. The previous calculations were _good_, but do not work when the composer opened. 
This uses `bottom` instead of `top` so that we can keep the emoji picker moving up with the chat window when the composer opens up. Also uses `usePopper: false` [added here](https://github.com/discourse/discourse/pull/15256), to make sure the position doesn't change when the composer is opened.

FIX: Emoji picker position

---

assets/javascripts/discourse/components/chat-composer.js

When you have typed ``` or are already inside a fenced
block of code, pressing enter should not submit the
chat message, but add a newline instead. Other chat
apps such as Mattermost have the same behaviour. Pressing
Ctrl+Enter inside code blocks still submits the message
as usual.

FEATURE: Newline when press Enter inside code block

---

assets/javascripts/discourse/components/chat-composer.js

I keep seeing this JS error, and I don't want to see it anymoreeee

FIX: Prevent JS error from emoji autocomplete

---

assets/javascripts/discourse/services/chat.js

Other chat apps tend to move to "away" status after 5 minutes. This gives
us slightly better parity. We still need to build support for automatic
away status into presence channel which is missing at the moment.

FEATURE: user presence up to 5 minutes from 60 seconds

---

assets/javascripts/discourse/initializers/chat-setup.js

isolate chat is a desktop only feature, does not make sense on mobile.

FEATURE: don't isolate chat on mobile

---

assets/javascripts/discourse/components/channel-list.js
assets/javascripts/discourse/services/chat.js
lib/chat_channel_fetcher.rb

I keep seeing this issue where someone personal chats me, and I don't see it until I do a page refresh. I thought the issue was with personal chat channel creation, but then I realized it's the limit on the DM channel query.
Currently the client is only tracking the latest 10 channels... so if Robin is 11th most recently updated and sends me a new message, I will not get it.
This PR does 2 things:
* Serializer _all_ your DM channels, and hides channels 11-on. This allows tracking of all channels.
* Keeps unread DM channels at the top of the list. First sort by unread messages count, then sort by `updated_at` on the channel

FIX: Track all DM channels in frontend even if hidden

---

assets/javascripts/discourse/templates/components/channel-list.hbs
config/locales/client.en.yml

Online count is a bit rough at the moment due to online definition.
It tends to go up and down, no way to easily drill in and see who and just
is becoming somewhat distracting and confusting.
You can pick the people you would like to see online status of by adding to
personal chat.
This has better parity with other chat application that do not surface
the total number.

UX: remove online count from channels

---

assets/javascripts/discourse/components/chat-composer.js

The entire .tc-live-pane element can now be used to
drop files into for uploads. An .uppy-is-drag-over class
is added to the element on drag over and removed on
drag leave, and we can also hook into those events
if we want to do anything fancy with CSS or JS. This
commit just expands the area so it's no longer just
the text box.

FEATURE: Expanded drop target for files

---

assets/javascripts/discourse/components/channel-list.js

With chat isolated, the sidebar is much smaller and there is room to show the latest 20 personal that channels instead of 10.

FEATURE: Show last 20 personal channels when chat is isolated

---

assets/javascripts/discourse/controllers/chat-index.js
assets/javascripts/discourse/routes/chat-index.js
assets/javascripts/discourse/routes/chat.js
assets/javascripts/discourse/templates/chat-index.hbs

This overloads the chat index route a bit to handle 2 cases - 
1. for when the user has not joined any channels
2. channel selector index
The reason for this: We need a channel selector index for mobile chat. Can't use`chat.channel` route, as we need a channel ID and title for that route, and we really just want this channel index to live at `/chat`. This solution seems fine for now, but I could see us moving the blank page to `/chat/get-started` if it needs more complex logic or we add more rich features.

FEATURE?: Mobile chat header icon opens channel list

---

assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/templates/components/tc-message.hbs

Fixes the issue in screenshot. The problem was we adjust the grid layout when selecting messages and the new message indicator was inside the grid. Moving it out, and adjusting the scrollToMessage function to subtract 20 pixels gets us to the same place.

FIX: Layout issue with selecting messages

---

assets/javascripts/discourse/components/sidebar-channels.js
assets/javascripts/discourse/services/chat.js

This is kind of impossible to test since it relies on the sidebar plugin being installed to be render...

FIX: Show channel list in sidebar on browse page

---

assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/components/topic-chat-float.js
assets/javascripts/discourse/services/chat.js

This does a few things
1. Clicking mentions when the channel was already open would call `fetchChannels` without passing in the `chatChannelId`, causing the chat live pane to not recover. Simply add the `chatChannelId` into the calls, and that issue is fixed.
2. Refactor the open channel at message logic to be more clear to follow (for me at least). The `chat float` and `chat live pane` (a child of the float) were listening to the same appEvent and it was really messy. This make the `chat float` pick up appEvents from the chat service, and then pass that information to the `chat live pane`.

FIX: Clicking mentions doesn't leave weird state

---

app/jobs/regular/notify_users_watching_chat.rb
app/models/chat_channel.rb
config/locales/server.en.yml

Group personal chat messages don't have a title right now so instead of 
> New chat message in 134
it's
> New chat message in a personal chat channel

FIX: Desktop notification for group new message

---

assets/javascripts/discourse/initializers/chat-notification-sounds.js

Doing this in case volume in the service worker is somehow louder

DEV: force volume on sound notifications to 0.8

---

assets/javascripts/discourse/helpers/format-chat-date.js
assets/javascripts/discourse/templates/components/chat-message-render.hbs
assets/javascripts/discourse/templates/components/tc-message.hbs
assets/stylesheets/common/common.scss
config/locales/client.en.yml

Relative times are hard to understand and follow in the fast lane, this swaps us to absolute times.
Also makes the time a link to the chat message which is handy for copying links to chat easily.

FEATURE: swap time from relative to absolute

---

assets/javascripts/discourse/templates/components/chat-message-render.hbs
assets/javascripts/discourse/templates/components/tc-message.hbs
assets/stylesheets/common/common.scss
assets/stylesheets/desktop/desktop.scss
assets/stylesheets/mobile/mobile.scss

Mostly message sizing, to prevent them from expanding beyond parent element bounds.
Also: circular (i.e. not oval) presence indicators. 🟢 
Chance of regressing something: pretty high.
But I tried it out in full-chat mode, floating, and mobile. Short messages, long, replies, images.

UX: Prevent message overflow; circular indicators

---

assets/javascripts/discourse/templates/components/chat-live-pane.hbs
assets/stylesheets/common/common.scss

The wrapper used to cover the whole width and capture the click events.

UX: Make area beside scroll-to-bottom clickable

---

assets/javascripts/discourse/components/chat-composer.js
assets/javascripts/discourse/components/full-page-chat.js
assets/javascripts/discourse/routes/chat-channel.js
config/settings.yml
test/javascripts/components/chat-composer-placeholder-test.js

This solves the problem when the channel is changed but the chatChannel value isn't modified due to the loading slider plugin.
Related: https://github.com/discourse/discourse-chat/pull/384 and https://github.com/discourse/discourse-chat/pull/391

FIX: Use discourseComputed value to get updated chatChannel

---

assets/javascripts/discourse/services/chat.js
assets/stylesheets/mobile/mobile.scss

Chat channels with long names have end up with two awkward rows of placeholder. This shortens it to just one
from
to
.

UI: Single-line chat placeholder

---

assets/stylesheets/common/common.scss
assets/stylesheets/mobile/mobile.scss

This PR makes adjustments to the chat-channel dividers and chat-channels-container to keep the spacing consistent with that of the list spacing in the teams sidebar.

UX: Small margin adjustments

---

config/locales/client.en.yml
config/locales/server.en.yml

Those strings _appear_ to be unused and create busywork during translation.

DEV: Remove unused strings from locale files

---

assets/stylesheets/common/common.scss

I do not believe we need specific emoji targeted margins here as they should receive the same spacing as the text tag they are located in.

UX: Remove emoji specific margins

---

app/controllers/chat_controller.rb
app/controllers/direct_messages_controller.rb
app/models/user_chat_channel_membership.rb
assets/javascripts/discourse/components/chat-channel-row.js
assets/javascripts/discourse/templates/components/chat-channel-row.hbs
assets/stylesheets/common/common.scss
config/locales/client.en.yml
lib/direct_message_channel_creator.rb
spec/components/chat_message_creator_spec.rb
spec/components/chat_message_updater_spec.rb
spec/lib/direct_message_channel_creator_spec.rb
spec/requests/chat_channel_controller_spec.rb
spec/requests/chat_controller_spec.rb

FEATURE: allows to unfollow direct message channel

---

assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/lib/collapse-lazy-yt.js
assets/stylesheets/common/common.scss
test/javascripts/acceptance/chat-live-pane-collapse-test.js

Introduce slack-esque folding for youtube onebox. /t/57501
(I actually spent some time looking at core's `lazyYT` to see if I could introduce a "collapsible" setting, but it had proved to be more difficult than just doing just this because of how it's padding the bottom manually.)
Here it is expanded:
Here it is collapsed:

FEATURE: Collapse youtube previews in chat

---

assets/stylesheets/common/common.scss
assets/stylesheets/desktop/desktop.scss

The pseudo-element trick wasn't working correctly because `after` element had a bit different size.

UX: Fix composer sizing

---

lib/chat_channel_fetcher.rb

The current state was doing a `user_custom_fields` query for each direct message channel user.

FIX: avoids N+1 query when fetching chat channels

---

assets/javascripts/discourse/components/chat-composer.js

FIX: Correctly handle `skip` result

---

db/post_migrate/20220104051326_change_chat_channels_timestamp_columns_to_timestamp_type.rb

In the migration added in https://github.com/discourse-org/discourse-topic-chat/commit/ba49568c2307e7abe1097312402be48102b28709
we added the created_at and updated_at columns after the
chat_channels table already existed. The way we did this was
not quite right; we used `Time.now` as the `default` for the
column, but Rails appears to take that to mean "use the now time
from the same date + time as the migration". Therefore any time
these columns were set to default, the date + time was always
`2021-08-24 23:48:01.169413`.
This commit fixes the issue by removing the default value for
the columns and changing the columns from `datetime` to `timestamp`,
which lets Rails wield its wizardry with the timestamps, and the
defaults are now correct for new channels.

FIX: Chat channel timestamps columns defaults were static

---

app/models/chat_channel.rb
app/models/chat_mention.rb
app/models/chat_message.rb
app/models/chat_message_post_connection.rb
app/models/chat_message_reaction.rb
app/models/chat_message_revision.rb
app/models/chat_upload.rb
app/models/chat_webhook_event.rb
app/models/direct_message_channel.rb
app/models/direct_message_user.rb
app/models/incoming_chat_webhook.rb
app/models/user_chat_channel_membership.rb

We should be doing this for plugins that have more than
one table I think...at least periodically, if not every
commit having it enforced like Discourse Core.

DEV: Add model annotations

---

assets/javascripts/discourse/components/tc-message-collapser.js

Firefox:
```
new DOMParser().parseFromString("<img>test</p>", "text/xml").firstChild
// XML Parsing Error: mismatched tag. Expected: </img>.
```
Chrome:
```
new DOMParser().parseFromString("<img>test</p>", "text/xml").firstChild
// <img><parsererror xmlns="http://www.w3.org/1999/xhtml" style="display: block; white-space: pre; border: 2px solid #c77; padding: 0 1em 0 1em; margin: 1em; background-color: #fdd; color: black"><h3>This page contains the following errors:</h3><div style="font-family:monospace;font-size:12px">error on line 1 at column 14: Opening and ending tag mismatch: img line 1 and p
</div><h3>Below is a rendering of the page up to the first error.</h3></parsererror></img>
```
Using `document.createElement("template");` will allow us to not fail on unexpected HTML which is …

FIX: DOMParser is very picky especially on firefox

---

assets/javascripts/discourse/templates/components/tc-message-collapser.hbs
assets/stylesheets/common/common.scss

UI: align vertically tc-message-collapsible

---

assets/javascripts/discourse/components/chat-live-pane.js

Before this fix we could enter the previous condition:
```javascript
if (this.chatChannel.id !== channelId) {
return;
}
```
And would never reach the point where we set to false the loading property.

FIX: ensures loading state is removed

---

assets/stylesheets/common/common.scss
assets/stylesheets/desktop/desktop.scss

This PR adjusts the look slightly for chat on full page with a non sidebar theme. It also applies consistent hover styling to the exit chat button.

UX: Full-page & exit button changes

---

assets/javascripts/discourse/components/tc-message.js
assets/javascripts/discourse/components/tc-text.js
assets/javascripts/discourse/templates/components/tc-message.hbs
assets/javascripts/discourse/templates/components/tc-text.hbs

Also to set up collapsing for images. `tc-message` is also growing so this feels like it's a useful complexity reduction in that file.
I may have a look at extracting reactions (`chat-message-reaction-list`) too to make `tc-message` less overwhelming. On first look it does look quite trivial to extract but there are a lot of minor details which need to be tested to prevent regressions.

DEV: Extract tc-text so that tc-message isn't too large

---

assets/javascripts/discourse/components/chat-live-pane.js

This is not the root issue, we should investigate more on why in some cases, we are processing a request to fetch a list of messages we don't care about anymore.
This commit will ensure that if it ever happens, we try to force transition to the channel the chat-live-pane is currently in, instead of showing a blank page.

FIX: reconciliate state of live-pane

---

assets/stylesheets/common/common.scss

Right now public channels are tiny and it looks bad. II hate having 2 sets of paddings here, but IDK else to do. I don't really want a set height (what if font-size changes)

FIX: Uniform sidebar channel row heights

---

assets/javascripts/discourse/components/chat-composer.js

It's impossible to clear uploads from drafts without changing the composer text. It's wildly annoying.
The problem is that we weren't triggering the callback that should be triggered when uploads or composer value is changed. Call the callback and it works!

FIX: Save new draft when upload is removed

---

assets/javascripts/discourse/components/chat-live-pane.js
test/javascripts/acceptance/chat-test.js
test/javascripts/chat-fixtures.js

We can leave the reply_to information going to the server and simple not render the in_reply_to on the client.

UX: Remove reply-to line if message is directly above

---

assets/javascripts/discourse/components/tc-message.js

On new instances of browsers where there were no favorite emojis,
do not crash

FIX: don't crash on missing favs

---

assets/stylesheets/common/common.scss

FIX: Stretchy avatars on iOS < 15.1

---

assets/javascripts/discourse/components/tc-message.js

In certain builds it appears that favorites can be {} somehow in production
This ensures the object we get responds to slice and thus is an array

FIX: ensure we also check for array in favorites

---

assets/javascripts/discourse/components/chat-composer.js

For some reason the fix in c89b05fcbf15f4de6fd9ea84d268f91d00108ec1
stopped working, maybe a core or ember update? Either way, return;
instead of return false; makes it work (when you press Shift+Enter
we just do return; as well)

FIX: Enter not working inside backticks

---

assets/javascripts/discourse/components/topic-chat-float.js

`const a = { expanded: false, expanded: true }`
`a.expanded` would be true so I'm keeping the subsequent declaration.

DEV: Remove duplicate declaration

---

assets/stylesheets/common/common.scss
assets/stylesheets/common/tc-message.scss

This fixes an issue in mobile where the image is bigger than the width of the screen. This was caused due to a missing style which was there before but got lost in translation.

FIX: Max-width an image

---

lib/chat_channel_fetcher.rb

Before this change, each public chat channel would trigger a `%{CHATABLE_TYPE}_custom_fields` query and cause a N+1

PERFORMANCE: preloads category and topic custom fields

---

app/models/direct_message_channel.rb

Before this commit each call to `chat_channel_title_for_user` would trigger an N+1:
```
plugins/discourse-chat/app/models/direct_message_channel.rb:12:in `chat_channel_title_for_user'
plugins/discourse-chat/app/models/chat_channel.rb:79:in `title'
plugins/discourse-chat/app/serializers/chat_channel_serializer.rb:30:in `title'
lib/freedom_patches/ams_include_without_root.rb:57:in `include!'
app/controllers/application_controller.rb:486:in `serialize_data'
app/controllers/application_controller.rb:495:in `render_serialized'
plugins/discourse-chat/app/controllers/chat_channels_controller.rb:6:in `index'
app/controllers/application_controller.rb:387:in `block in with_resolved_locale'
app/controllers/application_controller.rb:387:in `with_resolved_locale' …
```

PERF: prevents N+1 on direct message channel title

---

assets/javascripts/discourse/components/chat-channel-leave-btn.js
assets/javascripts/discourse/components/chat-channel-row.js
assets/javascripts/discourse/services/chat.js
assets/javascripts/discourse/templates/components/chat-channel-leave-btn.hbs
assets/javascripts/discourse/templates/components/chat-channel-row.hbs
assets/stylesheets/common/common.scss
config/locales/client.en.yml
test/javascripts/acceptance/chat-test.js
test/javascripts/components/chat-channel-leave-btn-test.js

- allows to quickly leave all channels and not only direct message channels
- makes channel-row tag less
- adds an instant animation when unfollowing a channel to make UI more responsive
- introduces `chat-channel-leave-btn` to encapsulate all this btn logic

REFACTOR: channel-row

---

assets/stylesheets/common/common.scss

The clear button was added to public channels, and it made the height too large. Now we get to simplify the css!

FIX: Channel row height since btn was added

---

assets/javascripts/discourse/initializers/chat-notification-sounds.js

/t/56762
Debounces the playing of audio notifications.
We also have to think about what we want to do when audio playing fails because the user has not interacted with the app due to [an autoplay policy browsers have](https://developer.chrome.com/blog/autoplay/#audiovideo-elements).
I don't have tests for this because I don't think it's possible to unit test this without sufficiently mocking the plugin API and we seem to be against mocking.

FIX: Prevent audio from playing on top of each other CAUSING IT TO BE LOUD

---

assets/javascripts/discourse/initializers/chat-notification-sounds.js

We have a nice `discourseDebounce` method which we should use.

DEV: Use debounce instead of manual timeout

---

assets/stylesheets/common/tc-message.scss

Less is more + better text contrast + tighter spacing + align left margin
Before / After

UX: Tweak message-separator styling

---

assets/javascripts/discourse/components/chat-live-pane.js

Wrong variable was being used.

FIX: "All loaded" message was shown too early

---

assets/javascripts/discourse/components/chat-channel-title.js
assets/javascripts/discourse/components/full-page-chat.js
assets/javascripts/discourse/templates/components/full-page-chat.hbs
assets/stylesheets/mobile/mobile.scss

Previously when there was no `chat.index` route, we needed the channel selector to be rendered for mobile, and the back btn hid the chat live pane and showed the channel selector. Now we can simply navigate back to the chat index route which is the channel selector :)
Also a little JS bug in channel-title.

REFACTOR: Mobile back btn takes you to channel index

---

assets/stylesheets/common/common.scss
assets/stylesheets/common/tc-message.scss

These changes should be no-op with the default themes, but fix some inconsistencies when used with custom ones.

UX: Fix compatibility with custom themes

---

assets/javascripts/discourse/components/chat-live-pane.js

A follow-up to #466. Turns out the bug I was hunting was caused by `allPastMessagesLoaded` being persisted between channel changes, which meant that once you saw an "end" of one channel you couldn't scroll-to-load in any channels.

FIX: Loading past messages

---

assets/stylesheets/common/common.scss
assets/stylesheets/mobile/mobile.scss
config/locales/client.en.yml
test/javascripts/components/chat-composer-placeholder-test.js

Related: https://github.com/discourse/discourse-chat/pull/394
The previous commit only made the ellipsis show on mobile. 
This one does it on desktop too for the mini-chat popup.
One thing to note is that when the placeholder is clicked, the
ellipsis actually goes away. This is also evident on 
https://developer.mozilla.org/en-US/docs/Web/CSS/:placeholder-shown

UI: Single line placeholder text

---

assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/components/tc-message.js
assets/stylesheets/common/common.scss
assets/stylesheets/common/tc-message.scss
test/javascripts/acceptance/chat-test.js

Since most of us don't know what the `tc-` prefix stands for, we are favouring the `chat-` prefix as a replacement. 
This PR is part 1 of the rename, since `tc-message` is to be renamed to `chat-message`, we have to replace the existing `chat-message` usages first.

DEV: Rename chat-message to prepare for tc-message rename

---

assets/javascripts/discourse/components/tc-message.js
assets/javascripts/discourse/templates/components/tc-message.hbs
assets/stylesheets/common/tc-message.scss

Part 2 of https://github.com/discourse/discourse-chat/pull/483
Within tc-message, the intent for classnames is
```
chat-message-container
chat-message (currently tc-message)
chat-message-content (currently tc-message-container, changed in this commit)
...
```

DEV: Rename tc-message's inner classes

---

assets/stylesheets/common/common.scss

Previously we were relying on the lack of whitespace between `<span>` elements. 14633d88 tidied up the HTML, and added newlines between the spans.
This commit uses `display:inline-flex` to make remove the space between the spans, which should be much less fragile.
Before (broken):
After (fixed):

UX: Remove space between dots in ellipsis

---

assets/javascripts/discourse/components/chat-user-avatar.js
assets/javascripts/discourse/templates/components/chat-channel-title.hbs
assets/javascripts/discourse/templates/components/chat-composer-message-details.hbs
assets/javascripts/discourse/templates/components/chat-emoji-avatar.hbs
assets/javascripts/discourse/templates/components/chat-message.hbs
assets/javascripts/discourse/templates/components/chat-user-avatar.hbs
assets/stylesheets/common/chat-message.scss
assets/stylesheets/common/common.scss
assets/stylesheets/desktop/desktop.scss
test/javascripts/acceptance/chat-test.js
test/javascripts/components/chat-channel-title-test.js
test/javascripts/components/chat-emoji-avatar-test.js
test/javascripts/components/chat-user-avatar-test.js

- chat-user-avatar, with tests (previously tc-avatar)
- chat-emoji-avatar, with test
- chat-user-presence-flair, tested in isolation (previously tc-user-presence-flair)
- fixes an issue where html for tc-user-presence-flair was also present for each avatar even if not online
- displays presence indicator for reply messages
- removes a lot duplicated css

REFACTOR: tc-avatar

---

assets/javascripts/discourse/components/chat-message-collapser.js
assets/javascripts/discourse/components/collapser.js
assets/javascripts/discourse/templates/components/chat-message-collapser.hbs
assets/javascripts/discourse/templates/components/chat-message-text.hbs
assets/javascripts/discourse/templates/components/collapser.hbs
assets/stylesheets/common/common.scss
test/javascripts/acceptance/chat-live-pane-collapse-test.js
test/javascripts/components/chat-message-collapser-test.js
test/javascripts/components/chat-message-text-test.js
test/javascripts/components/collapser-test.js

(the "feature" is that collapsing now includes external image URLs)
Previously, the assumption was that text would only be above the link,
and that there would only be one link in a message.
This change makes sure that links in between lines of text would be
collapsible, and that multiple links would be collapsible.
Acceptance tests have moved to component tests. Css styles extraction
into another file will be in a following PR.
Youtube:
Animated Image:
External linked image:

FEATURE: Collapses youtube, external gifs and images, and uploads properly

---

assets/javascripts/discourse/components/chat-message-collapser.js
test/javascripts/components/chat-message-collapser-test.js
test/javascripts/components/chat-message-text-test.js

This was happening and we don't want that to happen.

FIX: Don't collapse all oneboxes

---

assets/javascripts/discourse/components/chat-message-collapser.js
test/javascripts/components/chat-message-collapser-test.js

From https://github.com/discourse/discourse-chat/pull/441, the image filenames were supposed to be small but regressed in the recent PR https://github.com/discourse/discourse-chat/pull/504

FIX: Make file names small like before

---

assets/stylesheets/common/common.scss

Before this change it would be possible to have last channel unreachable as the container would not scroll.

FIX: correctly computes channels max height in float panel

---

assets/javascripts/discourse/templates/chat-browse.hbs
config/locales/client.en.yml
test/javascripts/acceptance/chat-browse-test.js
test/javascripts/acceptance/chat-test.js

/t/58540 and also incorporating /t/41110:
And also extract channel browsing tests into their own file

FEATURE: Show empty state when a user has no joinable channels

---

assets/javascripts/discourse/connectors/after-topic-status/topic-title-chat-icon.hbs
assets/javascripts/discourse/initializers/chat-topic-changes.js
assets/javascripts/discourse/widgets/topic-title-chat-link.js
test/javascripts/widgets/topic-title-chat-link-test.js

Not everything is tested as I tried to position the check as soon as I could but in any case the widget behaviour is fully tested and will be hidden if necessary. So worst case would be we add to the DOM a widget we could have avoided but it will be hidden.

FIX: ensures chat icon is not shown for closed topics

---

assets/javascripts/discourse/components/full-page-chat.js

This will need more refactoring in the future, but it seems needs for now, most likely because of the previous line `chat.Set("fullScreenChatOpen", true)` which probably impacts other elements.
This commit is meant as a partial revert of https://github.com/discourse/discourse-chat/commit/19a57e043a1bac9016852d89f74c55559604e04f

FIX: moves calculateHeight after render

---

assets/stylesheets/common/chat-message-collapser.scss
assets/stylesheets/common/chat-message.scss

This was tested also with twitter image embeds minimally. Maybe I'd get this right for reals. This was done with `object-fit: contain`. `width` needs to be `unset` because of the way our onebox engines are setting certain images.
One thing we may consider is a site setting for max-height. It's currently hardcoded to 150px.
Note that this fix cannot apply to youtube and we would have to change core because of the way lazyYT is dynamically calculating positions for the buttons and such.

FIX: No more large images, except youtube

---

assets/javascripts/discourse/components/chat-live-pane.js

Using this api https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API solves the issue of switching tabs and messages not being marked as read, because `document.hasFocus` is still false.

FIX: Use Page Visibility API for determining whether to read

---

assets/javascripts/discourse/components/chat-live-pane.js

It now tries to find the first parent scrollable element from a selected line.
It works nicely in my tests:

FIX: attempts to make scrolling github more resilient

---

assets/javascripts/discourse/components/chat-composer.js

Before this change the textarea was only resized on initial insert of the element or typing, which would mean that typing multiple lines in one channel would increase height of composer, and switching to another channel would keep this height.
Note: this behavior was only visible with the https://meta.discourse.org/t/experiment-on-meta-horizontal-loading-slider/177939 theme component

FIX: ensures textarea is resized upon entering a new channel

---

assets/stylesheets/sidebar-extensions.scss

This PR adjusts the padding of sidebar headers as well as the size and spacing of the header icons to make room for the chat icon being inserted into the header.

UX: Adjust padding + icon spacing in sidebar

---

assets/javascripts/discourse/templates/components/collapser.hbs
assets/stylesheets/common/chat-message-collapser.scss
assets/stylesheets/common/chat-message.scss
test/javascripts/acceptance/chat-live-pane-collapse-test.js
test/javascripts/components/chat-message-collapser-test.js
test/javascripts/components/collapser-test.js

The lightboxing function is applied once when [messages are loaded](https://github.com/discourse/discourse-chat/blob/3eabe03afa73418565d7f336f207ca3b2702ed07/assets/javascripts/discourse/components/chat-live-pane.js#L477). Since collapsing an image removed it from the document entirely, the lightboxing feature wasn't working after a user collapses and expands the image. 
To prevent this we could either A: reapply the lightboxing function every time after expand, or B: just skip removing the image when it's collapsed and just hide it. I chose B.

FIX: Show lightbox after collapse and expand

---

app/models/chat_message.rb
spec/models/chat_message_spec.rb

In e0a4a48d3cba6457a593dd43e3d7f14577c6f3d0 we limited chat to a
few features of markdown, but we missed some commonly used ones.
This commit adds the following back in:
* `[spoiler]spoiler tags[/spoiler]` from discourse-spoiler-alert
* markdown lists
* autolink for links like `<https://somelink.com>` to avoid inline
oneboxing those links
* emoji shortcuts (:P -> :stuck_out_tongue:) and inline emoji for
one emoji making up the whole chat message
The test for spoilers will not run unless you have
discourse-spoiler-alert installed and enabled.

FIX: Add missing markdown features

---

assets/javascripts/discourse/templates/components/chat-composer.hbs
assets/stylesheets/common/common.scss
assets/stylesheets/desktop/desktop.scss
assets/stylesheets/mobile/mobile.scss

This PR changes placement of the uploads button, and changes the mobile icon used to "send" messages once typed. It also makes a minor adjustment to full page chat left padding.
**Widget**
**Full screen**
**Mobile no text**
**Mobile with text**

UX: Chat composer changes, full page spacing adjustments

---

assets/stylesheets/sidebar-extensions.scss

This PR adds a bottom padding to the links in the sidebar in order to maintain vertical spacing.

UX: Small padding fix in sidebar

---

app/controllers/chat_controller.rb
app/jobs/scheduled/delete_old_chat_messages.rb
app/models/chat_channel.rb
app/models/chat_message.rb
assets/javascripts/discourse/components/chat-retention-reminder.js
assets/javascripts/discourse/templates/components/chat-live-pane.hbs
assets/javascripts/discourse/templates/components/chat-retention-reminder.hbs
assets/stylesheets/common/chat-retention-reminder.scss
assets/stylesheets/common/common.scss
config/locales/client.en.yml
config/locales/server.en.yml
config/settings.yml
db/migrate/20220119170535_add_chat_retention_fields_to_user_options.rb
plugin.rb
spec/jobs/delete_old_chat_messages_spec.rb
spec/requests/chat_controller_spec.rb
test/javascripts/components/chat-retention-reminder-test.js

Note: The serializer only serializes if the user HAS NOT cleared the reminder before. This will cut down on the current_user payload as most users who can chat will clear it.
The reminder also comes back if the site settings change, so that users stay up-to-date on how frequently old messages are removed. 
Site settings
Public channel channel (only staff will see this)
Personal chat channel (Everyone will see this)

FEATURE: Chat message auto-deletion with site settings

---

assets/stylesheets/sidebar-extensions.scss

This PR fixes an issue where the user-menu is placed a couple pixels shy of where it should be, which causes a border-line to show between the active icon and its menu. This is happening because in the chat plugin, we slightly decrease the size of these icons in order to make room for the chat icon.

UX: Use more specific positioning

---

assets/stylesheets/common/chat-retention-reminder.scss

This PR styles the retention message closer to core's styling.

UX: styling similar to core

---

assets/stylesheets/sidebar-extensions.scss

This PR changes the padding and margin for links in the sidebar to prevent the hover effect from extending to the edge of the sidebar.

UX: Padding changes in sidebar

---

test/javascripts/acceptance/chat-test.js

This causes the services to be initialized before the app has started. This means that the inject-discourse-objects pre-initializer has not run, and so the service will be initialized without any of the standard injections (e.g. currentUser, siteSettings, etc.)
This commit updates the hooks to define getters which will lookup the services 'just in time'.

DEV: Do not lookup services in test beforeEach hook

---

test/javascripts/acceptance/chat-test.js

`settled()` is the recommended way to pause a test for some update to take place. It waits for all pending runloop operations (e.g. next, later, schedule), and various other things. Manually using `assert.async()` and `next()` without any `await` means that qunit may start cleanup of the test container before the test has truly finished, leading to errors.
(Most of this commit is indentation changes)

DEV: Update tests to use `settled()` instead of `assert.async()`

---

assets/stylesheets/common/chat-channel-selector-modal.scss

FIX: Unread indicator styling in channel selector

---

app/jobs/regular/process_chat_message.rb
spec/jobs/process_chat_message_spec.rb

Do not error when message is deleted before job execution

FIX:  ProcessChatMessage when message deleted

---

assets/javascripts/discourse/components/chat-channel-selector-modal-inner.js
assets/javascripts/discourse/templates/components/chat-channel-selector-modal-inner.hbs

`{{input onChange=}}` has a built on delay for something like 500ms after the user stops typing.
Hooking into `keyup` for the `input` element causes the filter to trigger instantly and it makes this modal much better.

UX: Instantly filter chat channels in quick select modal

---

plugin.rb

Preload after reload, what a concept! 😛
I believe this fixes the issue I was having in dev env, where after a server reload the app would complain that some custom fields were not preloaded. This was happening because another plugin was preloading them after a reload, which enables the "warn on non-preloaded" logic, and those cfs from chat were missing.

FIX: Preload custom fields after server reload

---

assets/stylesheets/desktop/desktop.scss

Previously the chat was full viewport width, up to 1366px, at which point it would snap back to 1200px.
Now it simply stops growing at 1200px, so there's not weird jump.

UX: Fix the full-page-chat width

---

assets/javascripts/discourse/components/chat-channel-row.js
assets/javascripts/discourse/components/topic-chat-float.js
assets/javascripts/discourse/routes/chat-channel.js
assets/javascripts/discourse/services/chat.js

This is a major improvement on how `activeChannel` is calc'd everywhere, by being manually set at the correct spots. The largest benefit of this is that channel-rows can hook into the chat services' `activeChannel` and highlight even when the float is open :)

UX: Sidebar rows 'active' when float is open

---

app/controllers/chat_channels_controller.rb
app/models/chat_channel.rb
app/serializers/chat_channel_search_serializer.rb
assets/javascripts/discourse/components/chat-channel-selection-row.js
assets/javascripts/discourse/components/chat-channel-selector-modal-inner.js
assets/javascripts/discourse/components/chat-composer.js
assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/controllers/chat-channel.js
assets/javascripts/discourse/routes/chat-channel.js
assets/javascripts/discourse/services/chat.js
assets/javascripts/discourse/templates/chat-channel.hbs
assets/javascripts/discourse/templates/components/chat-channel-selection-row.hbs
assets/javascripts/discourse/templates/components/chat-channel-selector-modal-inner.hbs
assets/javascripts/discourse/templates/components/chat-live-pane.hbs
assets/javascripts/discourse/templates/components/full-page-chat.hbs
assets/stylesheets/common/chat-channel-selector-modal.scss
assets/stylesheets/common/chat-retention-reminder.scss
assets/stylesheets/common/common.scss
config/locales/client.en.yml
lib/chat_channel_fetcher.rb
plugin.rb
spec/requests/chat_channel_controller_spec.rb
test/javascripts/acceptance/chat-keyboard-shortcuts-test.js
test/javascripts/acceptance/chat-test.js

This PR implements server-side filtering of results in the quick channel selection modal. The purpose of this, is that you can now start new DMs with user's who you haven't chatted with yet.
The search endpoint/response handling is quite complex. Some records are users, some are chat channels, so I created a new frontend component `chat-channel-selection-row` to handle these cases.
Other thing that is changed: Calculate `previewing` in chat-live-pane so that we can open previewed channels in the float. Add join channel btw to the float for previewed channels.

FEATURE: Server-side filter and new DM creation from ctrl+k

---

assets/javascripts/discourse/templates/components/chat-message-text.hbs
assets/javascripts/discourse/templates/components/chat-message.hbs
assets/stylesheets/common/chat-message.scss
config/locales/client.en.yml
test/javascripts/components/chat-message-text-test.js

Makes edit subtler and consistent with the edit indicator elsewhere in Discourse.

UX: Make edited indicator subtler

---

assets/javascripts/discourse/services/chat.js

This was missed in the 034cd64c67b1adfe055282b0ed472cbc4eef80aa
change, Site.markdown_additional_options needs to be used instead
of the old site serializer additions from the plugin.

FIX: Use Site.markdown_additional_options

---

lib/chat_notifier.rb

Job arguments go via JSON, and so DateTime objects will appear as strings in the Job's `#execute` method. The latest version of Sidekiq has started warning about this to reduce developer confusion.

DEV: Use string timestamps when enqueuing jobs

---

assets/javascripts/discourse/initializers/chat-setup.js
assets/javascripts/discourse/routes/chat-channel-by-name.js
assets/javascripts/discourse/services/chat.js
assets/javascripts/lib/discourse-markdown/discourse-chat-transcript.js
assets/stylesheets/common/chat-transcript.scss
config/locales/client.en.yml
spec/requests/chat_channel_controller_spec.rb
test/javascripts/acceptance/chat-transcript-test.js

The multiQuote attribute for [chat] makes the channel name show
above the username + datetime. If the channel name is provided
and the multiQuote attribute is not present or false, then the
channel name is put to the right of the datetime of the chat message.
This commit also links to the chat channel by name and the corresponding
ember route.
```
[chat quote="martin;155;2022-01-25T05:40:39Z" channel="Staff" multiQuote="true"]
a chat message for multi quote
that goes over several
messages
[/chat]
[chat quote="lowell_jacobi;4;2022-01-25T05:41:39Z" channel="Arts & Media"]
wow this is a whole new quote from a different channel
[/chat]
[chat quote="hunter;4;2022-01-25T05:41:39Z"]
this is someone else responding in some channel we have no idea about
[/chat]
```
Also in this commit is the …

FEATURE: Add multiquote and chained attrs for chat-transcript

---

assets/javascripts/discourse/controllers/preferences-chat.js
assets/javascripts/discourse/initializers/chat-user-options.js
assets/javascripts/discourse/templates/preferences/chat.hbs
test/javascripts/acceptance/chat-test.js

In 18f45fc4c695407dec3df29edd3f163e86e17aab we made a change to not
call addSaveableUserOptionField for the chat-specific user options
if !userCanChat. However, this prevents the user from changing their
chat preferences if they disable chat and press save. They are not able
to re-enable it or change any other settings, because the user options
are no longer added.

FIX: User could not re-enable chat after disabling it

---

assets/javascripts/discourse/templates/components/chat-message-collapser.hbs
assets/stylesheets/common/chat-message-collapser.scss

There's currently no sizing for youtube so everything's gigantic. This adds some fixed styles to youtube oneboxes with this assumption https://support.google.com/youtube/answer/6375112:
> The standard aspect ratio for YouTube on a computer is 16:9. If your video has a different aspect ratio, the player will automatically change to the ideal size to match your video and the viewer’s device. 
Images are currently set to a max height of 150px, so we're basing our 16:9 off that value. Here's an example of the player doing padding (based on link above)
> For some video and device aspects ratios like 9:16 vertical videos on computer browsers, YouTube may add more padding for optimal viewing.

FIX: Prevent youtube from being gigantic

---

assets/javascripts/discourse/components/chat-message-collapser.js
test/javascripts/components/chat-message-collapser-test.js

Unfortunately due to the way we are detecting which elements need collapsing, I've also caused messages with emoji to be collapsible.
Other occurrences may happen so we just have to exclude them from the predicate.

FIX: Don't collapse emoji images

---

assets/javascripts/discourse/components/chat-live-pane.js
lib/chat_channel_fetcher.rb

Currently the `_updateReadTimer` is set in `willIInsertElement`, and if something goes wrong and the timer is canceled, it will only be started again if the component is destroyed and re-created. Changing channels does not fix this.
This moves the initialization of `updateReadTimer` into a function called on channel change.

FIX: Prevent update read timer from stalling

---

assets/stylesheets/common/chat-transcript.scss
config/locales/client.en.yml

* Got rid of the border to match the regular quotes (btw. always use `var(--x)`, never `$x`; that's why it was broken on dark theme 😃)
* Changed the username color to match regular quotes
* Fixed timestamp alignment
* Increased the minimal font size (header)
* Removed the period after the channel link
* Made the margins of `<p>` elements smaller
Before / After

UX: Fix style inconsistencies in chat quoting

---

config/locales/client.en.yml
lib/post_notification_handler.rb
plugin.rb
spec/lib/post_notification_handler_spec.rb

When quoting chat messages, we want to notify all of the
users whose messages are quoted. This commit adds this
functionality, with a corresponding core PR to add the
notification type. The notification looks the same as the
regular quote notification for now.
Related https://github.com/discourse/discourse/pull/15968

FEATURE: Notify chat message users on quote

---

assets/javascripts/discourse/components/chat-composer.js
assets/javascripts/discourse/initializers/chat-keyboard-shortcuts.js
config/locales/client.en.yml

This commit adds the simplest "surround" formatting shortcuts
from the composer into the chat composer:
* ctrl+b - bold selection
* ctrl+i - italicize selection
* ctrl+e - inline code selection
These shortcuts only work when the chat composer is focused.
Requires https://github.com/discourse/discourse/pull/15950 to work.

FEATURE: Add simple composer shortcuts

---

assets/stylesheets/common/common.scss

This PR adjusts the padding to align the `x` button on personal chat channels.

UX: Small padding fix

---

assets/stylesheets/common/common.scss

This also smushes all alerts together (in rare cases when you have more than one), but that's a better way to display them on the full page chat page (especially in the standalone app context!)

UX: Remove the alert gap on more alert types

---

app/controllers/incoming_chat_webhooks_controller.rb
lib/chat_message_creator.rb
spec/requests/incoming_chat_webhooks_controller_spec.rb

When we create chat messages with ChatMessageCreator, there
is a chance the message will fail and return an error message.
This was working fine, however when we were creating the
ChatWebhookEvent record we were passing the `@chat_message` to
it, which meant that the chat message was always created regardless
of whether the chat message creator errored or not.
This commit fixes the issue by only making the ChatWebhookEvent once
the chat message has been validated. Any other validations must
occur before the chat message is saved, and any records created
linking to the message must be created after the message is saved.

FIX: Don't create errored chat message from webhook event

---

app/controllers/chat_controller.rb
lib/chat_message_reactor.rb
plugin.rb

This will make the reaction code easier to work with
and also will add a nicer place to add more validations
before creating/removing the reaction (such as in the
upcoming readonly chat channel work).
We already follow this pattern with ChatMessageCreator
and ChatMessageUpdater.

DEV: Move chat reaction code into lib class

---

assets/javascripts/discourse/components/chat-composer.js
assets/javascripts/discourse/templates/components/chat-composer.hbs

This PR expands the target area for dropping in uploads to discourse chat. *If* the chat widget, or chat full page is open, dropping anywhere on the screen will upload the file to the chat composer. 
Without this PR, dragging an upload onto the view would only upload if specifically within the confines of the chat area, triggering the browser to open the image.
https://user-images.githubusercontent.com/30537603/155375743-bca23832-9582-411e-865f-9ea067365f30.mp4
https://user-images.githubusercontent.com/30537603/155376197-00d2b012-d9f0-4fae-9116-567949798b01.mp4

UX: Expand target area for chat uploads

---

app/models/chat_message.rb
assets/javascripts/discourse/components/chat-live-pane.js
spec/models/chat_message_spec.rb
spec/requests/chat_controller_spec.rb
test/javascripts/acceptance/chat-test.js

This commit enables the "quotes" markdown feature for
chat messages, and also makes sure the quote always has
a link to the quoted post with the force_quote_link
param for PrettyText.
**This core PR must be merged first: https://github.com/discourse/discourse/pull/16034**

FEATURE: Allow using [quote] bbcode in chat messages

---

app/models/chat_message.rb
spec/models/chat_message_spec.rb

Previously, the reply excerpt would be empty. So using adding the file name would perhaps make it more useful to the the viewer what the message is in reply to.

FEATURE: Uses upload filename for reply to excerpt if message is empty

---

assets/javascripts/discourse/components/chat-live-pane.js

Currently we have to manually click in composer after we "edit" a message. This focuses your cursor there so you don't have to.

FIX: Focus in composer after 'edit message' button is clicked

---

assets/javascripts/discourse/components/chat-live-pane.js

Previously I had made deleted messages auto-expand if they were the scroll-to target. This was for reviewables, where we want staff to know which message is flagged (by expanding and highlighting the message). I didn't think about the case where the scroll-to target is any ol' message b/c pagination. 
Adding optional arg to `scrollToMessage` fixes this riight up (as well as fixing another thing that's been bothering me)

FIX: Don't expand deleted messages on scroll up

---

assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/services/chat.js
assets/javascripts/discourse/templates/components/chat-live-pane.hbs
assets/stylesheets/common/common.scss
assets/stylesheets/desktop/desktop.scss
assets/stylesheets/mobile/mobile.scss
test/javascripts/acceptance/chat-test.js

This PR makes adjustments for the new `div` that will be used to add more details to archived & closed channels. It also removes the `x` button, as it is possible to leave chat in the same way users can "leave" other pages in Discourse core, which is by clicking the "home" logo.
**Desktop**
**Mobile**

UX: Adjust styles, remove leave chat button

---

lib/chat_message_processor.rb

Even without a typo, it wasn't needed.

DEV: Remove a typo'd instance variable

---

assets/javascripts/discourse/components/dm-creator.js
test/javascripts/acceptance/chat-test.js

When we were creating a new DM channel in non-isolated chat
mode, we were not creating a ChatChannel instance to wrap
the returned channel in, meaning the canModifyMessages
function cannot be found and throws an error. This is not
a problem in isolated chat because the channel is loaded via
a route.

FIX: New DM erroring on create because of canModifyMessages

---

assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/components/chat-message.js
test/javascripts/acceptance/chat-test.js

Previously, chat messages subscribed to `appEvents` channels for reactions on `init`. This is a problem because newly created messages (by you the sender), do not have an `id` in `init`. The `id` is hydrated later when message_bus sends the `id` along with the `staged-id` to the sender's client.
This checks for an `id` in `init`. If one is present, continue with the logic as it were before. If there is no ID present, subscribe to a new `appEvents` channel for hydrating `ids`, with the callback of subscribing to the normal `appEvent` channels.
The logic might look a bit funky with more appEvents, but this avoids throwing an `observes` in `chat-message` for when `stagedId` changes.

FIX: Ability to react to previously staged message

---

assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/components/chat-to-topic-selector.js
assets/javascripts/discourse/controllers/move-chat-to-topic.js
assets/javascripts/discourse/templates/components/chat-to-topic-selector.hbs
assets/javascripts/discourse/templates/modal/move-chat-to-topic.hbs

The move chat messages to topic modal has the same inner
selection component as the "move posts to topic" modal from
core. This topic selection functionality will be needed for
the archive chat channel functionality.
This commit moves the inner elements into a new chat-to-topic-selector
component, which can be used from any modal component.
For reference it is this modal:

DEV: Make topic selection component reusable from move modal

---

assets/javascripts/discourse/components/chat-channel-selector-modal-inner.js
assets/javascripts/discourse/components/chat-composer.js
assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/components/chat-retention-reminder.js
assets/javascripts/discourse/components/dm-creator.js
assets/javascripts/discourse/controllers/create-channel-modal.js
assets/javascripts/discourse/models/chat-channel.js
assets/javascripts/discourse/routes/chat-browse.js
assets/javascripts/discourse/services/chat.js
assets/javascripts/discourse/templates/components/chat-channel-title.hbs
test/javascripts/components/chat-retention-reminder-test.js
test/javascripts/helpers/fabricators.js

We now create ChatChannel model instances in the chat
JS code, so we can add shorthand methods for checking
the chatable type instead of comparing directly to
a hardcoded string, and in the places where this does
not fit this commit changes the comparison to look
at the CHATABLE_TYPES const.
Also standardises in more places to use instances of
`ChatChannel` instead of `EmberObject`

DEV: Standardise chatable_type checks in JS

---

plugin.rb
spec/plugin_spec.rb

The core plugin API changed while it was still under development and the
plugin was not. These changes fix the issue and add tests to prevent
similar future bugs.

FIX: Preserve uploads with associated ChatUpload

---

assets/stylesheets/common/common.scss

FIX: Ensure online flair is shown correctly on replies

---

app/models/chat_message.rb
assets/javascripts/discourse/components/chat-live-pane.js
spec/models/chat_message_spec.rb

This commit allows the [chat] bbcode for quoting chat messages
introduced in 034cd64c67b1adfe055282b0ed472cbc4eef80aa to be
used within chat messages, so you can quote chat from within
chat.

FEATURE: Allow use of [chat] bbcode within chat messages

---

assets/javascripts/discourse/routes/chat.js

Before this fix, the scrolling state of the topic list for example would persist and would cause long channels list to be partially scrolled.

FIX: ensures body is not scrolled when inserting channel list

---

assets/javascripts/discourse/services/chat.js
config/locales/server.en.yml
config/settings.yml
lib/validators/chat_default_channel_validator.rb
plugin.rb
spec/validators/chat_default_channel_validator_spec.rb

This setting will make the user navigate to the selected
public channel when opening chat IF they have no unread
messages and no mentions that they need to see. If there is
no default channel set, then the first public channel will
be shown, otherwise the first DM channel will be shown.

FEATURE: Add chat_default_channel_id site setting

---

app/serializers/chat_view_serializer.rb
assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/components/chat-message.js
spec/lib/guardian_extensions_spec.rb
spec/requests/chat_controller_spec.rb

When a user can moderate a channel, we allow the API to
return deleted messages in the JSON payload, but we do
not show the messages in the UI with the "A message was
deleted" message and [view] button. This PR corrects this
by providing the can_moderate boolean in the chat view
meta payload, and using that to determine whether to
show the message alongside existing conditions.

FIX: Show deleted messages if can moderate

---

db/migrate/20210813141741_add_timestamps_to_chat_channels.rb
db/post_migrate/20220104051326_change_chat_channels_timestamp_columns_to_timestamp_type.rb

The way the fix from 31de9ae70a021e32fee92b343f392e524f32c9b5
was applied for sites that have never had chat enabled left
ActiveRecord in a weird state until the next deploy, where
there were errors raised saying "created_at can not be null".
Presumably this is because of "Rails Magic TM" that is fixed
on a subsequent deploy. This commit attempts to fix the original
migration even further, so we should not encounter this again
when turning on chat for sites in future.

DEV: Fix chat_channel timestamp migrations

---

assets/javascripts/discourse/components/chat-composer.js
test/javascripts/acceptance/chat-test.js

In 009f7321bf83699ce0997b04a35b68ab85757717 we changed the composer
key event to keyup instead of keydown. This does not work correctly
for the composer's case though, because we want to prevent the default
behaviour of Enter if we do not hit certain special cases, such as
when we want to a) send the message or b) save the edit to a message.
On keyup, these special events still worked, but they would insert
an additional \n in the message because the Enter key event already
happened.

FIX: Revert chat-composer keyUp to keyDown event

---

assets/javascripts/discourse/components/chat-channel-row.js
assets/javascripts/discourse/components/chat-channel-status.js
assets/javascripts/discourse/models/chat-channel.js
assets/javascripts/discourse/templates/components/chat-channel-row.hbs
assets/javascripts/discourse/templates/components/chat-channel-settings-row.hbs
assets/javascripts/discourse/templates/components/chat-channel-status.hbs
assets/stylesheets/common/common.scss
assets/stylesheets/desktop/desktop.scss
assets/stylesheets/mobile/mobile.scss
config/locales/client.en.yml
test/javascripts/acceptance/archive-channel-test.js
test/javascripts/acceptance/chat-test.js

This commit moves the setting button out of the chat sidebar
on hover and into the channel browse list, because it is not
an often used action. Also shortens the status message at the
top of the channel, and adds a status indicator for the channel
in the browse list.
**Old Way**
**New Way**

FIX: Move channel settings button to channel browse list

---

config/locales/server.en.yml

`chat_default_channel_id` locale key was nested under `system_messages` instead of `site_settings`.

FIX: locale nesting for chat_default_channel_id site setting

---

app/models/chat_message.rb
spec/models/chat_message_spec.rb

Also use Rails' truncate method to truncate the message down to 400 characters.

FIX: convert emojis to unicode in push notifications

---

assets/javascripts/discourse/services/chat.js

publicChannelWithMention is never set and as a result `!publicChannelWithMention` would always be true.

FIX: this would always evaluate to true

---

assets/javascripts/discourse/services/chat.js
assets/javascripts/discourse/templates/components/chat-live-pane.hbs
assets/stylesheets/common/common.scss
assets/stylesheets/mobile/mobile.scss
lib/chat_channel_archive_service.rb
spec/lib/chat_channel_archive_service_spec.rb

* Make all users leave the channel when it gets archived
* Reload the channel window when the message bus channel
status change comes through, but only for the active
channel and only when the change is to read only or archived

FIX: Archive channel refinements

---

assets/javascripts/discourse/initializers/chat-setup.js
assets/javascripts/lib/discourse-markdown/discourse-chat-transcript.js
config/locales/server.en.yml
config/settings.yml
lib/chat_channel_archive_service.rb
lib/chat_transcript_service.rb
lib/extensions/topic_view_serializer_extension.rb
lib/tasks/chat_message.rake
spec/lib/chat_channel_archive_service_spec.rb
spec/lib/chat_transcript_service_spec.rb
spec/plugin_spec.rb
test/javascripts/acceptance/chat-transcript-test.js

* When generating markdown for the archive, do not create links
to individual chat messages, because these will just show a
404 message when clicked.
* Add a site setting to determine what to change the status of
the archive destination topic to. Before it was always changed
to archived, new options are open, archived, closed. This only
affects new destination topics.
* Hide the chat icon next to the topic title if the related channel
is read_only or archived.
* Fix some issues in chat-setup initializer -- we were getting the chat
service twice, and also the chat quote datetime decorator would not
work for users without chat enabled. This is wrong because the post
decorations should always work.

FIX: Improvements to archiving tool

---

.gitignore
assets/javascripts/discourse/components/chat-composer.js
assets/javascripts/discourse/components/chat-message.js
assets/javascripts/discourse/services/chat-emoji-store.js
assets/javascripts/discourse/templates/components/chat-message.hbs
config/locales/server.en.yml
config/settings.yml
test/javascripts/unit/lib/chat-emoji-store-test.js

FEATURE: add dedicated emoji store for chat plugin
This commit adds a new setting to define default emoji reactions for chat messages. The setting defaults to 3 reactions.
This commit also adds a new emoji store for chat plugin so that the favorites (recently used) emojis in chat emoji-picker is independent of topics/posts.

FEATURE: new setting to define default emoji reactions

---

app/controllers/chat_controller.rb
lib/guardian_extensions.rb
spec/requests/chat_controller_spec.rb

In the guardian extension we added a can_rebake? method with
a chat message as an argument. This causes a 500 error in the
core /post/:id/rebake endpoint, because guardian.ensure_can_rebake!
and guardian.can_rebake? are now expecting a chat message argument.
This commit just changes the chat guardian extension to be
can_rebake_chat_message?

FIX: Guardian can_rebake? was breaking core post rebake endpoint

---

assets/javascripts/discourse/routes/admin-plugins-chat.js
assets/stylesheets/common/common.scss

A follow-up to #644. When creating or editing an incoming webhook, the channel selector doesn't work unless each `chat_channel` is a ChatChannel object.

FIX: Chat channel selector was broken for incoming webhooks.

---

assets/stylesheets/common/common.scss
assets/stylesheets/mobile/mobile.scss

This CSS class is used in a lot of places, so changing where the margin is applied has a lot of unintended side-effects.
Revert "UX: Re-apply channels margin on mobile. (#683)"
This reverts commit 2aeb5b84c065172db62969ac3c5ba945e7fdc7ff.

UX: Revert margin changes to .chat-channel-title

---

assets/javascripts/discourse/initializers/chat-setup.js
test/javascripts/acceptance/chat-transcript-test.js

#685 didn't do anything…
The issue was that the function passed to `decorateCookedElement()` kept the `currentUser` (or `container`, after the just merged PR) from the first time the initalizer was executed.

DEV: Actually fix the test flakyness

---

assets/javascripts/discourse/services/chat.js
lib/chat_channel_archive_service.rb
spec/lib/chat_channel_archive_service_spec.rb
test/javascripts/acceptance/chat-status-test.js

When the channel was archived some users could end
up with an unclearable unread indicator. This commit
fixes the issue but for now the user still needs to
reload for the channel to drop off the list.

FIX: Clear unread when channel archived

---

assets/javascripts/discourse/templates/components/chat-user-avatar.hbs
assets/stylesheets/common/common.scss
test/javascripts/components/chat-user-avatar-test.js

The logic for this change is to prevent confusion between presence and new message. New message being presented as a bubble is already a very strong concept across Discourse, this new pattern attempts to prevent the confusion.

UX: implements presence indicator as a circle instead of bubble

---

assets/javascripts/discourse/templates/components/chat-channel-row.hbs
assets/javascripts/discourse/templates/components/chat-channel-selection-row.hbs
assets/javascripts/discourse/templates/components/chat-channel-title.hbs
assets/stylesheets/common/common.scss

This way it's included in the grid of chat-channel-title and ensures we have enough space.

FIX: moves unread indicator to chat-channel-title

---

app/models/chat_message.rb
assets/javascripts/lib/discourse-markdown/discourse-chat-transcript.js
assets/stylesheets/common/chat-message.scss
assets/stylesheets/common/chat-transcript.scss
lib/chat_channel_archive_service.rb
lib/chat_transcript_service.rb
spec/lib/chat_channel_archive_service_spec.rb
spec/lib/chat_transcript_service_spec.rb
test/javascripts/acceptance/chat-transcript-test.js

This commit introduces a new reactions attribute to
the [chat] BBcode in the format `emoji:user1,user2;emoji2:user1`.
When included, we store this data in a data-reactions attr
on the wrapping chat transcript div, and also construct
reaction indicators at the bottom of each [chat] quoted
set of messages.
We have intentionally left off the following:
* Fidelity is only per-group of messages. For example, if there
are 3 messages from a single user grouped into one [chat]
block, and each individual message has a reaction, all 3
reactions are placed at the bottom of the set of messages.
* When hovering the reactions, we do not show which username
reacted to what, we should be easily able to do this in
V2 of this feature.
Regular quoting of chat messages will not include
reaction metadata, …

FEATURE: Include reactions in archive chat quotes

---

assets/javascripts/discourse/templates/components/chat-channel-archive-status.hbs
assets/stylesheets/common/common.scss
lib/chat_channel_archive_service.rb
spec/lib/chat_channel_archive_service_spec.rb

When creating channel archive topics and posts previously
we used the archiving user as the creator of new topics and
posts to store the archive content. This commit changes this
to use the Discourse System user, because it is an automated
action. Also includes a few minor CSS fixes for the archive
status title.

FIX: Use system user for archive topics and posts

---

assets/stylesheets/common/chat-message.scss
assets/stylesheets/common/common.scss

FIX: Use similar styles for chat-emoji-avatar as chat-user-avatar

---

assets/javascripts/discourse/components/chat-channel-title.js
assets/javascripts/discourse/templates/components/chat-channel-row.hbs
assets/javascripts/discourse/templates/components/chat-channel-selection-row.hbs
assets/javascripts/discourse/templates/components/chat-channel-title.hbs
test/javascripts/components/chat-channel-title-test.js

https://github.com/discourse/discourse-chat/commit/aed2d84add728edcb49b4719948292ef136fd02c made it appear on places where its interest is very limited due to the fact it becomes instantly read and as a result just flashes the dot.

FIX: displays unread-indicator only when needed

---

app/controllers/chat_channels_controller.rb
app/jobs/regular/chat_channel_delete.rb
assets/javascripts/discourse/components/chat-channel-archive-modal-inner.js
assets/javascripts/discourse/components/chat-channel-delete-modal-inner.js
assets/javascripts/discourse/components/chat-channel-settings-btn.js
assets/javascripts/discourse/controllers/chat-browse.js
assets/javascripts/discourse/controllers/chat-channel-delete-modal.js
assets/javascripts/discourse/services/chat-emoji-reaction-store.js
assets/javascripts/discourse/templates/components/chat-channel-delete-modal-inner.hbs
assets/javascripts/discourse/templates/modal/chat-channel-delete-modal.hbs
config/locales/client.en.yml
config/locales/server.en.yml
lib/guardian_extensions.rb
plugin.rb
spec/jobs/chat_channel_delete_spec.rb
spec/requests/chat_channel_controller_spec.rb
test/javascripts/acceptance/archive-channel-test.js
test/javascripts/acceptance/chat-status-test.js
test/javascripts/acceptance/chat-test.js
test/javascripts/acceptance/close-open-channel-test.js
test/javascripts/acceptance/delete-channel-test.js

This commit introduces the delete functionality for chat
channels. This will trash the chat channel and its messages,
and permanently delete all related records like chat uploads,
chat reactions, and so on.

FEATURE: Deleting chat channels

---

assets/javascripts/discourse/components/chat-live-pane.js

`ignoreStickyScrolling` is important when loading messages, but once they're loaded we set it back to `false`. In a previous commit this was accidentally set to `true` instead of `false` in `finally`

FIX: Incorrectly ignoring sticky scrolling after fetching messages

---

assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/components/chat-message.js
assets/javascripts/discourse/templates/components/chat-message.hbs
config/locales/client.en.yml
test/javascripts/components/chat-message-test.js

1. If a user no longer exists in the DB, do not completely error all of chat.
2. Make sure that we don't update `last_read_message_id` to a message that has already been read

FIX: Don't error when user no longer exists

---

assets/javascripts/discourse/components/chat-live-pane.js
test/javascripts/acceptance/chat-quoting-test.js

Safari among the other browsers is doing the correct thing, and
throwing the following error when the user is clicking the
Quote button in chat isolated mode:
> NotAllowedError: the request is not allowed by the user agent or the
platform in the current context, possibly because the user denied permission.
This is because the clipboard API is supposed to be used in a
short time period to respond to a user-initiated event. Luckily,
there is a way around this, which is to hand a promise off to
a ClipboardItem. This is done via a new clipboardCopyAsync function
created in core.
This commit uses the new function and rewrites other parts of the
chat quote code to work around its usage.
cf. https://github.com/discourse/discourse/pull/16232

FIX: Clipboard copy chat quotes breaks on Safari

---

.discourse-compatibility

The commit 6f88f8b41315d683783c116a2c56125aff6b7627 introduces
a new function from core which will not be available in
the current beta version of core.

DEV: Add .discourse-compatibility

---

assets/javascripts/discourse/components/full-page-chat.js
test/javascripts/acceptance/chat-test.js

The ? key is used to show the keyboard shortcuts in the
app, we want this to work rather than autofocusing the chat
composer.

FIX: Do not autofocus chat composer when ? pressed

---

assets/javascripts/discourse/components/chat-live-pane.js

I'm also concerned we have a _focusComposer and focusComposer functions with slightly different implementations, but can't think of a simple fix for now.

FIX: DOM operations should happen after render

---

assets/javascripts/discourse/templates/chat-browse.hbs

model has the form of : `{ categoryChannel, topicChannels }` also we already check before if channels are empty, so this is not needed.

DEV: this condition is never reached

---

db/post_migrate/20220321235638_drop_chat_message_post_connections_table.rb

Since 613ff279c3c396fb84ca2911efe68aeaaa739bc0 we
no longer need this table.

DEV: Drop chat_message_post_connections

---

assets/javascripts/discourse/components/chat-composer.js
assets/javascripts/discourse/initializers/chat-keyboard-shortcuts.js
config/locales/client.en.yml
test/javascripts/acceptance/chat-keyboard-shortcuts-test.js

This commit adds the ctrl+l shortcut to open the
insert link modal in the chat composer (ctrl+k
was already taken by channel switcher)
This shortcut only works if the chat composer is
focused.

FEATURE: Insert link with shortcut in composer

---

plugin.rb
spec/plugin_spec.rb
test/javascripts/acceptance/user-card-chat-test.js

In 7b21a51120888caae9902c67536aaf2d78dd6964 we added a UserCardSerializer
extension for can_chat_user, which is used to show a button to initiate
a chat from the user card. However this is causing errors for anon
users viewing other users when chat is enabled, since scope.user
is nil for anon users.
This commit fixes the issue and adds tests exercising the can_chat_user
extension for the UserCardSerializer

FIX: Error when anon viewing another user when chat is enabled

---

assets/javascripts/discourse/components/chat-composer.js

This will allow the composer in chat to handle HTML and other
rich text pasting, which has been broken due to recent core
changes.
The core PR https://github.com/discourse/discourse/pull/16262 must
be merged before this.
Note: I tried to add UI tests here but it seems to be extremely difficult
to consistently fire the `paste` event manually. We are able to in a few
core tests, but it does not seem to work at all for the chat composer --
I tried variations for a couple of hours and I don't think its worth persuing
any further.

FIX: Use chatEventPrefix to handle composer insert-text events

---

assets/javascripts/discourse/components/chat-composer.js

In  https://github.com/discourse/discourse/commit/1341baaebaf9932952cf3fd65448564473188525 in core
I added composerEventPrefix for composer app events,
but I only changed a few of them. Also using the
useUploadPlaceholders: false option to avoid any text
being inserted into the chat composer as result
of uploads, introduced in:
https://github.com/discourse/discourse/pull/16272

FIX: Fix missing app event bindings

---

assets/javascripts/discourse/templates/components/chat-message-actions-mobile.hbs
assets/stylesheets/mobile/chat-message.scss

- prevents selection from long press before expansion
- collapse menu on background touch instead of click, that will make a scroll gesture close the menu
- ensure tc-reply-display will not be selected if present when doing long press

FIX: minor tweaks

---

assets/javascripts/discourse/components/chat-composer.js

We are changing to the non-underscore version of
many TextareaTextManipulation methods in core, see
https://github.com/discourse/discourse/pull/16285

DEV: Fixing TextareaTextManipulation deprecations

---

assets/javascripts/discourse/components/chat-composer.js
assets/javascripts/discourse/components/chat-live-pane.js
test/javascripts/acceptance/chat-test.js

Previously the date button was added in `discourse-local-dates`, see https://github.com/discourse/discourse/pull/16342 which removes it from core. 
This PR also 
- fixes the date modal in chat, it previously was inserting `undefinedundefinedundefined` in the chat composer
- adds an acceptance test
- uses the new `applyLocalDates` wrapper from core

DEV: Add date button, use cleaner `applyLocalDates` import

---

config/locales/client.en.yml

Change to "Quote in Topic" for more clarity about
what this button does in chat.

FIX: Change copy for the quote button

---

app/controllers/direct_messages_controller.rb
assets/javascripts/discourse/services/chat.js
plugin.rb
spec/requests/direct_messages_controller_spec.rb
test/javascripts/acceptance/chat-browse-test.js
test/javascripts/acceptance/chat-test.js

It makes more sense to have usernames as a query string than a URL param and it avoids issues with format and dots.

FIX: makes direct_messages an index route

---

assets/javascripts/discourse/components/chat-composer-uploads.js
assets/javascripts/discourse/components/chat-composer.js
assets/javascripts/discourse/templates/components/chat-composer.hbs
test/javascripts/acceptance/chat-test.js

This commit fixes an issue where the "Uploading..." placeholder
markdown from the composer was inserted into the chat composer.
This was due to the insert-text app event using composerEventPrefix,
which was not removed when it should have been in the
f0e777d07800dda1a0265bd57768edc4c6d8291a commit.
Also fixes an issue where the drop target was the entire page
for uploads in the floated chat, rather than just the floated
chat drawer.

DEV: Fix composer upload event and drop target issues

---

assets/javascripts/discourse/components/chat-composer.js
test/javascripts/acceptance/chat-test.js

Before this fix, the specific event triggered for chat wouldn't get caught and the paste would be considered handled, resulting in nothing happening.

FIX: ensures html pasting works

---

assets/javascripts/discourse/services/chat.js

This commit https://github.com/discourse/discourse-chat/commit/b8c5f7397c15126baed4363d7e19264c25ae56e9 introduced the site setting for a default channel. The issue is that the setting is a string in the JS, rather than an int (so that it can be left blank), and we were not casting the value to an integer when comparing.

FIX: Default channel setting not working

---

assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/components/chat-selection-manager.js
assets/javascripts/discourse/templates/components/chat-live-pane.hbs
assets/javascripts/discourse/templates/components/chat-selection-manager.hbs
assets/stylesheets/common/chat-selection-manager.scss
assets/stylesheets/common/common.scss
plugin.rb

At the moment there is just a Quote button when selecting messages,
but we are adding another button here and potentially more
in future, it makes more sense to have the chat selection
management buttons to be in their own component, not clogging
up chat-live-pane.

DEV: Move chat selection buttons out of chat-live-pane

---

assets/javascripts/discourse/components/chat-message.js
assets/javascripts/discourse/components/chat-selection-manager.js
test/javascripts/acceptance/chat-quoting-test.js

In 6445af48bb74b6312f863b1001bdc46546b1e34b I moved some things
from chat-live-pane into a new chat-selection-manager component.
However I did not realise I made a breaking change when I used
the class syntax for the Component; in this syntax instead of
doing `router: service()` we need to do `@service router`. This
was not picked up by the mobile quoting test because it was commented/
skipped back in 8794f358389b366fbe25b5ff5eb90ad31528251f because
the mobile menu was added but we did not have a way to test the
touch support.
This commit fixes the router issue and also adds a way to test the
long press on mobile by triggering the long press on a message
immediately instead of 500ms later in testing mode. This must be triggered
immediately because there is no concept of "long press" …

FIX: Use @service router to fix chat quoting on mobile

---

lib/chat_channel_fetcher.rb
spec/lib/chat_channel_fetcher_spec.rb

Prior to this fix, if deleted message was the last message of a channel it would forever stay in unread state.
Note that this commit won't fix client side not updating unread state after without a refresh after last message has been deleted. But refresh or navigating to channel will now work where it wouldn't have before.
This commit also adds extensive specs for unread_counts.

FIX: correctly acknowledge for deletion in unread_counts

---

assets/stylesheets/common/chat-message-collapser.scss
assets/stylesheets/common/chat-message-images.scss
plugin.rb

We never really resized images within oneboxes, so here's an attempt:
Reddit:
Existing collapser + Twitter:
Keeps max width without overflowing:
Tested in chrome and ff

FIX: Resize images within oneboxes

---

assets/javascripts/discourse/components/chat-live-pane.js

Prior to this change answering to an unfollowed public channel would create an error. This commit makes the result of the first step similar to allow for proper code sharing.
This commit also explains more precisely the different possible cases of sendMessage to prepare for future refactoring.

FIX: following public channel doesn’t return channel

---

assets/stylesheets/common/chat-message-images.scss

This styling was leaking into regular discourse posts and breaking onebox widths. Followup to 811595b8

FIX: Scope chat image/onebox styling to `.chat-message`

---

assets/stylesheets/common/chat-message-images.scss

https://github.com/discourse/discourse-chat/pull/797 had caused github oneboxes to overflow when screens are not wide. 
Problem:
Onebox after the removal of `width: max-content`:
^ not overflowing

FIX: Fix overflowing github oneboxes

---

assets/javascripts/discourse/initializers/chat-setup.js

Prior to chis change widgets are not correctly rendered using the last value of `this.chat.isChatPage` for example.

FIX: ensures widget is re-rendering when router changes

---

assets/javascripts/discourse/components/chat-live-pane.js

This was causing Youtube embeds to be broken after a message has been sent on an already loaded feed.

FIX: decorates lazyYT only once

---

assets/javascripts/discourse/components/chat-message-text.js
assets/javascripts/discourse/templates/components/chat-message.hbs
test/javascripts/components/chat-message-test.js
test/javascripts/components/chat-message-text-test.js

Incorrectly removed and merged https://github.com/discourse/discourse-chat/commit/cfce9acbd1bdc8acc3632d12cd0d414fe0fd40f3 due to too much trust in tests and carelessness.

FIX: Ensure edits are shown, with tests

---

assets/javascripts/discourse/components/chat-message-text.js
assets/javascripts/discourse/templates/components/chat-message-text.hbs

As part of this fix was related to the use of get/`@computed` in a non native class, I have refactored the whole component:
- native class
- tagless

FIX: ensures collapsing is working on legacy

---

assets/javascripts/discourse/templates/components/chat-message-text.hbs
test/javascripts/components/chat-message-text-test.js

Prior to this change, editing a youtube link and replacing it with another link wouldn't display the `edited` text.

FIX: shows edited text if editing a collapsible into a collapsible

---

assets/javascripts/discourse/components/chat-message-collapser.js

I suspect the use of get + `@computed` was potentially causing issues here.

REFACTOR: makes chat-message-collapser a native class

---

assets/javascripts/discourse/components/chat-live-pane.js
config/locales/client.en.yml

As we are overriding defaults of `moment.js` calendar function, we have to provide our own translation.
A test would be very heavy to test this due to the lack of isolation currently in chat-live-pane. I'm reluctant to have a full acceptance test only for this. chat-message-separator is already well tested by itself.

FIX: ensures separator is correctly translated

---

app/controllers/chat_controller.rb
assets/javascripts/discourse/adapters/chat-message.js
assets/javascripts/discourse/components/chat-live-pane.js
spec/requests/chat_controller_spec.rb

Previously, seeing new messages in a channel was unnatural when there was a large number on unread messages because we displayed the newest ones first, meaning you'll have to scroll back to see the conversation from the last you
read.
This change improves our scrolling logic by loading new messages from where you left the last time you visited the channel. Also, it'll load a couple of older messages to avoid leaving the "New Messages" indicator hidden beside the
channel header. We had to refactor the messages endpoint to make the direction you're scrolling explicit, which let us create the concept of landing in the middle of the conversation, where you can generally scroll both ways.
**Before:**
**After:**

FIX: Don't hide the new messages indicator beside the channel header.

---

assets/javascripts/discourse/components/chat-selection-manager.js
assets/javascripts/discourse/templates/components/chat-selection-manager.hbs
test/javascripts/acceptance/chat-move-message-to-channel-test.js

In f898aa7ff51d457e231c9a4c7098626ee6fcdfe3 we introduced
move messages to another channel, where we had a server side
check to prevent moving messages from a DM channel, but we
did not hide the button in the UI for DM channels.

FIX: Do not show Move Messages button in DM channels

---

app/controllers/chat_controller.rb
assets/javascripts/discourse/adapters/chat-message.js
assets/javascripts/discourse/components/chat-live-pane.js
spec/requests/chat_controller_spec.rb

Reintroduces discourse/discourse-chat#818, which was reverted on discourse/discourse-chat#826.

FIX: Don't hide the new messages indicator beside the channel header

---

app/controllers/chat_controller.rb
assets/javascripts/discourse/adapters/chat-message.js
assets/javascripts/discourse/components/chat-live-pane.js
spec/requests/chat_controller_spec.rb

Reverts discourse/discourse-chat#827

Revert "FIX: Don't hide the new messages indicator beside the channel header"

---

app/models/chat_message.rb
db/post_migrate/20220504080457_drop_old_chat_message_post_id_action_code_columns.rb

Follow up to 5baf232a597d27da490c021d7fcf2c570bb5f0a8, drops `post_id` and `action_code` from `chat_messages`.

DEV: Drop old post_id and action_code columns from ChatMessage

---

app/models/chat_message.rb

These were dropped in 4d6009ab243be7e4897256bc543a9139bd6ace0f

DEV: Remove ignored columns for ChatMessage

---

assets/stylesheets/common/chat-message.scss
assets/stylesheets/common/common.scss

This improves copy'n'paste experience:
Before:
```
lorem ipsum
​​
another message
​​
lorem ipsum
cvx 8:31 pm
heh
​​
sup
```
After:
```
lorem ipsum
another message
cvx 8:31 pm
heh
sup
```
---
(checklist: should be fine in all cases :P)

UX: Make some UI elements unselectable

---

app/controllers/chat_controller.rb
app/serializers/chat_view_serializer.rb
assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/components/chat-selection-manager.js
assets/javascripts/discourse/templates/components/chat-live-pane.hbs
lib/guardian_extensions.rb
spec/lib/guardian_extensions_spec.rb
spec/requests/chat_controller_spec.rb
test/javascripts/acceptance/archive-channel-test.js
test/javascripts/acceptance/chat-flagging-test.js
test/javascripts/acceptance/chat-keyboard-shortcuts-test.js
test/javascripts/acceptance/chat-move-message-to-channel-test.js
test/javascripts/acceptance/chat-quoting-test.js
test/javascripts/acceptance/chat-status-test.js
test/javascripts/acceptance/chat-test.js
test/javascripts/acceptance/close-open-channel-test.js
test/javascripts/acceptance/delete-channel-test.js
test/javascripts/acceptance/user-card-chat-test.js
test/javascripts/chat-fixtures.js
test/javascripts/components/chat-message-test.js

This allows category group moderators to moderate chat
channels via the `guardian.can_moderate_chat?` extension.
Practically this now allows category moderators to do
the following on category channels:
* Move messages to another channel
* Delete/restore/and see deleted chat messages
It also fixes some inconsistency with `can_delete_self` and
`can_delete_others`, which we had guardian methods for
and meta/details hash to attach the result to, but we were
setting a hardcoded result in the JS code.
Doing this necessitated introducing a dynamic `generateChatView`
function for the chat fixtures, because what is in these meta properties
is dependent on the current user. Tests were updated to use this
new function instead of the static `chatView`.

DEV: Allow category group mods to moderate chat channels

---

assets/javascripts/discourse/components/chat-message-collapser.js
assets/javascripts/discourse/templates/components/chat-message-collapser.hbs

The main change here is the removal of cases in the template, to make way for https://github.com/discourse/discourse-chat/pull/845.
_____

DEV: Refactor collapser

---

assets/javascripts/discourse/components/chat-message-collapser.js
test/javascripts/components/chat-message-collapser-test.js

Allows galleries (google photos, imgur, flickr) to be resized and collapsed. Example gallery: https://imgur.com/gallery/yyVx5lJ
Fullscreen
Docked

FIX: Add gallery to collapser

---

app/jobs/regular/create_chat_mention_notifications.rb
app/services/chat_publisher.rb
lib/chat_notifier.rb
spec/components/chat_message_creator_spec.rb
spec/jobs/regular/create_chat_mention_notifications_spec.rb
spec/lib/chat_notifier_spec.rb

When we want to notify users of a chat message, the `ChatNotifier` is our only source of truth. This service selects and groups the users by mention types, expanding direct, group, and channel-wide mentions. It also filters
unreachable users we can't notify because they don't have chat access or are not participating if the channel is private.
It doesn't send notifications itself but generates a "map" and gives it to a scheduled job. This structure includes all the users to notify and the mention type metadata, which we need in order to ship different data in the
notifications.
The current implementation has a bug that includes group members who aren't participating in a private conversation if the message mentions a group. The scheduled job has an additional membership check, so it …

REFACTOR: ChatNotifier mention types expansion.

---

assets/javascripts/discourse/components/chat-message.js

In 5baf232a597d27da490c021d7fcf2c570bb5f0a8 I removed the
`message.action_code` argument to the `chatMessageClasses`
`discourseComputed` decorator, but I forgot to remove `actionCode`
from the function params and internal to the function.

FIX: chatMessageClasses has too many arguments

---

assets/javascripts/discourse/components/chat-message-reaction.js
assets/javascripts/discourse/templates/components/chat-message-reaction.hbs
assets/stylesheets/common/chat-message.scss
test/javascripts/components/chat-message-reaction-test.js

- tagLess
- native class
- better support for mobile with long press
- tests
- correctly shows emoji name in title
- uses a real button instead of role="button"

REFACTOR: chat-message-reaction

---

assets/javascripts/discourse/components/chat-composer.js

Repro steps by Joffrey
- open a chat channel
- type a message and add an upload
- wait few seconds (at least 2, to ensure the upload is stored)
- remove the upload (wait at least 2 seconds again)
- post the message (it should be posted without the upload)
- add an upload, it should appear under the composer AND the last posted message

FIX: composer uploads were appearing in the last message

---

app/models/chat_message.rb
spec/models/chat_message_spec.rb

This commit makes it so more complicated messages that
have cooked content that PrettyText.excerpt returns ""
for will just return "" for the excerpt rather than
showing raw markdown for the In Reply To message.
Also includes an improvement to just show the raw link
for the In Reply To message if it just consists of a
single URL, to get around excerpt issues with oneboxes.

FIX: Excerpts for complex messages

---

config/locales/server.en.yml
lib/chat_message_reactor.rb
spec/requests/chat_controller_spec.rb

We previously had the "You are not permitted to view the
requested resource" error pop up if someone tried to react
to a channel message without joining the channel. This
improves the message to be more helpful.

FIX: Nicer error message when reacting without membership

---

lib/message_mover.rb

Since https://github.com/discourse/discourse-chat/pull/854
there is no longer a delay when mentioning other users in
chat, this note is no longer relevant.

DEV: Remove redundant message mover note

---

app/controllers/chat_base_controller.rb
spec/requests/chat_channel_controller_spec.rb

We do not force all channels to have a name, so the route
to get a channel by name needs to work with the chatable
names as well (e.g. category.name and topic.fancy_title).
Note that this does not take into account DM channels where
getting them by name is kind of tricky.
The chat transcript service currently converts the channel
attribute (e.g. channel="Music Lounge") into a link using the
channel title in the /chat/chat_channels/:title format. A better
fit rather than the somewhat unreliable and tricky channel
title would be perhaps to use a channel ID instead...but that
does have its own issues for the transcript. We should discuss
internally.

FIX: Make get channel by name work with chatable name

---

app/models/direct_message_channel.rb
assets/javascripts/lib/discourse-markdown/discourse-chat-transcript.js
config/locales/client.en.yml
config/locales/server.en.yml
lib/chat_transcript_service.rb
spec/integration/post_chat_quote_spec.rb
spec/lib/chat_transcript_service_spec.rb
spec/models/chat_message_spec.rb
spec/models/direct_message_channel_spec.rb
spec/requests/chat_controller_spec.rb
test/javascripts/acceptance/chat-quoting-test.js
test/javascripts/acceptance/chat-transcript-test.js

We have run across various complications when trying to
link to a channel by channel title (see /t/66638 and
https://github.com/discourse/discourse-chat/pull/857 for
examples) so instead we are just going to add a channel
ID to the chat quotes instead for easier linking.
This commit also improves DM channel titles for chat quotes,
which were not taken into account in the original design,
but was later allowed in 1f10fc6c4cf5642d21419eff30dc986d0cd33a7c.

FIX: Add channel ID attribute to chat quotes

---

app/controllers/chat_controller.rb
spec/requests/chat_controller_spec.rb

The controller endpoint isn't checking if the user follows the channel and marking all mentions from it as read even if they are newer than the new last read message value.

FIX: Update user last read endpoint.

---

assets/javascripts/discourse/templates/components/chat-message-actions-desktop.hbs
assets/stylesheets/common/chat-message.scss

UI: slightly improve look of message actions on desktop

---

assets/javascripts/discourse/components/full-page-chat.js

Before this fix, opening full page chat with a composer opened and then closing the composer could leave the chat in a state where it was not using full height.

FIX: ensures composer transition is over to compute height

---

app/core_ext/plugin_instance.rb
app/models/chat_message.rb
plugin.rb
spec/integration/plugin_api_spec.rb

Usage in plugin.rb:
```ruby
if respond_to?(:discourse_chat)
discourse_chat&.enable_markdown_feature('discourse-video')
end
```

DEV: allows plugins to enable markdown features

---

app/controllers/chat_channels_controller.rb
lib/chat_channel_fetcher.rb
spec/lib/chat_channel_fetcher_spec.rb

This fixes the filter in the fetcher -- it was only searching
on chat channel name but that's not always there, we need to
filter on topic title and category name as well.
Also the public_channels_with_filter function was redundant,
it shared too much with secured_public_channels, so I just
moved the filter into there.

FIX: Fix filter in chat channel fetcher

---

assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/components/topic-chat-float.js
assets/javascripts/discourse/services/chat-window-store.js
assets/javascripts/discourse/services/chat.js
assets/javascripts/discourse/templates/components/chat-live-pane.hbs
assets/javascripts/discourse/widgets/chat-header-icon.js
config/locales/client.en.yml
test/javascripts/acceptance/chat-test.js
test/javascripts/unit/lib/chat-window-store-test.js

This feature, in addition to adding a button to get back to small chat
from being in the full-page chat, adds *memory* to the window size.
This means that if you prefer to open chat in full-size when using the
sidebar it will remember which preference you have set when opening
channels.
See: https://meta.discourse.org/t/221388

FEATURE: Add a button to switch back to small chat

---

lib/chat_mailer.rb
spec/components/chat_mailer_spec.rb
spec/jobs/scheduled/email_chat_notifications_spec.rb

This is currently throwing exceptions:
```
Job exception: undefined method `send_unread_mentions_summary' for DiscourseChat::ChatMailer:Class
/var/www/discourse/plugins/discourse-chat/app/jobs/scheduled/email_chat_notifications.rb:10:in `execute'
/var/www/discourse/app/jobs/base.rb:232:in `block (2 levels) in perform'
rails_multisite-4.0.1/lib/rails_multisite/connection_management.rb:284:in `with_connection'
rails_multisite-4.0.1/lib/rails_multisite/connection_management.rb:77:in `with_connection'
/var/www/discourse/app/jobs/base.rb:221:in `block in perform'
/var/www/discourse/app/jobs/base.rb:217:in `each'
/var/www/discourse/app/jobs/base.rb:217:in `perform'
/var/www/discourse/app/jobs/base.rb:279:in `perform'
mini_scheduler-0.13.0/lib/mini_scheduler/manager.rb:93:in `process_queue' …
```

FIX: send_unread_mentions_summary is a class method

---

assets/stylesheets/common/chat-onebox.scss
assets/stylesheets/common/chat-transcript.scss
assets/stylesheets/common/common.scss
config/locales/server.en.yml
lib/onebox/templates/discourse_chat.mustache
plugin.rb
spec/plugin_spec.rb

This commit implements support for regular and inline oneboxes for chat.
Oneboxes are registered as local onebox using the new plugin API and
are different for links to channels and links to direct messages from
chat.

FEATURE: Implement oneboxes for chat

---

assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/components/chat-message.js
assets/javascripts/discourse/initializers/chat-decorators.js
assets/javascripts/discourse/initializers/chat-plugin-decorators.js
assets/javascripts/discourse/templates/components/chat-live-pane.hbs
test/javascripts/acceptance/chat-test.js
test/javascripts/components/chat-message-test.js

Some transformations were being implemented in the `chat-live-pane` component, rather than using the `chat-message` decoration system. This means that they were often being applied multiple times to the same message.
This commit refactors all the decorators from chat-live-pane so that they use the standard API. This means they can take advantage of the perf improvements from 43ce6e0c65

PERF: Update all decorators to use decorateChatMessage api

---

lib/chat_channel_fetcher.rb
spec/lib/chat_channel_fetcher_spec.rb

Adds some more specs for ChatChannelFetcher, but there are
still some untested areas. Discovered that:
* We were checking for a muted channel when setting unread counts
for a DM channel, but this is unnecessary because DM channels
cannot be muted
* We were only checking if a user had a UserChatChannelMembership
record when getting relevant DM channels, but we weren't checking
DirectMessageUsers. Granted, it's unlikely that the former record
would exist without the latter, but it was a little security hole.
Also changed .detect to .find...it's the same method (corporate asked
me to tell the difference between the two pictures), but in our
case .find makes more sense because we are finding a record based
on a condition.

FIX: Add ChatChannelFetcher specs and fix issues

---

lib/onebox/templates/discourse_chat.mustache
plugin.rb
spec/plugin_spec.rb

The date was not showed correctly in Safari because it could not
recognize the date format.

FIX: Serialize dates using ISO8601

---

app/models/chat_channel.rb
app/models/chat_message.rb
app/models/user_chat_channel_membership.rb
lib/duplicate_message_validator.rb
plugin.rb
spec/lib/duplicate_message_validator_spec.rb
spec/models/chat_message_spec.rb

We introduced duplicate message blocking in d1597107d2c0d2dbd18ce96ef71f82dd3d004063
but put the blocker logic which is quite specific inside the
ChatMessage model, and without many specs. This commit refactors
the methods and logic into a DuplicateMessageValidator class
and adds additional specs.
The numbers used for the calculations are quite mysterious, but
hopefully the specs cover the common use cases. The default for the
setting is 0.5, min is 0, and the max is 1.0.
Also added a couple of missing model annotations.

DEV: Refactor duplicate message blocker into class

---

app/controllers/chat_controller.rb
lib/message_mover.rb
spec/lib/message_mover_spec.rb
spec/requests/chat_controller_spec.rb

In https://meta.discourse.org/t/moving-chat-messages-to-a-new-channel-jumbled-them-all-up/227301
we were having issues with moved messages between channels
being jumbled up. During investigations it was found that
the ChatController /messages route ordered messages by ID
but everything else, including the message mover, ordered by
created_at.
This commit makes things consistent by changing the /messages
route to also order by created_at, then ID. This should make it so the
order is always consistent in the UI and also for moved messages.

FIX: Message order consistency

---

app/models/chat_channel.rb
spec/models/chat_channel_spec.rb

Prior to this fix, destroying a chatable would cause a 500 on /admin/plugins/chat page as the chatable would be found and the serializer couldn't display its data.

FIX: prevents destroyed/deleted chatable to crash admin page

---

app/controllers/chat_controller.rb
app/jobs/scheduled/delete_old_chat_messages.rb
app/models/chat_message.rb
assets/javascripts/discourse/components/chat-live-pane.js
db/post_migrate/20220526135414_remove_corrupted_last_read_message_id.rb
db/post_migrate/20220531105951_drop_user_chat_channel_last_reads.rb
spec/jobs/delete_old_chat_messages_spec.rb
spec/migrations/remove_corrupted_last_read_message_id_spec.rb
spec/models/chat_message_spec.rb
spec/requests/chat_controller_spec.rb

Before this fix, two conditions (AFAIK) could lead to data corruption:
- delete_old_chat_message job which could delete messages (and not just trash). There was no dependent behavior on related models
- some endpoint would not check if a message related to an impacted channel, eg:
```
PUT /chat/42/read/666.json
```
Where 666 is a message id NOT belonging to the channel with id 42. Moreover, there was no check server side before updating the `last_read_message_id` of a membership that the provided `message_id` was belonging to this channel. As a result we would sometimes store an incorrect `last_read_message_id` which is then used for messages lookup and ends up loading the messages of another channel. We attempt to reduce the chances for the frontend to make an incorrect request.
Note …

FIX: better handling of non existing messages

---

assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/templates/components/chat-live-pane.hbs
test/javascripts/acceptance/chat-keyboard-shortcuts-test.js
test/javascripts/acceptance/chat-quoting-test.js
test/javascripts/acceptance/chat-test.js
test/javascripts/acceptance/mobile-chat-test.js
test/javascripts/acceptance/user-card-chat-test.js

hide collapse button on mobile and isolate

---

assets/javascripts/discourse/components/chat-replying-indicator.js
test/javascripts/components/chat-replying-indicator-test.js
test/javascripts/helpers/mock-presence-channel.js

Before this fix, being in another channel and switching to dm creator would not reset replying-indicator state and you would see incorrect data.

FIX: ensures we unsubscribe from /chat-reply in draft mode

---

assets/javascripts/discourse/components/full-page-chat.js

Ideally in the future I want to get rid of this calculateHeight logic, this is temporary fix for this case.

FIX: ensures chat has correct height on composer resizing

---

assets/javascripts/discourse/components/chat-live-pane.js

- correctly removes the listener
- slightly increase debounce as 50ms is so low that it will often call it two times during the deceleration of the scroll

REFACTOR: cleaner scroll handler

---

assets/javascripts/discourse/components/chat-live-pane.js

Not only does it give more context on tall screens, but also prevents a bug where you couldn't load previous messages as there wouldn't be any scroll event given the pane is not overflowing.

FIX: ensures we attempt to fill the current pane with messages

---

assets/javascripts/discourse/initializers/chat-keyboard-shortcuts.js
config/locales/client.en.yml

We may be changing these at some point, but still
best to have the help discoverable for these additional
shortcuts.

FIX: Add extra chat shortcut help text

---

lib/discourse_dev/public_channel.rb

When running dev:populate you might not have the admin user specified in
your config yaml file so we should ignore that instead of throwing an
error.

FIX: Dev populate breaks with missing admin user

---

assets/javascripts/discourse/components/chat-live-pane.js

Sometimes `uploads` are not present, which means that
the change from 0f4816c43e285d3e5e330742ff2a62e045db596b sometimes
errors (e.g. when inserting gifs via discourse-gifs). This
fixes the issue by providing default values. As in the
referenced commit, current coupling prevents this from being
easily testable.

FIX: Undefined uploads error when attempting to cloneJSON

---

assets/javascripts/discourse/initializers/chat-decorators.js
assets/javascripts/discourse/templates/components/chat-upload.hbs
spec/models/direct_message_channel_spec.rb

This commit fixes non-image chat uploads not working since
e9cb7a172dfd1f413626a4590e7f373447370086 when we removed
the `resolveAllShortUrls` calls in the chat message decorator. We can
just use the `upload.url` directly on the `href`.
`data-orig-X` attributes must remain, as they are used for quoting.

FIX: Make sure chat uploads have correct URL in template

---

app/jobs/scheduled/update_user_counts_for_chat_channels.rb
plugin.rb
spec/jobs/update_user_counts_for_chat_channels_spec.rb
spec/plugin_spec.rb

A onebox for a chat channel should only show users that are active, not
staged, and not suspended in the members list.
Maybe as a future feature we should boot users from the channel list that don't
belong to a certain group or that are no longer activated. Not really
sure, it's possible they should re-join the group if they are no longer
suspended.

FIX: Onebox should only show active users

---

app/views/user_notifications/chat_summary.html.erb

It looks better on mobile this way.

UX: Split each summary's message into its row.

---

assets/javascripts/discourse/components/chat-live-pane.js

So far it feels more annoying than helpful, before this fix the top message would be scrolled to about half of the pane, creating a big jump, now it won't move and you can just continue your scrolling.

FIX: prevents the jump when loading more

---

assets/stylesheets/common/chat-onebox.scss

UI: reduces spacing between avatars in channel onebox

---

test/javascripts/acceptance/chat-test.js
test/javascripts/unit/lib/chat-window-store-test.js

Reset chat window state seems to help in these tests. They are passing
locally now at least.

DEV: Fix flakey chat window tests

---

app/serializers/chat_channel_serializer.rb
lib/chat_channel_fetcher.rb
spec/serializer/chat_channel_serializer_spec.rb

We were getting N1 queries with the archive record for
a channel when listing all public channels. This is mitigated
by:
a) only trying to query for the archive record if the channel
status is archived and
b) including the channel archive record when querying all public
chat channels

FIX: N1 in chat channels controller index querying chat_channel_archives

---

assets/javascripts/lib/discourse-markdown/discourse-chat-transcript.js
spec/integration/post_chat_quote_spec.rb

A oneline change. Chat quotes render their inner content with the
chat markdown engine with a limited subset of rules, using a
html_raw markdown-it token. However when I first added this I
pushed the token to the state with the wrong level. I had this:
```javascript
// rendering chat message content with limited markdown rule subset
const token = state.push("html_raw", "", 0);
token.content = customMarkdownCookFn(content);
state.push("html_raw", "", -1);
```
But needed this:
```javascript
// rendering chat message content with limited markdown rule subset
const token = state.push("html_raw", "", 1);
token.content = customMarkdownCookFn(content);
state.push("html_raw", "", -1);
```
Spot the difference? (I simply changed the 0 to 1 on the first line).
This was causing the token "level" to …

FIX: Chat quote interfering with oneboxes

---

assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/components/chat-message.js
assets/javascripts/discourse/components/direct-message-creator.js
assets/javascripts/discourse/components/full-page-chat.js
assets/javascripts/discourse/components/topic-chat-float.js
assets/javascripts/discourse/services/chat.js
assets/javascripts/discourse/templates/components/full-page-chat.hbs
assets/javascripts/discourse/templates/components/topic-chat-float.hbs
config/locales/server.en.yml
lib/chat_message_reactor.rb
spec/lib/chat_message_reactor_spec.rb
spec/requests/chat_controller_spec.rb

With this change reacting to a preview channel or a draft channel, will create a membership, the reaction and then navigate to the actual channel.
To make this change easier/cleaner I also made two other changes:
- rely on `chat.activeChannel` instead of recreating  an intermediate variable in full-page-chat and topic-chat-float
- simplify the `switchChannel` code, I suspect it might cause few regressions, but those are not tested ATM and I will fix/tests them as they come up
It also creates extensive specs for ChatMessageReactor which had none.

DEV: creates membership when reacting

---

assets/stylesheets/common/chat-message.scss
assets/stylesheets/common/chat-transcript.scss

FIX: Codeblock sizing (message and transcript)

---

assets/javascripts/discourse/templates/components/chat-live-pane.hbs
assets/stylesheets/common/chat-retention-reminder.scss

FIX: Correctly place the retention reminder

---

lib/extensions/user_option_extension.rb

In commit https://github.com/discourse/discourse-chat/commit/9083e37e40010bd7c9ff0c2f279bbe2bbd5a18e7 the column has been dropped but not added to ignored columns, this is the cause of errors like this one after a migration:
```
ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column user_options.last_emailed_for_chat does not exist
LINE 1: ..._mention", "user_options"."chat_email_frequency", "user_opti...
^
)
(eval):105:in `exec_params'
app/controllers/application_controller.rb:477:in `handle_theme'
lib/middleware/omniauth_bypass_middleware.rb:71:in `call'
lib/content_security_policy/middleware.rb:12:in `call'
lib/middleware/anonymous_cache.rb:368:in `call'
config/initializers/008-rack-cors.rb:25:in `call'
config/initializers/100-silence_logger.rb:29:in `call' …
```

DEV: adds last_emailed_for_chat to ignored columns

---

assets/javascripts/discourse/components/chat-channel-unread-indicator.js
assets/javascripts/discourse/initializers/chat-setup.js
assets/javascripts/discourse/services/chat.js
test/javascripts/unit/services/chat-test.js

- introduces chat#refreshTrackingState
- makes each tracking state an EmberObject to make computation easier
- reset lastForcedRefreshAt when leaving tab

DEV: allows to refresh only notifications and not full page

---

app/controllers/chat_base_controller.rb
app/controllers/chat_channels_controller.rb
app/controllers/chat_controller.rb
assets/javascripts/discourse/services/chat.js
lib/chat_channel_fetcher.rb
plugin.rb
spec/lib/guardian_extensions_spec.rb
spec/requests/chat_controller_spec.rb

This commit primarily fixes a security issue where permissions were not
checked during message lookup.
In addition, a review of the ChatChannelsController and ChatController was
conducted to make sure there was not more holes. They have been
patched, along with the following changes made:
* Refactors ChatBaseController.set_channel_and_chatable_with_access_check to
use DiscourseChat::ChatChannelFetcher.find_with_access_check directly, and
folds in the different code from the base controller into the fetcher for
consistency.
* Changes the POST /chat/drafts endpoint to use a chat_channel_id parameter
instead of channel_id for consistency, and ensures channel access is correct
before creating the draft.
* Makes sure many endpoints missing the
set_channel_and_chatable_with_access_check now …

SECURITY: Ensure chat message lookup checks for channel access

---

lib/chat_message_bookmarkable.rb
spec/lib/chat_message_bookmarkable_spec.rb

Messages are trashed and not destroyed, as a result `dependent: :destroy` has no effect on bookmarks and we have to make sure we don't attempt to list these bookmarks.
Before this fix the following repro would cause a 500 when reaching for `/u/:username/bookmarks.json`:
- Open a DM with any user
- Send a message
- Bookmark the message
- Delete the message
```
NoMethodError at /u/tomtom/bookmarks.json
=========================================
undefined method `chat_channel' for nil:NilClass
plugins/discourse-chat/app/serializers/user_chat_message_bookmark_serializer.rb, line 11
----------------------------------------------------------------------------------------
6     def title
7       fancy_title
8     end
9
10     def fancy_title
>  11       @fancy_title ||= …
```

FIX: do not list bookmarks of trashed messages

---

assets/javascripts/discourse/services/chat.js

Also fixes a bug where the state was not an ember object. Note this is currently way too complicated to test this behavior given the very high complexity and coupling of this codepath.

FIX: ensures a new channel always starts with unread 1

---

assets/javascripts/discourse/templates/components/chat-message-actions-desktop.hbs
assets/stylesheets/common/chat-message.scss

This would also fix a bug in firefox window on large screen (or specific circumstances) where the dropdown would appear under the scrollbar and making it barely usable.

FIX: ensures msg actions stay in live-pane

---

assets/stylesheets/common/chat-message.scss

drawer:
https://user-images.githubusercontent.com/1555215/176351384-9051342d-a652-48cd-bc95-45e5fa8fade8.mov
full screen
https://user-images.githubusercontent.com/1555215/176351395-7f68dd33-3920-4f77-a9e9-7b199b46d922.mov

Show hovering when sidebar is on as well

---

app/controllers/direct_messages_controller.rb
app/services/chat_publisher.rb
assets/javascripts/discourse/components/chat-channel-selector-modal-inner.js
assets/javascripts/discourse/components/chat-draft-channel-screen.js
assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/services/chat.js
lib/direct_message_channel_creator.rb
lib/discourse_dev/direct_channel.rb
spec/components/chat_mailer_spec.rb
spec/components/chat_message_creator_spec.rb
spec/components/chat_message_updater_spec.rb
spec/jobs/regular/chat_notify_mentioned_spec.rb
spec/lib/chat_notifier_spec.rb
spec/lib/direct_message_channel_creator_spec.rb
spec/mailers/user_notifications_spec.rb
spec/requests/chat_channel_controller_spec.rb
spec/requests/direct_messages_controller_spec.rb

At some time in the past few months (possibly #758)
the ability for users to create a new DM channel with themselves
was broken. There was inconsistency around the
chat direct message controller sometimes accepting
an array of usernames and sometimes accepting
a comma separated string of usernames. They are
both needed - the former for POST and the latter
for GET. The test for POST in ruby did not pass the
usernames as an array so it was not catching the
error which was preventing the creation of the channel,
which was caused by a duplication of the current user
in the users array.
This commit also changes the `create!` method argument
for `DirectMessageChannelCreator` to have a
`target_user` argument, which will make it easier to
add mute/ignore checks involving the user creating
the …

FIX: Allow user to direct message themself again and fix DM inconsistencies

---

app/services/chat_publisher.rb
spec/lib/direct_message_channel_creator_spec.rb

Follow up to f1fb1d0b4843b6265a6f46d8b24c31930a69c015,
in this commit I accidentally changed as_json (which produces
a Hash) to to_json (which produces a JSON string) in the
ChatPublisher for the new DM channel. This makes the MessageBus
data unparseable, so in JS in the chat service it ends up creating
a public channel in the channel list with undefined data, leaving
a blank channel in the list with a blue unread indicator.
Before fix MessageBus data:
After fix MessageBus data:
UI error:

FIX: Use as_json instead of to_json for chat DM message bus

---

app/controllers/chat_channels_controller.rb
spec/requests/chat_channel_controller_spec.rb

Follow up to ca528966dfc4be9a920a8477813892e19a38d0a2, channel
creation was prevented because we still required the `type`
parameter in the controller but it was removed from create-channel.js . That
param is redundant anyway since the only type of channel we can
make now is a Category channel.
This commit fixes the issue and removes the type requirement.

FIX: Create channel modal error with type param required

---

assets/javascripts/discourse/components/chat-live-pane.js

Follow up to 9c800e0146182ce6a4a3353138d0ba7c8ccbe2a3
When starting a new DM channel with one or more users where
no channel exists we return a 404 from the server. However
we were still trying to fetch messages for that channel in
the chat-live-pane, leading to a GET like this:
http://localhost:4200/chat/undefined/messages.json?page_size=50
This commit fixes the issue by not doing any additional fetching
in chat-live-pane if the chat channel ID is not present.

FIX: Do not fetch messages for draft channel with no ID

---

assets/javascripts/discourse/components/topic-chat-float.js

This small difference ensures that the chat-live-pane component of the drawer is going to be destroyed and call `willDestroyElement`

FIX: marks drawer as not expanded when full screen

---

assets/stylesheets/common/common.scss
assets/stylesheets/desktop/desktop.scss
assets/stylesheets/desktop/sidebar-extensions.scss
assets/stylesheets/sidebar-extensions.scss
plugin.rb

Continue of https://github.com/discourse/discourse-chat/pull/998
Extract CSS to sidebar-extensions

FIX: move CSS to sidebar-extensions

---

assets/javascripts/discourse/components/topic-chat-float.js

Before this fix, the drawer would still be expanded when switching to full page, albeit hidden, making the live pane inside the drawer still existing and new messages would be appended to this instead of the live pane of the full page.

FIX: makes drawer not expanded on full page

---

assets/stylesheets/common/common.scss

Fixing the squashing of the indicator when a channel name is max length

UX: fix channel msg indicator

---

assets/stylesheets/common/common.scss

UX: Remove gap on sidebar with full page chat

---

lib/chat_message_processor.rb

This will allow core or other plugins to listen for the
`chat_message_processed` event.
This will be needed for this PR for the discourse-video plugin:
https://github.com/discourse/discourse-video/pull/34

DEV: Trigger an event on chat message processed

---

app/services/chat_publisher.rb
assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/components/chat-message.js
spec/services/chat_publisher_spec.rb

This method allows to send a "refresh" message which will trigger a re-decorate on the client side.
The js part of this PR is sadly too complicated to test in the current state of coupling.

DEV: adds ChatPublisher.publish_refresh!

---

assets/javascripts/discourse/components/topic-chat-float.js
assets/javascripts/discourse/templates/components/chat-live-pane.hbs
assets/javascripts/discourse/templates/components/topic-chat-float.hbs
assets/stylesheets/common/chat-drawer.scss
assets/stylesheets/common/common.scss
test/javascripts/acceptance/chat-test.js
test/javascripts/acceptance/user-card-chat-test.js

- Removes member count from header in chat, it is not adding value
- Remove "full screen" button from minimized chat
- When minimized any click will simply restore height drawer
- BEM-izes some more of the chat drawer CSS classes

UX: stop displaying member count, clean up minimized chat view

---

app/controllers/chat_channels_controller.rb
assets/javascripts/discourse/components/chat-channel-selector-modal-inner.js
spec/requests/chat_channel_controller_spec.rb

- race condition with this filter and debounce
- not correctly filtering usernames
- directly exclude current user in query
- user username_lower instead of LOWER()
- correctly checks for prioritize_username_in_ux and enable_names

FIX: various issues in selector modal

---

test/javascripts/components/on-visibility-action-test.js

`await settled()` is not able to wait for `IntersectionObserver` callbacks

DEV: Fix `on-visibility-action` test

---

assets/javascripts/discourse/components/chat-channel-preview-card.js
assets/javascripts/discourse/templates/components/chat-channel-preview-card.hbs
test/javascripts/components/chat-channel-preview-card-test.js

When we show the chat channel preview card if you
are not a member of the channel, we should not be
showing the Join button if the channel is anything
but open (e.g. closed/archived/etc)

FIX: For non-open channels do not show Join on preview card

---

test/javascripts/acceptance/chat-test.js

It previously worked (occasionally) just because of pretender handler leak. That issue will be fixed in core.

DEV: Fix "Create channel modal" test

---

.github/workflows/plugin-linting.yml

The linter currently spams this warning in CI (and locally):
> warning: Pattern matching is experimental, and the behavior may change in future versions of Ruby!
No need to see that every time, so suppressing warnings.

DEV: Suppress stree lint warnings with RUBYOPT="-W0"

---

app/jobs/regular/auto_join_channel_batch.rb
app/jobs/regular/auto_manage_channel_memberships.rb
app/jobs/scheduled/auto_join_users.rb
plugin.rb
spec/jobs/regular/auto_manage_channel_memberships_spec.rb
spec/jobs/scheduled/auto_join_users_spec.rb
spec/plugin_spec.rb
spec/requests/users_controller_spec.rb

Additionally, trigger an auto-join for a user the first time we set `last_seen_at` instead of on create to avoid adding users who never visited the site.

FIX: Add a scheduled job to auto-join users when their state changes.

---

app/jobs/regular/auto_manage_channel_memberships.rb
spec/jobs/regular/auto_manage_channel_memberships_spec.rb

Currently the `AutoManageChannelMemberships` job will add users to a channel following a set of rules. It won’t do anything if the channel doesn’t exist or if the chatable isn’t a category.
But if the chatable doesn’t exist anymore then the job will raise an exception.
This PR addresses this issue by simply checking if the chatable exists before trying to do anything.

FIX: Don’t add users when chatable isn’t present

---

assets/javascripts/discourse/initializers/chat-sidebar.js
assets/stylesheets/sidebar-extensions.scss
test/javascripts/acceptance/core-sidebar-test.js

Private messages section has to be reloaded more often than channels section because they are reordered based on activity (amount of unread messages or last message date when amount of unread messages is same).
https://user-images.githubusercontent.com/72780/181156596-1ff5bea4-322c-4d15-9a10-d8c062b4cd88.mov

FIX: reorder private messages in sidebar

---

app/controllers/chat_controller.rb
app/serializers/basic_user_with_status_serializer.rb
app/serializers/chat_message_serializer.rb
assets/javascripts/discourse/components/chat-message-info.js
assets/javascripts/discourse/models/chat-message.js
assets/javascripts/discourse/templates/components/chat-message-info.hbs
assets/stylesheets/common/chat-message-info.scss
plugin.rb
test/javascripts/components/chat-message-info-test.js

_Note that before merging this, https://github.com/discourse/discourse/pull/17497 and https://github.com/discourse/discourse/pull/17598 should be merged in Core._
This adds "live" status to the user avatar on chat messages. Note that we'll improve design a bit later:

FEATURE: show status next to avatar on chat messages

---

assets/stylesheets/common/chat-replying-indicator.scss

Fixes extra space showing below the reply indicator on iOS. The culprit is `safe-area-inset-bottom`, iOS mistakenly still adds a value there even when the keyboard is visible. Thankfully it doesn't look like we need to account for safe areas here, the input is still clear of the device's bottom on iOS.

FIX: Adjust reply indicator spacing on iOS

---

assets/javascripts/discourse/initializers/chat-sidebar.js
assets/javascripts/discourse/services/chat.js
test/javascripts/acceptance/core-sidebar-test.js

PMs section should be limited to 20 links.
Existing `truncateDirectMessageChannels` function is used.

FIX: sidebar direct messages are limited to 20

---

assets/javascripts/discourse/components/chat-draft-channel-screen.js

Before this fix, selecting a user which doesn’t have a DM yet, would result in the creation of a new channel using selected users as the list of users for the chatable. This would have the consequence of mutating each selected users in the dm creator screen and it would then be impossible to remove a user from the selected users array as the user given to `removeObject` would now be a different object than the one in the array.

FIX: prevents mutation of dm creator selected users

---

app/models/chat_message.rb
db/migrate/20220729032237_add_index_to_chat_message_created_at.rb

Follow up to ddab84061ccfa2003fa52e73b1c364a7014c47e4,
there could be a lot of messages in the chat message
table, so we want to make sure these stat queries are
using an index.

DEV: Add created_at index for ChatMessage

---

assets/stylesheets/common/common.scss
assets/stylesheets/mobile/mobile.scss

ok! I think I've got something for full-screen chat that will:
* adjust chat and sidebar height on desktop when the topic composer is open
* adjust chat and sidebar height on mobile and iPad when the virtual keyboard is open
The adjustments for desktop to accommodate the topic composer use `--composer-height` and otherwise adjusts similarly to mobile/ipad, so I think this should be less fragile than revamping the whole layout just for the topic composer (which is what I did in a previous attempt). 
Desktop - The composer still has a fixed position, but the height of the page adjusts to fit:
iPad: 
Mobile: 
ᕕ(⌐■_■)ᕗ ♪♬

UX: adjust to fit composer on desktop, fix iPad layout

---

assets/javascripts/discourse/initializers/chat-decorators.js
assets/javascripts/discourse/initializers/chat-plugin-decorators.js
assets/javascripts/discourse/initializers/chat-setup.js
assets/javascripts/discourse/initializers/chat-user-options.js
assets/javascripts/discourse/widgets/chat-invitation-notification-item.js
assets/javascripts/discourse/widgets/chat-mention-notification-item.js
test/javascripts/acceptance/chat-test.js
test/javascripts/unit/lib/chat-emoji-reaction-store-test.js
test/javascripts/unit/services/chat-guardian-test.js
test/javascripts/widgets/chat-invitation-notification-item-test.js
test/javascripts/widgets/chat-mention-notification-item-test.js

- rely on default notification item behavior
- provides a URL and uses data-auto-route
- adds tests
- renames chat-mention-notification-item file

FIX: ensures chat notifications have a URL

---

assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/templates/components/chat-live-pane.hbs
assets/stylesheets/common/common.scss
config/locales/client.en.yml
test/javascripts/acceptance/chat-live-pane-test.js

When we set up a chat channel, we subscribe to a message bus channel that notifies us about updates, one of them being new messages from other users. To show them in real-time, we add them immediately, but since we don't check if
all the latest ones are already loaded, we may create a gap where some messages will be missing until you refresh the tab.
We are changing how we handle new message updates and checking if it's possible to scroll into the future, and if it is, it means we haven't loaded all the latest messages yet, so we'll display a "jump to latest" button.
https://user-images.githubusercontent.com/5025816/179126445-ed56b275-0260-42db-9b8a-458a1d1ed07f.mov
Thanks to this bug, we also noticed that our last read update logic is problematic because it aggressively updates to the …

FIX: Don't corrupt users' last read IDs.

---

assets/javascripts/discourse/initializers/chat-sidebar.js

While adding the channel to the sidebar, the tracking state might not have been created yet and this would cause an error.

FIX: prevents crash when joining channel

---

.github/workflows/plugin-linting.yml

-W0 suppresses all warnings, _including_ the syntax-tree
ones, whereas we just want to suppress these experimental
feature warnings to stop noise:
> warning: Pattern matching is experimental, and the behavior may change in future versions of Ruby!
Followup to 2c7bdf674322f8dac7d6566b879802171eac27da

DEV: Fix RUBYOPT for syntax-tree linting

---

assets/javascripts/discourse/routes/chat-channel.js
assets/javascripts/discourse/widgets/chat-invitation-notification-item.js
assets/javascripts/discourse/widgets/chat-mention-notification-item.js
test/javascripts/acceptance/chat-channel-slug-test.js

This will make any invalid slug title be replaced after model is loaded, eg:
`/chat/channel/1/-` will be replaced by `/chat/channel/1/channel-1-title`

FIX: checks if notification has a title or lets router handle it

---

config/locales/server.en.yml
config/settings.yml
db/migrate/20220802014549_disable_chat_uploads_if_secure_media_enabled.rb
lib/secure_media_compatibility.rb
lib/validators/chat_allow_uploads_validator.rb
plugin.rb
spec/plugin_spec.rb
spec/validators/chat_allow_uploads_validator_spec.rb

To avoid unexpected behaviour, since we do not currently
support securing chat uploads via the `secure_media` setting
we are disabling chat uploads if `secure_media` is also enabled
via an initial migration. We also disable chat uploads if `secure_media`
is changed from disabled to enabled, and we prevent changing
`chat_allow_uploads` to true via a site setting validator if `secure_media`
is enabled.
This condition can be overridden with `DISCOURSE_ALLOW_UNSECURE_CHAT_UPLOADS`
at operator risk. This condition will be removed once secure media
rework to allow for chat uploads is completed later in the year.

FIX: Do not allow chat uploads if secure_media is enabled

---

assets/stylesheets/common/chat-channel-title.scss
assets/stylesheets/common/chat-drawer.scss

Removing some overflow to fix:
And adding a fix for too long usernames pushing the icons out
so it uses ellipsis

Ux avatar border chat

---

assets/stylesheets/common/common.scss

Fixes an issue where the content was too tall for iPads in the hub app, because of the added nav (`footer-nav.js`) above the header:
Before:
After:
This relies on a core commit to get `--footer-nav-height`, https://github.com/discourse/discourse/pull/17744

UX: adjust fullscreen height for the iPad iOS app

---

assets/javascripts/discourse/components/topic-chat-float.js
assets/javascripts/discourse/initializers/chat-keyboard-shortcuts.js
config/locales/client.en.yml
test/javascripts/acceptance/chat-keyboard-shortcuts-test.js

This PR adds the functionality to:
- open the chat drawer using the key <kbd>-</kbd>
- close the chat drawer while focused on the input using the key <kbd>esc</kbd>
It also adds the details to the shortcut menu:

FEATURE: Keyboard shortcut to toggle open/close of chat drawer

---

assets/javascripts/discourse/services/chat.js

This logic shouldn't be here, but in openChannel, this is causing various bugs and doing more work than necessary ATM, eg: when unfollowing a channel currently it will first go to index, pick ideal first channel and then it will open the channel you just unfollowed. Removing this logic will avoid all of this.

FIX: removes ideal first channel logic from unfollowChatChannel

---

assets/javascripts/discourse/components/chat-composer.js
test/javascripts/acceptance/chat-test.js

This is especially needed on android where our existing `focusTextarea` is happening way too far down the chain. This fix attempts to refocus the input as soon as possible. It's hard to test this exact behavior, but a check to ensure we get focus has been added.

FIX: enforces focus of composer after send

---

spec/lib/message_mover_spec.rb

This commit ensures destination_channel used in test is correctly updated. The failure is reproducible with this command: `LOAD_PLUGINS=1 bundle exec rspec --seed 2514 plugins/discourse-chat`

FIX: prevents test failure in message mover spec

---

spec/requests/api/chat_channel_memberships_spec.rb

Ensures test sets a username to prevent random results

FIX: memberships order are username dependent

---

assets/javascripts/discourse/components/chat-live-pane.js
test/javascripts/acceptance/chat-live-pane-test.js

When a user sends a message, we upsert it at the end and force a scroll to the future, assuming we have all the latest messages loaded. However, this is not
always the case, which causes the scroll to load old messages.
This PR handles this scenario by loading the latest, then scrolling to the newly created message.

FIX: Don't stage sent message if there are more to load.

---

assets/javascripts/discourse/initializers/chat-sidebar.js

Reverts discourse/discourse-chat#1144
This was generating the following exception: "Uncaught TypeError: Cannot read properties of undefined (reading 'lookup')" when trying to create a new "personal chat".

Revert "DEV: Fix `site:main` deprecation"

---

assets/javascripts/discourse/components/chat-live-pane.js
assets/stylesheets/common/common.scss

This is hard to test as it happens only on a live iOS device. The padding removal is to prevent a very minor scroll jump. We could bring it back later by adding this space on a different container.

FIX: fixes ios white screen without causing scroll jump

---

app/models/chat_channel.rb
app/queries/chat_channel_memberships_query.rb
plugin.rb
spec/models/chat_channel_spec.rb
spec/queries/chat_channel_memberships_query_spec.rb

When a staff member joins a channel, and it's not a member of one of the groups with access to it, it should still be able to join the presence
channel.

FIX: Staff can participate in private categories' chat presence channels.

---

test/javascripts/acceptance/chat-test.js
test/javascripts/acceptance/core-sidebar-test.js
test/javascripts/chat-fixtures.js
test/javascripts/components/chat-message-test.js
test/javascripts/helpers/fabricators.js
test/javascripts/unit/services/chat-test.js

Beside being correct (that is a non-null attribute) it fixes issues with tests on Firefox.

DEV: Add `last_message_sent_at` to channel fixtures

---

lib/chat_channel_fetcher.rb
spec/lib/chat_channel_fetcher_spec.rb

This has effects on the number of public channels we display in the sidebar, in the future we might want to separate this case from others.

UX: increases max count of fetched public channels from 20 to 50

---

assets/javascripts/discourse/components/topic-chat-float.js
test/javascripts/acceptance/chat-test.js

Before this fix the following case would left the drawer at an incorrect position:
- Open main composer
- Open chat drawer
- Close preview in main composer
(See chat drawer go left)
- Close main composer
(See chat drawer stay out of position)
This is due to the fact that closing the composer doesn’t reset its state and it still has a reduced width after toggling the preview.

UX: ensures drawer position is correct with small/closed topic composer

---

assets/javascripts/discourse/initializers/chat-sidebar.js
test/javascripts/acceptance/core-sidebar-test.js

This reverts commit 784f15aa84178b65f9ed1758d03768a04fc70317. (which was a revert of the original implementation)
The original didn't work because section objects had no owner. That is now fixed in https://github.com/discourse/discourse/pull/17827
Also adds a test

DEV: Use `@service` in chat sidebar section

---

app/models/chat_channel.rb
spec/models/chat_channel_spec.rb

`Category#secure_group_ids` returns nil for public categories.

FIX: Don't scope MB messages only to staff groups for public channels

---

assets/javascripts/discourse/components/dc-filter-input.js

Now that all of our singletons have been converted to true Ember Services, we can remove our custom discourse/component/glimmer superclass and use explicit injection where needed (not needed here)

DEV: Update dc-filter-input to use @glimmer/component

---

assets/javascripts/discourse/components/topic-chat-float.js
test/javascripts/acceptance/chat-test.js

It's nicer and avoids overlap with scrollbar

UX: always applies a 15px right margin to the drawer

---

assets/stylesheets/common/chat-message-images.scss

UX: makes oneboxes full width to prevent different width

---

assets/javascripts/discourse/components/chat-channel-row.js
test/javascripts/components/chat-channel-row-test.js

We were showing user status next to the direct message channels with multiple users:
This PR removes status from such channels.

FIX: Don't show user status on direct message channels with multiple users

---

assets/javascripts/discourse/components/chat-live-pane.js
test/javascripts/acceptance/chat-live-pane-test.js

Either clicking the jump arrow or sending a message when there are unloaded ones will fetch the latest page and scroll to the latest one. Calling `_markLastReadMessage()` in these scenarios will break the scrolling since it also tries to scroll to the last read message immediately after, which we can't guarantee it's on the loaded page.

FIX: Don't try to scroll to the last read message when fetching from latest.

---

assets/javascripts/discourse/components/chat-message.js
assets/javascripts/discourse/helpers/format-chat-date.js
lib/onebox/templates/discourse_chat.mustache
spec/plugin_spec.rb
test/javascripts/unit/helpers/format-chat-date-test.js

Note this commit will require a rebake on affected posts to work.
This commit also fixed format-chat-date and copy message link codepaths to generate a correct URL to a chat message.
In the future it could be improved to simply rely on `channel.slug` both in frontend/backend but using `-` is  good solution for now as it will get replaced at runtime.

FIX: correctly links to channel message

---

assets/javascripts/discourse/components/chat-live-pane.js

Regression added in #1133. Adding newer messages also causes a scroll-down,  firing another event, fetching messages again, and so on. Scroll to the first
new one to prevent this.

FIX: Don't fire multiple scroll events when scrolling to the future.

---

assets/javascripts/discourse/initializers/chat-keyboard-shortcuts.js
test/javascripts/acceptance/chat-keyboard-shortcuts-test.js

Prior to this fix navigating to a channel in full page and pressing <kbd>escape</kbd> would erase content of the live pane.

FIX: prevents esc shortcut to remove content when in full page

---

assets/javascripts/discourse/services/chat.js
assets/javascripts/discourse/services/full-page-chat.js
assets/javascripts/discourse/widgets/chat-header-icon.js

```
x.isPreferred = false;
x.isPreferred == true
```
…was a bit confusing, and the mobile-related logic didn't fit the name (on mobile, fullscreen isn't "preferred" - it's "required" 😛)

DEV: Move mobileView check out of `FullPageChat.isPreferred`

---

assets/javascripts/discourse/templates/components/chat-channel-row.hbs
test/javascripts/components/chat-channel-row-test.js

UX: show status on the direct message chats list using the new component with rich tooltip

---

assets/javascripts/discourse/templates/components/chat-message-info.hbs
test/javascripts/components/chat-message-info-test.js

UX: show status next to posts using new component with rich tooltip

---

app/jobs/regular/chat_notify_watching.rb
app/models/user_chat_channel_membership.rb
assets/javascripts/discourse/templates/components/chat-channel-settings-view.hbs
lib/chat_channel_fetcher.rb
spec/fabricators/chat_fabricator.rb
spec/jobs/regular/chat_notify_watching_spec.rb
spec/lib/chat_channel_fetcher_spec.rb
spec/requests/api/chat_channel_notifications_settings_controller_spec.rb
test/javascripts/components/chat-channel-settings-view-test.js

This commit allows users to change the Mute settings
for DM channels as they can for regular category channels,
as well as changing the desktop and mobile notification
levels for the channel if it is not muted. It also changes
the unread_count logic for DM channels -- since the channels
can now be muted, the unread count does not always show regardless
for DM channels.

FEATURE: Allow changing DM channel notification settings

---

lib/direct_message_channel_creator.rb
spec/lib/direct_message_channel_creator_spec.rb

Previously, we created or updated UserChatChannelMembership
records in a loop, which added a lot of unnecessary SQL queries
when created a DM channel. For example, creating a new DM channel
for 4 users generated 12 queries (so N users * 3 queries):
* query to select the existing membership for the user
* query to select a channel from an ID (presumably AR doing
this for the association on insert)
* query to insert the membership
Instead, we can do this in a single DB.exec call which does
2 queries regardless of how many users are used to create
the DM channel.
Relies on https://github.com/discourse/discourse-chat/pull/1179 for
tests to pass.

PERF: Reduce membership queries for DirectMessageChannelCreator

---

spec/lib/chat_message_bookmarkable_spec.rb
spec/lib/chat_message_reactor_spec.rb

```
WARNING: Using `expect { }.not_to raise_error(SpecificErrorClass)` risks false positives, since literally any other error would cause the expectation to pass, including those raised by Ruby (e.g. `NoMethodError`, `NameError` and `ArgumentError`), meaning the code you are intending to test may not even get reached. Instead consider using `expect { }.not_to raise_error` or `expect { }.to raise_error(DifferentSpecificErrorClass)`.
```

DEV: Fix rspec warnings

---

app/jobs/regular/chat_notify_mentioned.rb
assets/javascripts/discourse/services/chat.js
lib/chat_mailer.rb
lib/chat_notifier.rb
lib/direct_message_channel_creator.rb
lib/extensions/user_notifications_extension.rb
spec/components/chat_mailer_spec.rb
spec/components/chat_message_creator_spec.rb
spec/lib/direct_message_channel_creator_spec.rb
spec/mailers/user_notifications_spec.rb
spec/requests/chat_channel_controller_spec.rb
test/javascripts/acceptance/chat-test.js
test/javascripts/unit/services/chat-test.js

Other users of the channel should only start tracking once a new message is sent. This is to cover cases where the DM channel can be created _without_ sending a message, such as from the user card "Chat" button.

FIX: only acting user should track channel on creation

---

assets/stylesheets/common/chat-message-images.scss

When there was a problem with an image the built-in frame would expand way outside the message.
Before/After
If anyone has a better solution, please come forward 😄
(originally incorrectly submitted in https://github.com/discourse/discourse/pull/18000 oops 😅)

UX: Hide chat image overflow

---

assets/javascripts/discourse/components/channels-list.js
assets/javascripts/discourse/initializers/chat-setup.js
assets/javascripts/discourse/initializers/chat-sidebar.js
assets/javascripts/discourse/services/chat.js
assets/javascripts/discourse/templates/components/channels-list.hbs
lib/chat_channel_fetcher.rb
plugin.rb
spec/lib/chat_channel_fetcher_spec.rb
spec/plugin_spec.rb
test/javascripts/acceptance/chat-channels-list-test.js
test/javascripts/acceptance/core-sidebar-test.js

Unusable is defined by the following conditions:
- user is not staff
- user doesn’t have any possible public channel
Note this commit is also implementing preload of current user chat channels, preventing a /chat/channels ajax call on each first page load. This was on the roadmap and was needed in this commit to allow for clean initial state.

FEATURE: hides public channels section if unusable

---

app/jobs/scheduled/delete_old_chat_messages.rb
spec/jobs/delete_old_chat_messages_spec.rb

Prior to this fix, we would keep trashed messages in the DB forever.

FIX: deletes trashed messages when hitting retention limit

---

assets/javascripts/discourse/components/chat-composer.js
assets/javascripts/discourse/components/chat-live-pane.js
test/javascripts/acceptance/chat-keyboard-shortcuts-test.js

We can't edit staged messages as they haven't been  propagated on the server yet.

FIX: Arrow Up should edit last non staged message

---

assets/javascripts/discourse/services/chat.js
test/javascripts/unit/services/chat-test.js

Prior to this fix a new dm would not force a resort of the list to push channels with highest unread_count at the top.

FIX: ensures dms are sorted on new-channel event

---

assets/javascripts/discourse/components/chat-live-pane.js

Prior to this fix we were only marking last read message when in drawer mode, however a bug in the `_floatOpenAndFocused` logic could actually return true when in full page mode making the bug much less obvious.
Also take the opportunity to return early if user is not present.
A test here is way too complicated for the current state of chat-live-pane.

FIX: only checks if user is present and has unread messages

---

app/models/chat_channel.rb
assets/javascripts/lib/discourse-markdown/discourse-chat-transcript.js
spec/integration/post_chat_quote_spec.rb
spec/models/chat_message_spec.rb
test/javascripts/acceptance/chat-transcript-test.js

For human facing cases uses the direct link URL: "/chat/channel/:id/:slug"

FIX: /chat/chat_channels/:id is only for json

---

assets/javascripts/discourse/components/chat-composer.js
assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/lib/chat-api.js
assets/javascripts/discourse/services/chat.js
assets/javascripts/discourse/templates/components/chat-composer.hbs
assets/javascripts/discourse/templates/components/chat-live-pane.hbs
assets/javascripts/discourse/templates/components/chat-message.hbs
assets/stylesheets/common/chat-composer.scss
config/locales/client.en.yml
test/javascripts/acceptance/chat-composer-test.js
test/javascripts/unit/services/chat-test.js

- Allows to resend staged messages
- Displays an icon when network is unreliable
- Doesn't make the sed button unusable

FEATURE: adds support for unreliable network

---

test/javascripts/acceptance/chat-user-menu-notifications-test.js

Use `grouped_unread_notifications` instead of `grouped_unread_high_priority_notifications`
Related PR: https://github.com/discourse/discourse/pull/18132

FIX: use grouped_unread_notifications

---

assets/javascripts/discourse/components/chat-live-pane.js
assets/stylesheets/common/chat-skeleton.scss
assets/stylesheets/common/common.scss

- ensures we use scroll and not auto on ios
- 100vh height can be an issue on mobile where we don't have enough space to show skeleton for the resulting height
- a typo where we had two times small and not large
- a silent error where details was not defined
- apply ios scroll fix everytime for now

FIX: minor tweaks to skeleton

---

config/locales/server.en.yml
lib/extensions/category_extension.rb
lib/guardian_extensions.rb
plugin.rb
spec/lib/guardian_extensions_spec.rb
spec/models/category_spec.rb

Currently nothing prevents from deleting a category which has chat enabled on it. This already led to a bug (see commit 07f9cb4).
This PR addresses this issue by not allowing the deletion of a category if a channel is linked to it. This is the same approach we already have for not deleting a category when topics or sub-categories are present.

FIX: Prevent deleting a category that has channels

---

assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/components/chat-message.js
assets/javascripts/discourse/components/chat-vh.js
assets/javascripts/discourse/lib/zoom-check.js

Also creates a zoom library to encapsulate this behavior, not very much testable as it doesn’t work well in tests.

FIX: zoom check doesn't work with tests

---

assets/javascripts/discourse/components/chat-live-pane.js
assets/stylesheets/mobile/chat-message.scss

- removes part of the code which has a very unclear goal at the moment, if this was proven useful, the intent should be made much more clear in the code and a test should written. ATM this is causing scroll bumps when pulling at the bottom of the pane.
- fixes a possible artifact when ios rendering is lagging behind

FIX: tweaks to live pane scroll

---

assets/javascripts/discourse/components/chat-message.js
assets/javascripts/discourse/templates/components/chat-live-pane.hbs
assets/javascripts/discourse/templates/components/chat-message.hbs
assets/stylesheets/mobile/chat-message.scss

This move allows to apply translated3D on parent chat-messages-container (needed to avoid a case of lag rendering on iOS) without suffering from the bug of translated3D + fixed positioning (which is basically creating a different positioning context for fixed)

FIX: moves chat-msg-actions-mobile into live-pane

---

assets/javascripts/discourse/components/chat-live-pane.js

This was proven useful, and while the behavior is not perfect this is even worse without it.

FIX: reverts part of 1b30db

---

assets/javascripts/discourse/components/chat-message.js
assets/javascripts/discourse/templates/components/chat-message.hbs
assets/stylesheets/common/chat-message.scss

- prevents specific anchor styles to leak in other parts of the app
- only checks for emojiPickerIsActive and not emojiPickerIsActive && isHovered, the later was too unforgiven for small messages

FIX: minot tweaks to emoji picket in chat message

---

assets/stylesheets/common/common.scss

It was mostly hidden under the message elements

FIX: Make the scrollbar visible on iOS

---

config/locales/client.en.yml

We only add users who are active and have been seen in the last 3 months
This hint is intended to help avoid some of the confusion that has
surfaced around the current logic.
Copy for channels only available to certain groups may benefit from similar
improvements, but logic to calculate the user count would need to be changed
at the same time, so skipping that for now.
Related:
* https://meta.discourse.org/t/introducing-default-chat-channels-automatically-add-users/233141/31
* https://github.com/discourse/discourse-chat/blob/07f9cb4618465a5f2288fffa0a708d01db2ce175/spec/jobs/regular/auto_manage_channel_memberships_spec.rb#L28-L32

Update "automatically add users" copy

---

lib/discourse_dev/direct_channel.rb

This addresses the same type of issue that was covered in https://github.com/discourse/discourse-chat/pull/912
>When running dev:populate you might not have the admin user specified in
your config yaml file so we should ignore that instead of throwing an
error.
Output before:
```
I did no detect a custom `config/dev.yml` file, creating one for you where you can amend defaults.
There are 9 group records. Creating 6 more.
......
There are 3 user records. Creating 27 more.
...........................
There are 4 category records. Creating 26 more.
..........................
discourse-solved enabled on category 'Travelling' (10).
Creating 30 sample tag records
..............................
There are 6 topic records. Creating 24 more.
........................
There are 1 chatchannel records. …
```

FIX: Dev populate still breaks with missing admin user

---

assets/stylesheets/common/chat-composer-dropdown.scss
assets/stylesheets/common/chat-composer.scss

Mostly fixes the misshaped circle button
Before / After

UX: Tweak the composer styling

---

assets/stylesheets/common/chat-composer.scss
assets/stylesheets/common/chat-replying-indicator.scss
assets/stylesheets/common/common.scss
assets/stylesheets/mobile/chat-composer.scss
assets/stylesheets/mobile/mobile.scss

Before / After
(actually, the composer is now about 6px lower than shown in "After" but I didn't want to retake the screenshot 😛 you can see the final position below)
How our message composer compares now to other apps:

UX: Tweak padding on mobile

---

assets/javascripts/discourse/templates/admin-plugins-chat.hbs
config/locales/client.en.yml

UX: Add help text for webhook URL and remove from index page

---

assets/javascripts/discourse/components/chat-upload.js
assets/javascripts/discourse/templates/components/chat-upload.hbs
test/javascripts/components/chat-upload-test.js

Also takes the opportunity to make `chat-upload` a Glimmer Component
(requires https://github.com/discourse/discourse/pull/18248)

UX: Add lazy loading and dominant-color placeholder for uploads

---

config/locales/client.en.yml

As of https://github.com/discourse/discourse/commit/496f910f03dfbc0a8021561fa7795a68894ef0e4, core automatically adds title to user menu tabs if an i18n string exists at the key `user_menu.tabs.${tab_id}`. This PR adds a string in the right place so core picks it up and uses it for the chat notifications tab.

UX: Add title for the chat notifications tab in the user menu

---

spec/integration/post_chat_quote_spec.rb
spec/models/chat_message_spec.rb

This PR adds the `tabindex="0"` attribute to the emoji markup used in certain tests. This PR should only be merged in after the PR in core is merged (https://github.com/discourse/discourse/pull/18163) which is responsible for adding keyboard accessibility to the emoji picker.
The update to the markup is important to ensure tests will pass.

DEV: Add `tabindex` to emoji markup

---

app/jobs/regular/chat_notify_mentioned.rb
app/jobs/regular/chat_notify_watching.rb
spec/jobs/regular/chat_notify_mentioned_spec.rb
spec/jobs/regular/chat_notify_watching_spec.rb

The user can mute a channel they are a member of, but
still have the desktop/mobile notification levels set
to always/mention. This commit fixes the issue where the
desktop/mobile push notifications were being sent even
if the user had muted the channel.

FIX: Do not desktop/mobile notify on muted channel

---

spec/integration/post_chat_quote_spec.rb
spec/models/chat_message_spec.rb
test/javascripts/acceptance/chat-transcript-test.js

Core is now passing, and we can revert the skipping of tests.

Revert "DEV: Temporarily skip reactions tests (#1254)"

---

test/javascripts/acceptance/chat-live-pane-test.js

This test relies on a dialog in core that is about to change in https://github.com/discourse/discourse/pull/18292. So, to get stuff passing in CI and builds, I'm following this process: 
- skipping the tests (this PR)
- getting the core PR to ✅ in CI
- merging core PR
- reverting the skip and adjusting the test in discourse-chat

DEV: Skip a test temporarily

---

assets/stylesheets/common/common.scss

Removes extra space below input in DiscourseHub on iPads.

FIX: Full page chat height on DiscourseHub iPad

---

test/javascripts/acceptance/chat-test.js

Follow up to core PR
https://github.com/discourse/discourse/commit/9daa6328b525069556de8e9a293f197fbf62fe7f which made some changes to uppy completion
events, which requires us to wait for the composer to be settled before checking the placeholders

DEV: Fix upload test by adding settled

---

app/controllers/chat_controller.rb
app/models/chat_message.rb
app/models/deleted_chat_user.rb
app/models/reviewable_chat_message.rb
app/serializers/chat_message_serializer.rb
app/services/chat_publisher.rb
assets/javascripts/discourse/components/chat-message.js
assets/javascripts/discourse/lib/chat-message-flag.js
config/locales/client.en.yml
config/locales/server.en.yml
config/settings.yml
lib/chat_review_queue.rb
lib/guardian_extensions.rb
plugin.rb
spec/lib/chat_review_queue_spec.rb
spec/models/reviewable_chat_message_spec.rb
spec/requests/chat_controller_spec.rb
spec/serializer/chat_message_serializer_spec.rb
test/javascripts/acceptance/chat-flagging-test.js
test/javascripts/chat-fixtures.js

This PR re-uses core's flag modal so users can select a flag type and send PMs when selecting notify_user or notify_moderators. It also lets staff take actions, or queue chat messages for review.
One difference is that we don't have the concept of "hiding" as we do for posts, so we have to delete messages instead on those scenarios.

FEATURE: Improve chat messages flagging.

---

app/controllers/chat_controller.rb
assets/javascripts/discourse/adapters/chat-message.js
assets/javascripts/discourse/components/chat-live-pane.js
spec/requests/chat_controller_spec.rb
test/javascripts/acceptance/chat-live-pane-test.js

This will deserve an heavier refactoring in the future, and more importantly moving all this logic under something like `/chat/chat_channels/:id/messages?target_message_id=865` to enforce message being a child from the channel.
This commit however prevents the issue for now and ensures this case is tracked for future refactoring with a test.

FIX: enforces chat_channel_id when present

---

assets/javascripts/lib/discourse-markdown/discourse-chat-transcript.js
spec/integration/post_chat_quote_spec.rb
spec/models/chat_message_spec.rb
test/javascripts/acceptance/chat-transcript-test.js

Prior to this fix we were constructing links using: `/chat/message/id` in chat transcript, which is prone to errors.

FIX: prefers /chat/channel/:id/:title?messageId=x link

---

assets/javascripts/discourse/components/channels-list.js
assets/javascripts/discourse/components/chat-browse-view.js
assets/javascripts/discourse/initializers/chat-sidebar.js
assets/javascripts/discourse/templates/components/channels-list.hbs
assets/javascripts/discourse/templates/components/chat-browse-view.hbs
assets/stylesheets/common/chat-browse.scss
config/locales/client.en.yml
test/javascripts/acceptance/chat-test.js
test/javascripts/acceptance/create-channel-test.js

Removes the dropdown with browse/create from the sidebar. As a side effect:
- it's now a button using the pencil icon, leading to browse page
- the new channel button is at the top of browse page
It's only changing behavior for staff, regular users were already not seeing the dropdown as they can’t create channels.

UX: moves new channel button to browse view

---

app/jobs/scheduled/delete_old_chat_messages.rb
db/post_migrate/20221004122254_delete_reviewables_targetting_deleted_chat_messages.rb
spec/jobs/delete_old_chat_messages_spec.rb

Since the job permanently deletes messages instead of trashing them, it makes sense to delete associated flags too.

FIX: Deleting old messages should also clear flags.

---

assets/stylesheets/common/chat-channel-title.scss

FIX: closing button not  visible on chat index page

---

assets/javascripts/discourse/components/chat-composer-upload.js
assets/javascripts/discourse/components/chat-upload.js
assets/javascripts/discourse/templates/components/chat-upload.hbs
assets/stylesheets/common/chat-message-collapser.scss
test/javascripts/components/chat-message-collapser-test.js
test/javascripts/components/chat-upload-test.js

This commit makes it so user-uploaded videos in chat are shown inside a video player rather than as a
downloadable attachment. Same width and height rules as youtube videos defined in 811595b8b13bec45abaf18133379e85d5c670ca3 apply.

FEATURE: Inline video player for video uploads

---

assets/javascripts/discourse/initializers/chat-sidebar.js
config/locales/server.en.yml
lib/guardian_extensions.rb
spec/lib/direct_message_channel_creator_spec.rb
spec/lib/guardian_extensions_spec.rb
test/javascripts/acceptance/core-sidebar-test.js

Users who are not inside any direct_message_enabled_groups should not be able to create DM channels, however if they are messaged by a user who does have this permission they should be able to send messages back in the channel without issue. Update setting description to reflect this.
Also do not show the create direct message channel button in the sidebar for users who do not have permission to do so, where the sidebar is showing for them since another user has opened a DM channel with them.

FIX: direct_message_enabled_groups refinements

---

app/controllers/chat_channels_controller.rb
config/locales/server.en.yml
lib/guardian_extensions.rb
plugin.rb
spec/lib/guardian_extensions_spec.rb
spec/requests/chat_channel_controller_spec.rb

The `chat_allowed_groups` setting is changing in this commit to reflect other group settings, which always allow staff to do the related action regardless of whether the staff user is in one of the designated groups or not.

FIX: Staff should always be able to chat

---

assets/javascripts/discourse/initializers/chat-sidebar.js
assets/stylesheets/sidebar-extensions.scss

In https://github.com/discourse/discourse/pull/18555 we are adding a sidebar function, contentCSSClass, for section links, and this commit uses it to make the muted channels low opacity again, since this is not currently working with the new sidebar.

FIX: Use sidebar contentCSSClass for muted channels

---

lib/chat_channel_fetcher.rb

This decouples the `secured_public_channels` method which also decorates the user memberships from the actual channel searching, filtering, ordering, and limiting based on the user's permissions, so we can just get the channels the user has access to see without needing to know their memberships.

DEV: Split channel search in ChatChannelFetcher into own method

---

app/serializers/chat_message_serializer.rb
app/serializers/chat_view_serializer.rb
app/serializers/reviewable_chat_message_serializer.rb
assets/javascripts/discourse/templates/components/reviewable-chat-message.hbs
assets/stylesheets/common/reviewable-chat-message.scss
config/locales/client.en.yml
config/locales/server.en.yml
lib/chat_review_queue.rb
lib/guardian_extensions.rb
plugin.rb
spec/lib/chat_review_queue_spec.rb
spec/requests/chat_controller_spec.rb
spec/serializer/chat_message_serializer_spec.rb

For flagged DMs, we'll include a transcript of the previous messages (up to ten), which we store in a companion topic.
Additionally, we store the cooked content of the message in the reviewable to prevent users from editing it before staff reviews it.

FEATURE: Enable flagging for DMs

---

test/javascripts/acceptance/core-sidebar-test.js

In preparation for core PR https://github.com/discourse/discourse/pull/18413 which changes JS to load default yml site settings.

DEV: Fix JS tests to use default site settings pt. 2

---

assets/javascripts/discourse/components/chat-live-pane.js

When scrolling the chat live pane on iOS, if the sticky scroll button is clicked during the scroll momentum , that would most likely result in a blank screen. This hack attempts to ensure it doesn’t happen.

FIX: avoids blank screen on ios on sticky scroll

---

assets/javascripts/discourse/components/chat-emoji-picker.js
test/javascripts/components/chat-emoji-picker-test.js

Fitzpatrick scale should only be appended when scale is > 1. This will fix a bug generating invalid reactions URL when the scale was at 1.

FIX: prevents selected toned emoji to append t1

---

assets/stylesheets/common/chat-skeleton.scss

It was particularly visible when switching channels

FIX: prevents shimmer effect to apply to sidebar

---

assets/javascripts/discourse/components/chat-live-pane.js
assets/javascripts/discourse/components/chat-message-actions-desktop.js
assets/stylesheets/desktop/desktop.scss

It prevents various issues like flickering and also perf issues as popper was constantly trying to reposition it. It's very add to test as discourseLater will be to 0 in tests and a result the class is already removed.

PEFF: hide msgactions on scroll

---

assets/javascripts/discourse/components/chat-composer.js
assets/javascripts/discourse/initializers/chat-setup.js
test/javascripts/acceptance/composer-hashtag-autocomplete-test.js

Include context in the setupHashtagAutocomplete call, and use registerHashtagSearchParam to set up category + tag search for the chat composer. We cannot add channel search yet because we need to be able to look up channels by slugs first and also choose/render selected channels. More core work still to come.
c.f. https://github.com/discourse/discourse/pull/18592
**Do not merge until the core PR has merged!**

DEV: Use new setupHashtagAutocomplete + registerHashtagSearchParam APIs

---

test/javascripts/acceptance/chat-test.js
test/javascripts/components/chat-channel-card-test.js
test/javascripts/components/chat-message-info-test.js
test/javascripts/components/chat-replying-indicator-test.js

CSS can slightly affect the result of `element.innerText`. Preparation for https://github.com/discourse/discourse/pull/18668

DEV: Ensure tests work when plugin CSS is loaded

---

app/controllers/emojis_controller.rb

Following https://github.com/discourse/discourse/commit/a705e4815fac1cc74073848a8dfa3c7b441ead22 we don't need to exclude the default group anymore as it will now only contain custom emojis.

FIX: default is now only used for custom emojis

---

test/javascripts/acceptance/chat-live-pane-test.js

When CSS is loaded, `.chat-messages-scroll` is correctly used as the scrolling element for chat messages. Its default position is the bottom, so we need to scroll up manually at the start of the test.
Preparation for https://github.com/discourse/discourse/pull/18668

DEV: Update scrolling test to work with css loaded

---

app/controllers/incoming_chat_webhooks_controller.rb
assets/javascripts/discourse/templates/admin-plugins-chat.hbs
config/locales/client.en.yml
spec/requests/incoming_chat_webhooks_controller_spec.rb

This commit removes the `hijack` on the chat webhooks controller since it is of dubious necessity and because `hijack` is suppressing the correct resposne codes.
Also add some documentation around how the incoming webhooks work, their params, and their limits.
Bump the incoming text param length limit to 2000, 1000 is quite low.

FIX: Remove hijack on webhook and improve documentation

---

app/serializers/chat_message_serializer.rb
app/serializers/reviewable_chat_message_serializer.rb
assets/javascripts/discourse/templates/components/reviewable-chat-message.hbs
spec/serializer/chat_message_serializer_spec.rb

The serializer tried to serialize the whole message, but this needed the channel passed in the options hash to work. I wrote the code this way to avoid fetching each message chat channel when serializing in the context of the `ChatView`.
This change simplifies the reviewable chat message serializer and fallbacks to the object's `chat_channel` when `@options[:chat_channel]` is `nil`.

FIX: Don't fail when trying to display DM flags in the review queue.

---

assets/javascripts/discourse/components/chat-live-pane.js

We have seen some sporadic failures of chat-live-pane tests with the error:
> Test is not isolated (async execution is extending beyond the duration of the test)
This commit should ensure these debounce timers never run beyond the end of the tests.

DEV: Reduce throttle times in test mode to fix flakiness

---

assets/javascripts/discourse/initializers/chat-decorators.js

Only the first message would get the date element and following `dateTimeLinkEl` would be undefined, resulting in an error when trying to assign `innerText`.

FIX: prevents exception when transcripting multiple messages

---

spec/requests/emojis_controller_spec.rb

The spec also now ensures before/after state is not suffering from the state of any other spec.

DEV: improves emojis controller spec to include custom emojis

---

assets/javascripts/discourse/templates/components/chat-message-reaction.hbs
test/javascripts/acceptance/chat-live-pane-test.js
test/javascripts/acceptance/chat-message-test.js
test/javascripts/acceptance/chat-test.js
test/javascripts/components/chat-message-reaction-test.js

Using it as a class can cause unexpected clashes with 'real' CSS classes. Using a data attribute is safer, and can still be targetted by CSS if desired.

FIX: Move reaction emoji name from class to data attribute

---

assets/stylesheets/common/chat-browse.scss
assets/stylesheets/common/dc-filter-input.scss

Before: stuck to sides + placeholder gets cutoff
After:

FIX: Channel index mobile issues

---

assets/javascripts/discourse/components/chat-live-pane.js

safari iOS has the bug when programmatically scrolling to a part of the scrollable element while being in momentum scrolling. This will cause the renderer to lag and cause an empty screen. In the past `-webkit-overflow-scrolling: touch` was used to stop momentum but it's not longer usable since iOS 13. This commit attempts to implement a decent solution to the problem.

FIX: improves iOS hack for momentum scrolling

---

assets/javascripts/discourse/components/chat-live-pane.js

It seems to prevent the hack to work correctly

FIX: removes requestAnimationFrame

---

spec/requests/api/chat_channel_notifications_settings_controller_spec.rb

It now supports strict keyword argument matching by default.

DEV: Fix mocha deprecations
