discourse/discourse-chat

- app/controllers/chat_channels_controller.rb
- assets/javascripts/discourse/components/category-tag-chat-link.js
- assets/javascripts/discourse/components/topic-chat-float.js
- assets/javascripts/discourse/connectors/before-create-topic-button/category-tag-chat-link-connector.hbs
- assets/javascripts/discourse/templates/components/category-tag-chat-link.hbs
- assets/javascripts/discourse/templates/components/chat-live-pane.hbs
- assets/javascripts/discourse/widgets/post-chat-link.js
- assets/javascripts/discourse/widgets/topic-title-chat-link.js
- assets/stylesheets/common/common.scss
- config/locales/client.en.yml
- lib/chat_channel_fetcher.rb
- lib/guardian_extensions.rb
- plugin.rb
- spec/requests/chat_channel_controller_spec.rb
- test/javascripts/acceptance/chat-test.js
> FEATURE: Open chat links from category/tag show

- assets/javascripts/discourse/templates/components/chat-replying-indicator.hbs
- assets/stylesheets/common/common.scss
- assets/stylesheets/desktop/desktop.scss
This reverts commit cdcef9aed20af81d111fdedf21cf23134bb90939.
> Revert "UX: Do not reserve space for presence indicator (#245)"

- assets/javascripts/discourse/components/chat-composer.js
- test/javascripts/acceptance/chat-test.js
In core PR https://github.com/discourse/discourse/pull/15058
we are changing to use uppy by default in the composer, so
there is no need for the experimental composer uploader check.
**Do not merge before core PR.**
> DEV: Change to use uppy processor by default

- assets/javascripts/discourse/templates/components/chat-replying-indicator.hbs
- assets/stylesheets/common/common.scss
- assets/stylesheets/desktop/desktop.scss
Fixes a layout issue with the full page layout when using sidebar.
> UX: Do not reserve space for presence indicator (take 2)

- assets/stylesheets/common/common.scss
This PR changes the border color of the unread notification based on if the user has the sidebar enabled.
> UX: Notification tweaks

- assets/stylesheets/common/common.scss
> UX: Reduce reaction emoji size

- assets/stylesheets/common/common.scss
> UX: Remove lines for nested topic channels

- assets/javascripts/discourse/components/full-page-chat.js
- assets/stylesheets/common/common.scss
- assets/stylesheets/desktop/desktop.scss
This reverts commit a3e05b9ecbf2cef445ce506975e706c667043eb1.
That was causing issues on mobile. Will try a different approach.
> Revert "FIX: Drop --full-page-chat-height to fix app height issue"

- assets/javascripts/discourse/components/chat-live-pane.js
> FIX: Force all external links to open in new tab

- assets/javascripts/discourse/widgets/chat-header-icon.js
https://github.com/discourse/discourse/pull/15218
> FIX: If in PWA with chat isolated, no new tab

- app/controllers/incoming_chat_webhooks_controller.rb
This should be the first thing we do
> DEV: Move debug chat webhook payload

- assets/javascripts/discourse/components/tc-message.js
- assets/javascripts/discourse/templates/components/tc-message.hbs
- assets/stylesheets/common/common.scss
- test/javascripts/acceptance/chat-test.js
> UI: implements link to message button

- assets/stylesheets/common/common.scss
- assets/stylesheets/mobile/mobile.scss
Before I threw a lot of css under `.chat-message`, and this overrode other css properties... we need some cleanup here.
> UX: Do not override other css background colors

- assets/stylesheets/common/common.scss
> UX: Make my reactions lighter blue

- assets/javascripts/discourse/components/tc-message.js
- assets/stylesheets/common/common.scss
- test/javascripts/acceptance/chat-test.js
- test/javascripts/chat-fixtures.js
> FEATURE: Highlight my mentions and @here/@all

- assets/javascripts/discourse/components/tc-message.js
- assets/stylesheets/common/common.scss
> UX: Style `@here` and `@all` mentions like regular mentions

- assets/javascripts/discourse/services/chat.js
In be2db2dd723d1bf4a0d33cf1b78e94c3f4dfb007 we introduced
this method of detecting that the chat window should have
its channels resynced if we fall too far behind from dropped
MessageBus messages. This full resync causes a route transition
and the input to blur from cleanDOM in core. However we did
not update `lastUserTrackingMessageId` if this reload happened,
leaving the state in a permanently bad state.
This commit always updates `lastUserTrackingMessageId` if the
new chat messageId is greater than the `lastUserTrackingMessageId`
regardless of whether all the channels are refreshed.
> FIX: Input blur from user tracking state sync

- assets/javascripts/discourse/components/chat-live-pane.js
- assets/stylesheets/common/common.scss
This is a temporary commit while we work on refactoring lazy-YT plugin out of jQuery.
> FIX: implements bare minimum for working youtube videos

- assets/javascripts/discourse/templates/preferences/chat.hbs
- test/javascripts/acceptance/chat-test.js
Somehow I duplicated this setting without realizing it in my last PR 🤦
> FIX: Remove duplicate setting

- app/controllers/chat_controller.rb
- app/services/chat_publisher.rb
- assets/javascripts/discourse/components/chat-live-pane.js
- assets/javascripts/discourse/components/tc-message.js
- assets/javascripts/discourse/templates/components/tc-message.hbs
- assets/javascripts/discourse/widgets/chat-invitation-notification-item.js
- assets/stylesheets/common/common.scss
- config/locales/client.en.yml
- lib/chat_notifier.rb
- plugin.rb
- spec/components/chat_message_creator_spec.rb
- spec/requests/chat_controller_spec.rb
- test/javascripts/acceptance/chat-test.js
Relies on core PR https://github.com/discourse/discourse/pull/15288
> FEATURE: Alert on mention that allows inviting users to join channel

- app/jobs/regular/create_chat_mention_notifications.rb
- app/jobs/regular/notify_users_watching_chat.rb
- app/models/chat_message.rb
I thought using `excerpt` would be much cleaner, but I forgot it's HTML.... woops
> FIX: Revert change to push notification excerpt

- lib/chat_channel_fetcher.rb
- spec/lib/slack_compatibility_spec.rb
A follow-up to #364.
The change in slack_compatibility_spec.rb is unrelated but fixes specs.
> FIX: A proper fix for calculating unread counts

- app/controllers/direct_messages_controller.rb
- app/models/direct_message_channel.rb
- app/serializers/direct_message_channel_serializer.rb
- assets/javascripts/discourse/services/chat.js
- assets/javascripts/discourse/templates/components/dm-creator.hbs
- spec/models/direct_message_channel_spec.rb
- spec/requests/direct_messages_controller_spec.rb
- spec/serializer/direct_message_channel_serializer_spec.rb
- test/javascripts/acceptance/chat-test.js
- test/javascripts/acceptance/direct-message-test.js
- test/javascripts/chat-fixtures.js
And also put my own DM at the top
.
> FEATURE: Let me talk to myself

- app/controllers/chat_channels_controller.rb
- app/services/chat_publisher.rb
- assets/javascripts/discourse/components/chat-channel-settings-row.js
- assets/javascripts/discourse/services/chat.js
- assets/javascripts/discourse/templates/components/chat-channel-settings-row.hbs
- assets/stylesheets/common/common.scss
- assets/stylesheets/desktop/desktop.scss
- assets/stylesheets/mobile/mobile.scss
- config/locales/client.en.yml
- lib/guardian_extensions.rb
- plugin.rb
- spec/requests/chat_channel_controller_spec.rb
- test/javascripts/acceptance/chat-test.js
> FEATURE: Renaming channels from browse page

- assets/javascripts/discourse/components/chat-message-reaction.js
- assets/javascripts/discourse/templates/components/chat-message-reaction.hbs
- assets/javascripts/discourse/templates/components/tc-message.hbs
- assets/stylesheets/common/common.scss
- test/javascripts/acceptance/chat-test.js
- uses chat-message-reaction for favorite reactions
- various minor refactoring to chat-message-reaction component
- larger hitzone for buttons of tc-msgactions container
- gives role=button to chat-message-reaction
> DEV: refactoring of favorite reactions and chat-message-reaction

- assets/stylesheets/common/common.scss
* No double border
* All button have the same width
* "…" button has the same color
Before / After
updated After:
> UX: Tweak .tc-msgactions CSS

- assets/stylesheets/common/common.scss
Mostly fixes overlapping elements of oneboxes, oversized images in tweets.
> UX: Various CSS fixes

- assets/javascripts/discourse/components/chat-composer.js
- assets/javascripts/discourse/components/full-page-chat.js
- assets/javascripts/discourse/routes/chat-channel.js
- assets/javascripts/discourse/services/chat.js
- assets/javascripts/discourse/templates/components/chat-live-pane.hbs
- config/locales/client.en.yml
- config/settings.yml
- test/javascripts/components/chat-composer-placeholder-test.js
Essentially https://github.com/discourse/discourse-chat/pull/384
but with a SiteSetting that helps me turn it on and off to debug why it's not refreshing on dev.
> DEV: Show context-aware placeholders and debug why they're not refreshing

- assets/javascripts/discourse/templates/components/chat-channel-title.hbs
- assets/stylesheets/common/common.scss
- assets/stylesheets/desktop/desktop.scss
- assets/stylesheets/mobile/mobile.scss
* Makes emoji small in channel names
* Fixes alignment of some sidebar elements
* Tweaks the styling of message reactions
* Remove non-hoverable space between messages
> UX: Mostly chat sidebar CSS fixes

- assets/javascripts/discourse/components/chat-live-pane.js
- assets/javascripts/discourse/templates/components/tc-message.hbs
- assets/stylesheets/common/common.scss
- test/javascripts/acceptance/chat-test.js
- test/javascripts/chat-fixtures.js
> FEATURE: displays a separator between days

- assets/stylesheets/common/common.scss
> UX: Small daily message tweaks

- assets/javascripts/discourse/components/chat-message-reaction.js
- assets/stylesheets/common/common.scss
This commit also makes reactions tabbable
> UI: makes all actions having a consistent styling

- assets/javascripts/discourse/components/channel-list.js
- assets/javascripts/discourse/templates/components/channel-list.hbs
- assets/stylesheets/common/common.scss
- test/javascripts/acceptance/chat-test.js
- drops custom popup code for SK, solves few accessibility issues and makes it easier to style
- go tagLess
- few minor changes
> REFACTOR: channel-list

- assets/stylesheets/common/common.scss
A couple small things regressed in #411. This commit also makes the focus styles more palatable.
> UX: Tweak on-hover menu css

- assets/stylesheets/common/common.scss
- assets/stylesheets/desktop/desktop.scss
(and a very minor tweak to .first-daily-message)
Before / After
> UX: Make the full-page chat more core-like

- assets/stylesheets/common/common.scss
> UX: Minor emoji alignment fix

- spec/components/chat_message_creator_spec.rb
- spec/requests/chat_controller_spec.rb
- spec/requests/move_to_topic_controller_spec.rb
Fixes two failing specs on my setup. Also minor typos.
There's also a flaky spec that I can repro locally… 👀 ~~Still looking!~~
https://github.com/discourse/discourse-chat/runs/4693826733?check_suite_focus=true
> DEV: Don't double-signin in specs

- assets/javascripts/discourse/components/channel-list.js
It was because of going tag less on the component and this.element was always null.
> FIX: user chooser was not auto opened anymore

- assets/stylesheets/common/common.scss
This PR adjusts the placement of the notifications drop down on the browse channels page.
> UX: Drop down placement adjustment

- assets/stylesheets/common/common.scss
> FIX: Fix margins for multiline text

- assets/javascripts/discourse/components/chat-composer.js
- assets/javascripts/discourse/components/chat-live-pane.js
- assets/javascripts/discourse/services/chat.js
- assets/javascripts/discourse/templates/components/chat-live-pane.hbs
- test/javascripts/acceptance/chat-test.js
@CvX I know you'll have the async in the test... but the chat float component waits on a promise to check the channels so... idk how else to do this shiz.
> FEATURE: Store reply-to in draft

- assets/javascripts/discourse/controllers/create-channel-modal.js
- assets/javascripts/discourse/templates/modal/create-channel-modal.hbs
- assets/stylesheets/common/common.scss
- config/locales/client.en.yml
- test/javascripts/acceptance/create-channel-modal-test.js
Before:
Shows a link to categories when no category is selected:
Shows a link to /c/category-slug/edit/security if a category is selected
> UX: Show better copy when creating channels

- assets/stylesheets/common/common.scss
- assets/stylesheets/mobile/mobile.scss
- size of the indicator for non direct messages
- wrong indicator color for direct messages
- removes unused css rules
> UI: fixes various minor issues

- assets/javascripts/discourse/components/chat-channel-title.js
- assets/javascripts/discourse/models/chat-channel.js
- assets/javascripts/discourse/templates/components/chat-channel-title.hbs
- test/javascripts/components/chat-channel-title-test.js
- test/javascripts/helpers/fabricators.js
> REFACTOR: chat-channel-title

- assets/stylesheets/common/common.scss
The rows are too large right now in the sidebar and I do not like iitttt
> UX: Adjust sidebar channel row height

- assets/javascripts/discourse/components/chat-replying-indicator.js
- assets/javascripts/discourse/templates/components/chat-replying-indicator.hbs
- assets/stylesheets/common/common.scss
- test/javascripts/acceptance/chat-test.js
- test/javascripts/components/chat-replying-indicator-test.js
- test/javascripts/helpers/mock-presence-channel.js
- tagLess
- renames `tc-replying-indicator` into `chat-replying-indicator`
- test component in isolation
- minor changes
> REFACTOR: chat-replying-indicator

- assets/javascripts/discourse/components/chat-live-pane.js
- assets/javascripts/discourse/components/chat-message.js
- assets/javascripts/discourse/templates/components/chat-live-pane.hbs
- assets/javascripts/discourse/templates/components/chat-message-text.hbs
- assets/javascripts/discourse/templates/components/chat-message.hbs
- assets/stylesheets/common/chat-message.scss
- assets/stylesheets/common/common.scss
- assets/stylesheets/desktop/desktop.scss
- test/javascripts/acceptance/chat-test.js
- test/javascripts/components/chat-message-text-test.js
Related: https://github.com/discourse/discourse-chat/pull/483
> DEV: Replace all instances of tc-message to chat-message

- assets/javascripts/discourse/components/chat-composer.js
- assets/javascripts/discourse/components/chat-live-pane.js
- assets/javascripts/discourse/components/chat-message.js
- assets/javascripts/discourse/helpers/format-chat-date.js
- assets/javascripts/discourse/templates/components/channel-list.hbs
- assets/javascripts/discourse/templates/components/chat-composer-message-details.hbs
- assets/javascripts/discourse/templates/components/chat-composer.hbs
- assets/javascripts/discourse/templates/components/chat-live-pane.hbs
- assets/javascripts/discourse/templates/components/chat-message-collapser.hbs
- assets/javascripts/discourse/templates/components/chat-message.hbs
- assets/javascripts/discourse/templates/components/topic-chat-float.hbs
- assets/stylesheets/common/chat-message.scss
- assets/stylesheets/common/common.scss
- assets/stylesheets/desktop/desktop.scss
- assets/stylesheets/mobile/mobile.scss
- test/javascripts/acceptance/chat-test.js
- test/javascripts/components/chat-composer-placeholder-test.js
- test/javascripts/components/chat-message-collapser-test.js
With the exception of
```
(chat-channel-title.hbs)
tc-avatar-container
tc-user-presence-flair
(chat-composer-message-details.hbs)
tc-reply-display
tc-reply-av
tc-reply-username
(chat-message.hbs)
tc-reply-display
tc-reply-av
tc-reply-msg
tc-avatar
tc-avatar-container
(tc-user-presence-flair.hbs)
tc-presence-flair
tc-bot-indicator
tc-reply-wave (animation)
```
Since there is a separate refactor going on
> DEV: tc- rename all the things \o/

- assets/javascripts/discourse/components/chat-message-collapser.js
- assets/javascripts/discourse/components/chat-message-text.js
- assets/javascripts/discourse/templates/components/chat-message-collapser.hbs
- assets/javascripts/discourse/templates/components/chat-message-text.hbs
- assets/javascripts/discourse/templates/components/chat-message.hbs
- assets/stylesheets/common/chat-message.scss
- assets/stylesheets/common/common.scss
- test/javascripts/components/chat-message-collapser-test.js
- test/javascripts/components/chat-message-text-test.js
and make sure they don't stretch past the chat area's width
> FEATURE: Also collapse gifs

- assets/stylesheets/common/common.scss
> UI: uses primary for icon color on direct hover

- assets/stylesheets/common/chat-message-collapser.scss
- assets/stylesheets/common/common.scss
- plugin.rb
Styles in their own component stylesheet
> DEV: Extract collapser styles into their own file

- assets/stylesheets/common/chat-message.scss
- assets/stylesheets/common/common.scss
- assets/stylesheets/desktop/desktop.scss
- assets/stylesheets/mobile/mobile.scss
* UX: Remove mobile background color
* UX: Remove hover style from mobile chat list
* UX: Add safe-area padding
* UX: Remove alert-info spacing also on mobile
* DEV: Remove an unused grid-area
> UX: Various mobile improvements

- app/jobs/regular/create_chat_mention_notifications.rb
- assets/javascripts/discourse/components/chat-composer.js
- assets/javascripts/discourse/widgets/chat-mention-notification-items.js
- config/locales/client.en.yml
- config/locales/server.en.yml
- lib/chat_notifier.rb
- spec/components/chat_message_creator_spec.rb
- test/javascripts/acceptance/chat-test.js
Currently group mentions do not work. This PR changes that :)
Relies on core PR for notification type to be added https://github.com/discourse/discourse/pull/15616
> FEATURE: Ability to mention groups

- app/jobs/regular/create_chat_mention_notifications.rb
- assets/javascripts/discourse/components/chat-composer.js
- assets/javascripts/discourse/widgets/chat-mention-notification-item.js
- config/locales/client.en.yml
- config/locales/server.en.yml
- lib/chat_notifier.rb
- spec/components/chat_message_creator_spec.rb
- test/javascripts/acceptance/chat-test.js
This reverts commit be7bf80da19980b6aab9965a47f691b10b1c03d0.
> REVERT: "FEATURE: Ability to mention groups (#527)"

- app/jobs/regular/create_chat_mention_notifications.rb
- assets/javascripts/discourse/components/chat-composer.js
- assets/javascripts/discourse/widgets/chat-mention-notification-items.js
- config/locales/client.en.yml
- config/locales/server.en.yml
- lib/chat_notifier.rb
- spec/components/chat_message_creator_spec.rb
- test/javascripts/acceptance/chat-test.js
This reverts commit d0f4820e81eeff1e9f1d93469126f21d7c12a919.
Let's give it another go and I can debug on server.
> REVERT: "Revert "FEATURE: Ability to mention groups (#527)" (#532)"

- assets/javascripts/discourse/initializers/chat-setup.js
@jordanvidrine wants this class so that he can scope sidebar css only for users with chat enabled.
> DEV: Add class to body when chat is enabled

- assets/javascripts/discourse/initializers/chat-setup.js
- assets/stylesheets/common/common.scss
- assets/stylesheets/sidebar-extensions.scss
This PR adjusts the padding and spacing a bit on the sidebar when chat is enabled. The changes are subtle!
> UX: Sidebar edits

- assets/stylesheets/sidebar-extensions.scss
This PR is required to mesh well with the current sidebar-scroll refactor in the teams sidebar plugin. There are no visual changes here, only small edits to accommodate for the scroll bar.
> UX: Sidebar padding edits

- assets/stylesheets/common/common.scss
This PR slightly increase the size of the buttons via button padding in the uploads button section. I've also added a hover effect to keep it in line with other buttons in this section.
> UX: Increase uploads buttons sizes

- config/locales/server.en.yml
Fixed a small typo : reguar --> regular
> Fixed a typo

- test/javascripts/acceptance/chat-test.js
a897f86a removed the use of `next()` in this plugin's tests, so that they passed consistently on Ember CLI. Unfortunately that change broke the tests under the legacy Ember environment. This commit restores the hack **for the legacy environment only**, and wraps it up in a `chatSettled` helper so we can easily remove it in future.
I'm not sure exactly why this hack is required. Since it only affects the older Ember version running in the legacy environment, I decided not to investigate in detail.
> DEV: Restore test runloop hack for legacy ember environment

- app/controllers/chat_controller.rb
- app/jobs/regular/process_chat_message.rb
- app/models/chat_message.rb
- assets/javascripts/discourse/components/chat-message.js
- config/locales/client.en.yml
- lib/guardian_extensions.rb
- plugin.rb
- spec/jobs/process_chat_message_spec.rb
- spec/requests/chat_controller_spec.rb
- test/javascripts/acceptance/chat-test.js
This is an advanced feature but can be quite useful, especially while developing chat.
> DEV: displays a rebake button to admin for each message

- assets/stylesheets/common/chat-retention-reminder.scss
- assets/stylesheets/common/common.scss
- assets/stylesheets/desktop/desktop.scss
Previously I overshot it a bit with size of the buttons/dropdown.
---
~~Can a sidebar user please confirm it doesn't affect their layout? 😃~~
Checked and updated.
> UX: Slightly tighter headers

- assets/javascripts/discourse/components/chat-composer.js
Update to chat-composer to support the changes from
the https://github.com/discourse/discourse/pull/15787 core PR.
> DEV: Add editorClass to composer

- assets/stylesheets/common/chat-message.scss
> FIX: A visual regression introduced in #585

- app/models/chat_message.rb
Will be used to integrate with discourse-gifs
https://user-images.githubusercontent.com/1385470/152429115-46046989-8ec7-4905-9535-2bf2d4f5123f.mp4
> FEATURE: Allow image markdown markup

- assets/javascripts/discourse/components/chat-message-collapser.js
- assets/javascripts/discourse/templates/components/chat-message-collapser.hbs
- assets/stylesheets/common/chat-message-collapser.scss
- test/javascripts/components/chat-message-collapser-test.js
Just another type of image to collapse. The difference is that this one is cooked different from the rest, like this
```
<p><img src=...></p>
```
> FEATURE: Collapse non-oneboxed gifs and images in general

- assets/stylesheets/common/chat-message.scss
> FIX: Height of emojis

- assets/stylesheets/common/common.scss
- assets/stylesheets/sidebar-extensions.scss
This PR makes minor adjustments to get the spacing & alignment working properly on teams sidebar, as well as chat in core.
> UX: Minor fixes for font, width, and icon adjustments

- plugin.rb
This PR needs new plugin API: https://github.com/discourse/discourse/pull/15545
> DEV: Use new register_upload_in_use API

- app/controllers/chat_controller.rb
- app/models/chat_draft.rb
- assets/javascripts/discourse/services/chat.js
- db/migrate/20220203204002_create_chat_drafts_table.rb
- db/migrate/20220203204003_migrate_drafts_to_chat_drafts.rb
- lib/chat_message_creator.rb
- plugin.rb
- spec/components/chat_message_creator_spec.rb
- spec/requests/chat_controller_spec.rb
This PR needs new plugin API: https://github.com/discourse/discourse/pull/15545
> DEV: Use new model for chat drafts

- app/controllers/chat_controller.rb
- assets/javascripts/discourse/components/chat-live-pane.js
- assets/javascripts/discourse/components/chat-message.js
- assets/javascripts/discourse/templates/components/chat-live-pane.hbs
- assets/javascripts/discourse/templates/components/chat-message.hbs
- config/locales/client.en.yml
- spec/requests/chat_controller_spec.rb
- test/javascripts/acceptance/chat-send-error-test.js
> FEATURE: Rate limit message sending with btn to re-send

- assets/stylesheets/common/chat-message.scss
Accompanies https://github.com/discourse/discourse/pull/16027.
> DEV: Uniform `ol`/`ul` padding

- plugin.rb
It should have returned from the block instead. Another fix is that
'exists?' does not accept the same arguments as 'where' and in this
case both 'where' and 'exists?' must be called.
> FIX: Upload in use callback returned from method

- assets/stylesheets/common/common.scss
This PR fixes the background color changing to a light color on dark color schemes.
> FIX: Always use dark color for background on upload

- assets/javascripts/discourse/components/chat-message-text.js
Just a remnant of the past that wasn't cleaned up.
> DEV: Cleanup

- app/controllers/chat_controller.rb
- app/serializers/chat_view_serializer.rb
- assets/javascripts/discourse/components/chat-composer.js
- assets/javascripts/discourse/components/chat-live-pane.js
- assets/javascripts/discourse/components/chat-message-collapser.js
- assets/javascripts/discourse/components/chat-message.js
- assets/javascripts/discourse/templates/components/chat-composer.hbs
- assets/javascripts/discourse/templates/components/chat-live-pane.hbs
- assets/javascripts/discourse/templates/components/chat-message.hbs
- config/locales/client.en.yml
- lib/guardian_extensions.rb
- spec/requests/chat_controller_spec.rb
- test/javascripts/acceptance/chat-browse-test.js
- test/javascripts/acceptance/chat-flagging-test.js
- test/javascripts/acceptance/chat-live-pane-collapse-test.js
- test/javascripts/acceptance/chat-live-pane-silenced-user-test.js
- test/javascripts/acceptance/chat-quoting-test.js
- test/javascripts/acceptance/chat-test.js
- test/javascripts/acceptance/create-channel-modal-test.js
- test/javascripts/chat-fixtures.js
Staff view - 
View for a silenced user - 
j
> FEATURE: Quick silence button for staff, and block silenced users from interacting w/ chat

- test/javascripts/acceptance/chat-transcript-test.js
This is a companion commit to https://github.com/discourse/discourse/pull/16050
to add tests for the fix there, which was that we weren't hoisting
the html_raw tokens from the custom markdown engine properly, which
caused issues with onebox rendering.
> DEV: Add tests for onebox rendering within [chat] 

- assets/stylesheets/common/common.scss
This PR fixes the colors for the icons for buttons in the chat channel title on the browse page.
> UX: Icon color variable fix

- assets/javascripts/discourse/widgets/chat-header-icon.js
On a channel on mobile, will attempt to display channels index list page when click the chat icon
> UX: improves behavior of the icon when chat is visible

- assets/javascripts/discourse/components/chat-channel-row.js
- assets/javascripts/discourse/components/chat-channel-selector-modal-inner.js
- assets/javascripts/discourse/components/chat-composer.js
- assets/javascripts/discourse/components/chat-live-pane.js
- assets/javascripts/discourse/initializers/chat-setup.js
- assets/javascripts/discourse/services/chat.js
- assets/javascripts/discourse/templates/components/chat-channel-row.hbs
- assets/javascripts/discourse/templates/components/chat-channel-settings-row.hbs
- assets/javascripts/discourse/templates/components/chat-channel-title.hbs
- assets/javascripts/discourse/templates/components/chat-message.hbs
- assets/javascripts/discourse/templates/components/chat-to-topic-selector.hbs
- assets/javascripts/discourse/templates/components/topic-chat-float.hbs
- assets/javascripts/discourse/widgets/chat-header-icon.js
- assets/javascripts/lib/discourse-markdown/discourse-chat-transcript.js
- package.json
- test/javascripts/acceptance/chat-keyboard-shortcuts-test.js
- test/javascripts/acceptance/chat-test.js
- test/javascripts/chat-fixtures.js
- test/javascripts/components/chat-channel-row-test.js
- yarn.lock
The only highlight is that I replaced "keydown/mousedown" with "keyup/mouseup" as those are recommended defaults (for A11Y)
> DEV: Update linting, fix issues

- assets/stylesheets/common/common.scss
> UI: reduces is-online circle width

- app/models/chat_message.rb
- assets/javascripts/discourse/components/chat-composer.js
- assets/javascripts/discourse/templates/components/chat-composer.hbs
- assets/stylesheets/common/common.scss
- config/locales/server.en.yml
- config/settings.yml
- lib/chat_message_creator.rb
- lib/chat_message_updater.rb
- spec/components/chat_message_creator_spec.rb
- spec/components/chat_message_updater_spec.rb
- test/javascripts/components/chat-composer-attachments-test.js
This also adds more tests and refactors some code that made me revert in the first place :)
> REVERT: Re-revert minimum length and upload disabling

- test/javascripts/acceptance/chat-test.js
Previously skipped this one because it wasn't
working in CI, let's test it now and also test
for the composer not getting a placeholder for
the in progress upload
> DEV: Add chat upload test

- app/jobs/regular/create_chat_mention_notifications.rb
- app/jobs/regular/notify_users_watching_chat.rb
- app/models/chat_channel.rb
- assets/javascripts/discourse/components/chat-channel-settings-row.js
- assets/javascripts/discourse/widgets/chat-mention-notification-items.js
- config/locales/client.en.yml
- config/locales/server.en.yml
> UX: Even more consistent chat notifications

- assets/stylesheets/common/common.scss
Based on [chat beta tester feedback](https://meta.discourse.org/t/chat-plug-in-feedback/222428/5)
> FIX: Apply truncation on text placeholder

- config/locales/client.en.yml
- plugin.rb
- spec/integration/custom_api_key_scopes_spec.rb
This adds an api scope for creating messages. Also added some specs to
verify you can scope to specific channels.
> DEV: Add api scope for creating messages

- assets/javascripts/discourse/connectors/topic-footer-main-buttons-before-create/topic-chat-button.hbs
- assets/javascripts/discourse/initializers/chat-topic-changes.js
- assets/javascripts/discourse/widgets/topic-chat-button.js
- assets/stylesheets/common/common.scss
- config/locales/client.en.yml
https://user-images.githubusercontent.com/11170663/162688848-1bca3734-156f-4a4b-9db8-c5458d298e14.mov
> FEATURE: add chat button on topic page under topic timeline and footer

- assets/javascripts/discourse/components/chat-replying-indicator.js
- test/javascripts/acceptance/chat-test.js
- test/javascripts/components/chat-replying-indicator-test.js
This commit also improves tests.
> FIX: fixes a regression preventing indicator to show

- config/locales/client.en.yml
> FIX: Add missing tooltip to icon in topic list

- assets/javascripts/discourse/components/direct-message-creator.js
Writing a test for this would currently be almost useless given we would essentially be testing the mock behavior.
> FIX: allows to DM yourself

- assets/javascripts/discourse/components/chat-live-pane.js
- assets/javascripts/discourse/components/full-page-chat.js
- assets/javascripts/discourse/components/topic-chat-float.js
- assets/javascripts/discourse/services/chat.js
Writing a test here would be a lot of work in the current state, both to write and maintain, Im postponing this to us having system tests as they should be available soon.
> FIX: improves channel switching when upserting

- assets/javascripts/discourse/components/chat-live-pane.js
This is kinda brute-forcing the problem, but that makes the code slightly more clear, and should allow easier refactoring/testing in future commits
> FIX: ensures we don't double subscribe to updates

- assets/javascripts/discourse/initializers/chat-setup.js
- assets/javascripts/discourse/services/chat.js
- reverts previous unnecessary onPageChange use
- uses computed helpers where possible
> FIX: get + computed causing issues on legacy

- assets/javascripts/discourse/components/chat-message-text.js
- assets/javascripts/discourse/templates/components/chat-message.hbs
> DEV: Remove unused properties

- assets/javascripts/discourse/components/chat-composer.js
- assets/javascripts/discourse/components/chat-live-pane.js
- assets/javascripts/discourse/templates/components/chat-live-pane.hbs
- config/locales/client.en.yml
This reverts commit 9944e9dd713c6ce6af1fdeba5a23579189df5212.
> Revert "UX: display staged message when creating channel  (#793)"

- .github/pull_request_template.md
> DEV: Introduce PR template

- assets/stylesheets/common/chat-message-separator.scss
- assets/stylesheets/common/chat-message.scss
- assets/stylesheets/mobile/chat-message.scss
> UX: Disable text selection on more elements

- assets/javascripts/discourse/components/chat-message.js
Previously we were running the decorators every time any attribute on the `{{chat-message}}` was changed. Simply mousing in on out of a message would cause the decorators to be re-run, which is incredibly inefficient.
> PERF: Only decorate messages when cooked changes

- assets/javascripts/discourse/services/chat-emoji-reaction-store.js
See https://github.com/discourse/discourse/pull/16917
> DEV: Apply emoji-store changes to match core

- test/javascripts/acceptance/chat-quoting-test.js
These were failing and I originally didn't see why, then I
realised it's because I didn't add channelId into the faked
response in 7363981de5bb2796525039c073a6a29ad88961a9
> DEV: Unskip quote tests

- test/javascripts/acceptance/chat-quoting-test.js
I suspect it's still not working consistently.
> DEV: skip quotes tests

- assets/javascripts/discourse/components/chat-live-pane.js
Way too complicated to test in the current state of coupling
> FIX: ensures staged message is not using upload array ref

- assets/javascripts/discourse/components/full-page-chat.js
- assets/javascripts/discourse/initializers/chat-setup.js
Attempts to:
- refresh notifications state
- recompute full page chat height
> FIX: refresh chat state when tab gains visibility

- assets/stylesheets/common/common.scss
- config/locales/client.en.yml
> UX: Tweak the archived channel UI

- spec/lib/chat_channel_archive_service_spec.rb
https://github.com/discourse/discourse/commit/9db8f00b3dd6f2881adf1b786e29426889225e7a
> FIX: tests were broken following core change

- assets/javascripts/discourse/components/chat-live-pane.js
I wish I could test this, but I don't see any way to do this in the current state I would have to refactor most of the logic to be able to do so.
> UX: ensures sticking to bottom loads from last message

- config/locales/server.en.yml
- config/settings.yml
- lib/chat_message_rate_limiter.rb
- spec/components/chat_message_rate_limiter_spec.rb
Note, not migrating site setting, accepting risk since we are in early beta.
> DEV: correct silence / silience typo

- spec/models/chat_message_spec.rb
Depends on https://github.com/discourse/discourse/pull/17099
> DEV: Fix spec for Markdown.it 13

- app/controllers/chat_channels_controller.rb
- lib/chat_message_creator.rb
Co-authored-by: Martin Brennan <martin@discourse.org>
> DEV: Remove unused code

- lib/chat_message_bookmarkable.rb
- spec/lib/chat_message_bookmarkable_spec.rb
The Bookmark.cleanup! method is called on a schedule in
core, and calls the cleanup_deleted method on each
registered bookmarkable. This commit adds that method
to ChatMessageBookmarkable, and also a missing validate_before_create
method to the bookmarkable to ensure the bookmark can be
created for the message.
> FIX: Clean up deleted chat message bookmarks

- assets/stylesheets/common/common.scss
- assets/stylesheets/sidebar-extensions.scss
This commit also removes a big chunk of duplicated css
> FIX: channel title height without sidebar

- assets/stylesheets/common/common.scss
> FIX: notification shape

- assets/stylesheets/common/common.scss
This is a temporary fix as new browse page is coming soon.
> FIX: correctly make browse page scrollable

- README.md
https://meta.discourse.org/t/discourse-chat/230881
> DOCS: link to correct Meta topic

- lib/chat_channel_fetcher.rb
This part of the code has been forgotten in https://github.com/discourse/discourse-chat/commit/ca528966dfc4be9a920a8477813892e19a38d0a2
> DEV: removes topic code from chat channel fetch

- assets/stylesheets/common/common.scss
Fixed this yesterday but this is a better solution
> UX: chat msg indicator fix with flex

- assets/stylesheets/common/core-extensions.scss
- plugin.rb
- bootstrap mode notice
- create topics notice
> UX: hides useless notices for chat

- assets/javascripts/discourse/templates/chat.hbs
- assets/stylesheets/desktop/sidebar-extensions.scss
> UX: Fix width of full page chat when paired with experimental sidebar

- assets/javascripts/discourse/helpers/slugify-channel.js
- assets/javascripts/discourse/lib/slugify-channel.js
- assets/javascripts/discourse/services/chat.js
- test/javascripts/unit/lib/slugify-channel-test.js
- creates a common implementation
- support cyrillic
- adds tests
> FIX: improves slugify channel

- assets/stylesheets/common/chat-channel-card.scss
> UX: clickable target for setting icon

- test/javascripts/acceptance/chat-keyboard-shortcuts-test.js
- test/javascripts/acceptance/chat-test.js
- test/javascripts/components/chat-channel-row-test.js
> DEV: Use key names in `triggerKeyEvent()`

- config/locales/client.en.yml
- lib/chat_statistics.rb
- plugin.rb
- spec/lib/chat_statistics_spec.rb
This commit introduces statistics for chat that will show
on the /about endpoint and can also be used for other reporting.
> FEATURE: Statistics for chat messages, users, and channels

- assets/javascripts/discourse/components/chat-message-actions-mobile.js
- assets/javascripts/discourse/components/chat-message-reaction.js
- assets/javascripts/discourse/components/chat-message.js
Saves us a handful of warnings.
> DEV: Don't vibrate in tests

- app/queries/chat_channel_memberships_query.rb
- spec/queries/chat_channel_memberships_query_spec.rb
Only treats channels with category as chatable, further todo should work out direct message channels.
> FIX: ensures user can see channel even with membership

- assets/javascripts/discourse/initializers/chat-sidebar.js
- test/javascripts/acceptance/core-sidebar-test.js
Show flair when a user participating in direct message is on holiday
> FEATURE: holiday flair in sidebar

- assets/javascripts/discourse/components/chat-composer.js
- assets/javascripts/discourse/components/chat-live-pane.js
- assets/javascripts/discourse/components/chat-message.js
- assets/javascripts/discourse/lib/body-scroll-lock.js
- assets/javascripts/discourse/templates/components/chat-live-pane.hbs
- hides keyboard when showing menu
- prevents body scroll as much as possible on iOS
> UX: more composer fixes

- assets/javascripts/discourse/templates/chat.hbs
- test/javascripts/acceptance/core-sidebar-test.js
Related to https://github.com/discourse/discourse/pull/17662
> FIX: use new enable_sidebar setting

- test/javascripts/acceptance/core-sidebar-test.js
Additional test to cover changes from https://github.com/discourse/discourse-chat/pull/1093
> DEV: additional test to ensure sidebar is visible

- assets/javascripts/discourse/templates/chat-channel-info.hbs
- assets/javascripts/discourse/templates/components/chat-browse-view.hbs
- assets/javascripts/discourse/templates/components/chat-channel-members-view.hbs
- assets/stylesheets/common/chat-browse.scss
- assets/stylesheets/common/chat-channel-info.scss
- assets/stylesheets/common/chat-tabs.scss
- test/javascripts/components/chat-channel-members-view-test.js
- [ x mobile – `?mobile_view=1`
> Ux channel styling

- assets/javascripts/discourse/components/chat-live-pane.js
Use feature implemented in this PR: https://github.com/discourse/discourse/pull/17727
> FEATURE: scroll to sidebar chat section on enter

- assets/javascripts/discourse/initializers/chat-sidebar.js
> UX: Skip sidebar additions if user has disabled chat

- test/javascripts/acceptance/chat-channel-info-test.js
- test/javascripts/acceptance/chat-keyboard-shortcuts-test.js
- test/javascripts/acceptance/chat-move-message-to-channel-test.js
- test/javascripts/acceptance/delete-chat-channel-modal-test.js
- test/javascripts/chat-fixtures.js
Automatically correct the title of a channel has exposed multiple incorrect tests. This should bring us to a sane state.
> DEV: fix tests

- lib/direct_message_channel_creator.rb
Companion commit to core PR https://github.com/discourse/discourse/pull/17737
Follow up to 74584ff3ca2d29caf243dd413509d0cc03b29a88
> DEV: Use new UserCommScreener core methods for DM creator

- assets/stylesheets/common/common.scss
It causes more issues than it solves, a proper fix is probably much more involved as it will at least force to refactor msg-actions to be at the pane level instead of the message level.
> FIX: removes -webkit-overflow-scrolling

- test/javascripts/acceptance/chat-test.js
- test/javascripts/chat-fixtures.js
> DEV: Don't use site channels in tests

- assets/javascripts/discourse/components/chat-selection-manager.js
- assets/javascripts/discourse/templates/components/chat-selection-manager.hbs
- assets/stylesheets/common/chat-selection-manager.scss
- config/locales/client.en.yml
- test/javascripts/acceptance/chat-quoting-test.js
1. Restored the message (regressed in #1146)
2. Fixed the animation (regressed in #790)
3. Fixed element placement
4. Restored and updated tests
5. Restored "quote in topic" on desktop (regressed in #974)
6. Exposed "copy quote" as a separate button
---
> FIX: Restore/fix quote-in-topic and copy-quote features

- assets/stylesheets/common/chat-channel-info.scss
- assets/stylesheets/common/chat-tabs.scss
> UX: alignment member tab

- assets/javascripts/discourse/components/chat-live-pane.js
Reverts discourse/discourse-chat#1101
> Revert "FEATURE: scroll to sidebar chat section on enter"

- lib/validators/chat_default_channel_validator.rb
- spec/validators/chat_default_channel_validator_spec.rb
Don't hard-code ids in spec. Those will eventually fail.
Also improved the whole spec and `valid_value?` method.
> DEV: Fix flaky validator spec

- assets/stylesheets/sidebar-extensions.scss
Remove after https://github.com/discourse/discourse/pull/17980
> DEV: Remove redundant sidebar css

- spec/requests/chat_controller_spec.rb
The order of records was undefined
> DEV: Fix flaky spec

- assets/stylesheets/desktop/chat-composer-uploads.scss
- plugin.rb
> Fix for desktop

- assets/javascripts/discourse/templates/components/chat-composer.hbs
- assets/javascripts/discourse/templates/components/chat-message.hbs
- assets/stylesheets/common/chat-message.scss
- config/locales/client.en.yml
> UI: improves retry send staged message style

- assets/stylesheets/mobile/chat-message.scss
Nesting of translate3d causes flickering
> FIX: only translate on chat-message-container

- assets/javascripts/discourse/components/chat-message.js
- assets/javascripts/discourse/templates/components/chat-live-pane.hbs
- assets/javascripts/discourse/templates/components/chat-message.hbs
- test/javascripts/acceptance/chat-message-bookmarking-test.js
- test/javascripts/acceptance/chat-test.js
This is to avoid rendering bug du to position and translate3d on chat-message
> FIX: renders emoji-picker out of message

- assets/javascripts/discourse/components/user-menu/chat-notifications-list.js
- assets/javascripts/discourse/initializers/chat-user-menu.js
Related PR: https://github.com/discourse/discourse/pull/18164
> FIX: defined notifications types for user menu

- assets/stylesheets/common/chat-channel-title.scss
- assets/stylesheets/common/common.scss
- assets/stylesheets/mobile/mobile.scss
> UX: Fix alignment of full-page-header elements

- assets/stylesheets/common/chat-channel-card.scss
- assets/stylesheets/common/chat-channel-title.scss
- assets/stylesheets/common/chat-message-separator.scss
- assets/stylesheets/common/chat-message.scss
- assets/stylesheets/common/common.scss
- assets/stylesheets/desktop/desktop.scss
- assets/stylesheets/mobile/chat-message.scss
- assets/stylesheets/sidebar-extensions.scss
> DEV: Various css tweaks

- lib/extensions/user_extension.rb
- plugin.rb
- spec/models/user_spec.rb
Follow up to https://github.com/discourse/discourse-chat/pull/1211/files#r959578410
> DEV: Extract patch to User into a dedicated module

- spec/integration/post_chat_quote_spec.rb
- spec/models/chat_message_spec.rb
- test/javascripts/acceptance/chat-transcript-test.js
Temp PR for hiding tests till core is up to date
> DEV: Temporarily skip reactions test

- config/locales/server.en.yml
- db/migrate/20220802014549_disable_chat_uploads_if_secure_media_enabled.rb
- lib/chat_message_processor.rb
- lib/secure_uploads_compatibility.rb
- lib/validators/chat_allow_uploads_validator.rb
- plugin.rb
- spec/plugin_spec.rb
- spec/validators/chat_allow_uploads_validator_spec.rb
Following up changes in core PR https://github.com/discourse/discourse/pull/18376
**Do not merge until core PR is merged.**
> DEV: Change secure_media references to secure_uploads

- assets/stylesheets/sidebar-extensions.scss
Dependent on https://github.com/discourse/discourse/pull/18378
> DEV: Remove unnecessary core CSS overrides

- assets/javascripts/discourse/components/chat-live-pane.js
Note this refactoring will also fix a bug where a link to a message in the currently viewed channel was not loading the message as expected.
> FIX: simplifies loading message code

- spec/serializer/chat_message_serializer_spec.rb
c.f. core PR https://github.com/discourse/discourse/pull/18437
> DEV: Remove old setting references in spec

- test/javascripts/components/chat-channel-about-view-test.js
- test/javascripts/components/chat-channel-card-test.js
- test/javascripts/components/chat-channel-title-test.js
> DEV: Add component tests for places where we use replace-emoji

- config/locales/server.en.yml
- lib/chat_seeder.rb
- spec/components/chat_seeder_spec.rb
Now that the General category is being seeded for new sites we can link
the general chat channel to it.
> FEATURE: Link general chat channel to general category

- assets/javascripts/discourse/initializers/chat-sidebar.js
- assets/stylesheets/sidebar-extensions.scss
- test/javascripts/acceptance/core-sidebar-test.js
* Adds tests to ensure that CSS class is added when channels are muted
as well.
> DEV: Add proper CSS class for sidebar section link content

- app/models/chat_channel.rb
- db/migrate/20221014005208_add_slug_column_to_chat_channel.rb
This commit just adds the column and index,
backfilling and filling it when creating/updating
will come later pending other refactors in
https://github.com/discourse/discourse-chat/pull/1284
> DEV: Add slug column to chat_channel model

- spec/jobs/regular/auto_join_channel_batch_spec.rb
- spec/jobs/regular/auto_manage_channel_memberships_spec.rb
See: https://github.com/discourse/discourse-chat/pull/988#discussion_r985642408
> DEV: Fix flaky specs

- assets/javascripts/discourse/services/chat-emoji-picker-manager.js
This issue was identified automatically by https://github.com/discourse/discourse/pull/18666
> DEV: Ensure timer does not run beyond end of tests

- assets/javascripts/discourse/components/chat-composer.js
- assets/javascripts/discourse/components/chat-live-pane.js
- assets/javascripts/discourse/components/chat-message-actions-desktop.js
- assets/javascripts/discourse/components/chat-message.js
- assets/javascripts/discourse/services/chat-emoji-reaction-store.js
- assets/stylesheets/desktop/desktop.scss
- test/javascripts/acceptance/chat-composer-test.js
- test/javascripts/acceptance/chat-message-test.js
- test/javascripts/acceptance/chat-test.js
- test/javascripts/unit/lib/chat-emoji-reaction-store-test.js
- now sort emojis by most used and recent
- ensures we track emojis in every cases where we use them
- adds tests
> FIX: improve chat emoji reactions

- assets/javascripts/discourse/templates/components/toggle-channel-membership-button.hbs
- assets/stylesheets/common/chat-browse.scss
- assets/stylesheets/common/chat-channel-card.scss
> UX: fix link colour channel cards

- assets/javascripts/discourse/components/channels-list.js
- assets/javascripts/discourse/components/chat-draft-channel-screen.js
- assets/javascripts/discourse/templates/components/channels-list.hbs
- assets/javascripts/discourse/templates/components/chat-draft-channel-screen.hbs
- assets/stylesheets/common/chat-channel-title.scss
- assets/stylesheets/common/chat-draft-channel.scss
- assets/stylesheets/common/common.scss
- assets/stylesheets/mixins/chat-scrollbar.scss
- assets/stylesheets/mobile/chat-drawer.scss
- assets/stylesheets/mobile/mobile.scss
- config/locales/client.en.yml
- plugin.rb
- test/javascripts/acceptance/chat-test.js
- test/javascripts/acceptance/mobile-chat-test.js
|Before|After|
|---|---|
|![Screenshot 2022-10-26 at 11 01 11 AM](https://user-images.githubusercontent.com/30090424/198101784-c3722cde-f1b8-4ecd-95a9-e88fd4d4525a.png)|![Screenshot 2022-10-26 at 11 28 04 AM](https://user-images.githubusercontent.com/30090424/198106869-020e4b40-cbec-4600-b356-06e15467d041.png)|
|![Screenshot 2022-10-26 at 11 01 36 AM](https://user-images.githubusercontent.com/30090424/198101819-c4c41b4f-ca5e-44e7-a3b0-12053fd56ea8.png)|![Screenshot 2022-10-26 at 11 06 00 AM](https://user-images.githubusercontent.com/30090424/198102649-0020dce5-1972-4abd-90ec-bf5354c5c0ab.png)|
Light Mode:
https://user-images.githubusercontent.com/30090424/198123066-c79a135f-9976-473e-b9b9-bf3648e3497f.MP4
Dark Mode:
https://user-images.githubusercontent.com/30090424/198123435-f1f59df4-4c01 …
> FEATURE: Improve mobile chat experience

- assets/stylesheets/mobile/chat-index.scss
> UX: reduced sizing
